#!/usr/bin/env python3
"""Relocate Nanjing-specific gameplay from former province 1821 to Jiangning 5056."""

from __future__ import annotations

import argparse
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[2]
MOD = ROOT / "guangdong_independent_practice"
OLD_NANJING = 1821  # now Liuhe
NEW_NANJING = 5056  # Jiangning


def named_block(text: str, name: str) -> str:
    match = re.search(rf"(?m)^\s*{re.escape(name)}\s*=\s*\{{", text)
    if not match:
        raise ValueError(f"Missing block: {name}")
    brace = text.find("{", match.start())
    depth = 0
    for index in range(brace, len(text)):
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                return text[match.start():index + 1]
    raise ValueError(f"Unclosed block: {name}")


def replace_named_block(text: str, name: str, replacement: str) -> str:
    old = named_block(text, name)
    return text.replace(old, replacement, 1)


def replace_province_id(text: str, old: int, new: int) -> str:
    return re.sub(rf"(?<!\d){old}(?!\d)", str(new), text)


def initial_value(text: str, key: str) -> str | None:
    match = re.search(rf"(?m)^\s*{re.escape(key)}\s*=\s*([^#\r\n]+)", text)
    return match.group(1).strip() if match else None


def history_path(province_id: int) -> Path:
    paths = [
        path for path in (MOD / "history/provinces").glob("*.txt")
        if re.match(rf"{province_id}(?:\D|$)", path.name)
    ]
    if len(paths) != 1:
        raise ValueError(f"Expected one history for {province_id}; found {paths}")
    return paths[0]


def validate_histories() -> None:
    liuhe = history_path(1821).read_text(encoding="utf-8-sig")
    jiangning = history_path(5056).read_text(encoding="utf-8-sig")
    expected = {
        "liuhe": {
            "culture": "gdd_wu", "trade_goods": "grain", "base_tax": "7",
            "base_production": "8", "base_manpower": "4",
        },
        "jiangning": {
            "culture": "gdd_jianghuai", "trade_goods": "silk", "base_tax": "2",
            "base_production": "2", "base_manpower": "1",
            "fort_15th": "yes",
        },
    }
    for label, text in (("liuhe", liuhe), ("jiangning", jiangning)):
        for key, value in expected[label].items():
            if initial_value(text, key) != value:
                raise ValueError(f"{label} {key} is not the reviewed value {value}")
    if initial_value(liuhe, "fort_15th") is not None:
        raise ValueError("Liuhe still carries Nanjing's 15th-century fort")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--vanilla-root", type=Path, required=True)
    args = parser.parse_args()
    vanilla = args.vanilla_root.resolve()

    validate_histories()

    monument_source = (vanilla / "common/great_projects/01_monuments.txt").read_text(
        encoding="utf-8-sig"
    )
    monument_blocks = []
    for name in ("porcelain_tower_nanjing", "grand_canal_4"):
        block = replace_province_id(named_block(monument_source, name), OLD_NANJING, NEW_NANJING)
        if not re.search(rf"(?m)^\s*start\s*=\s*{NEW_NANJING}\b", block):
            raise ValueError(f"{name} was not relocated")
        monument_blocks.append(block)
    monument_output = MOD / "common/great_projects/zz_gdd_nanjing_relocation.txt"
    monument_output.write_text(
        "# Generated by apply_nanjing_semantic_relocation.py\n"
        "# Jiangning 5056 is the mod's physical Nanjing; 1821 is Liuhe.\n\n"
        + "\n\n".join(monument_blocks) + "\n",
        encoding="utf-8",
    )

    agenda_source = (vanilla / "common/estate_agendas/09_eunuchs_agendas.txt").read_text(
        encoding="utf-8-sig"
    )
    agenda = replace_province_id(
        named_block(agenda_source, "estate_eunuchs_porcelain_tower_agenda"),
        OLD_NANJING,
        NEW_NANJING,
    )
    agenda_output = MOD / "common/estate_agendas/zz_gdd_nanjing_relocation.txt"
    agenda_output.parent.mkdir(parents=True, exist_ok=True)
    agenda_output.write_text(
        "# Generated by apply_nanjing_semantic_relocation.py\n"
        "# Override the vanilla porcelain-tower agenda to target Jiangning.\n\n"
        + agenda + "\n",
        encoding="utf-8",
    )

    modifiers_path = MOD / "common/triggered_modifiers/00_triggered_modifiers.txt"
    modifiers = modifiers_path.read_text(encoding="utf-8-sig")
    for name in ("ai_wants_chinese_capitals", "lost_control_of_nanjing"):
        block = named_block(modifiers, name)
        relocated = replace_province_id(block, OLD_NANJING, NEW_NANJING)
        modifiers = replace_named_block(modifiers, name, relocated)
    modifiers_path.write_text(modifiers, encoding="utf-8")

    for path in (monument_output, agenda_output):
        text = path.read_text(encoding="utf-8")
        executable_text = re.sub(r"#.*", "", text)
        if re.search(rf"(?<!\d){OLD_NANJING}(?!\d)", executable_text):
            raise ValueError(f"Stale Nanjing ID remains in {path}")
    checked_modifiers = modifiers_path.read_text(encoding="utf-8")
    for name in ("ai_wants_chinese_capitals", "lost_control_of_nanjing"):
        block = named_block(checked_modifiers, name)
        if str(OLD_NANJING) in block or str(NEW_NANJING) not in block:
            raise ValueError(f"Triggered modifier {name} was not relocated")

    print("Nanjing semantic relocation applied: 1821 Liuhe -> 5056 Jiangning")


if __name__ == "__main__":
    main()
