#!/usr/bin/env python3
"""Apply and validate the canonical 1444 Lingnan nation setup."""

from __future__ import annotations

import argparse
from collections import Counter
import json
import re
from pathlib import Path

from encode_eu4_chinese_localisation import from_escaped_bytes, to_escaped_bytes


ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "guangdong_independent_practice"
MANIFEST = ROOT / "planning/lingnan_nations/lingnan_nations_manifest.json"
COUNTRIES = MOD / "history/countries"
PROVINCES = MOD / "history/provinces"
DIPLOMACY = MOD / "history/diplomacy/gdd_lingnan_dependencies.txt"
DEFINITION = MOD / "map/definition.csv"
IDEAS = MOD / "common/ideas/gdd_ideas.txt"
GOVERNMENT_NAMES = MOD / "common/government_names/00_gdd_government_names.txt"
GDD_ON_ACTIONS = MOD / "common/on_actions/gdd_on_actions.txt"
GDD_STARTUP_EVENTS = MOD / "events/gdd_startup_events.txt"
LOCALISATION_SOURCE = MOD / "localisation_source/017_gdd_lingnan_nations_readable_utf8.txt"
LOCALISATION_SOURCE_ROOT = MOD / "localisation_source"
GDD_GENERAL_LOCALISATION_SOURCE = LOCALISATION_SOURCE_ROOT / "gdd_l_english_readable_utf8.txt"
GDD_TREATY_LOCALISATION_SOURCE = LOCALISATION_SOURCE_ROOT / "gdd_treaty_readable_utf8.txt"
OPENING_SCHOOLS = ROOT / "planning/religion_opening_schools/opening_schools_manifest.json"
GDD_LINKED_EVENTS = (
    MOD / "events/gdd_heir_events.txt",
    GDD_STARTUP_EVENTS,
)
DAI_CAPITAL_BEGIN = "# GDD_LINGNAN_DAI_CAPITAL_BEGIN"
DAI_CAPITAL_END = "# GDD_LINGNAN_DAI_CAPITAL_END"


def load_manifest() -> dict[str, object]:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if manifest.get("schema_version") != 1:
        raise ValueError("unsupported Lingnan nation manifest schema")
    if manifest.get("campaign_start") != "1444.11.11":
        raise ValueError("Lingnan nation manifest must target 1444.11.11")
    return manifest


def render_character(kind: str, character: dict[str, object], config: dict[str, object]) -> list[str]:
    lines = [f"    {kind} = {{"]
    lines.append(f'        name = "{character["name"]}"')
    dynasty = character.get("dynasty")
    if dynasty:
        lines.append(f'        dynasty = "{dynasty}"')
    if character.get("birth_date"):
        lines.append(f'        birth_date = {character["birth_date"]}')
    for stat in ("adm", "dip", "mil"):
        lines.append(f"        {stat} = {character[stat]}")
    if kind == "heir":
        lines.append(f"        claim = {character.get('claim', 70)}")
    if character.get("female"):
        lines.append("        female = yes")
    lines.append(f"        culture = {character.get('culture', config['primary_culture'])}")
    lines.append(f"        religion = {character.get('religion', config['religion'])}")
    lines.append("    }")
    return lines


def render_country(tag: str, config: dict[str, object], campaign_start: str) -> str:
    lines = [
        "# Generated by tools/apply_lingnan_nations.py from the reviewed manifest.",
        f"government = {config['government']}",
        f"add_government_reform = {config['reform']}",
        f"government_rank = {config['rank']}",
        "",
    ]
    if "mercantilism" in config:
        lines.append(f"mercantilism = {config['mercantilism']}")
    lines.extend(
        [
            f"primary_culture = {config['primary_culture']}",
            *(f"add_accepted_culture = {culture}" for culture in config["accepted_cultures"]),
            f"religion = {config['religion']}",
            "technology_group = chinese",
            f"capital = {config['capital']}",
            f"fixed_capital = {config['capital']}",
            "",
            f"{campaign_start} = {{",
            *render_character("monarch", config["ruler"], config),
        ]
    )
    if tag == "GDD":
        lines.extend(
            [
                "    clear_scripted_personalities = yes",
                "    add_ruler_personality = gdd_liang_shouqian_prestige_personality",
                "    add_ruler_personality = gdd_liang_shouqian_unrest_personality",
                "    add_ruler_personality = gdd_liang_shouqian_corruption_personality",
            ]
        )
    if "heir" in config:
        lines.extend(render_character("heir", config["heir"], config))
        if tag == "GDD":
            lines.append("    add_heir_personality = gdd_liang_shouyi_personality")
    elif "successor_candidate" in config:
        candidate = config["successor_candidate"]
        lines.extend(
            [
                "    # A military republic has no monarchic heir slot; this named",
                "    # general enters its generals-become-rulers succession pool.",
                "    leader = {",
                f'        name = "{candidate["dynasty"]}{candidate["name"]}"',
                "        type = general",
                f'        fire = {candidate["fire"]}',
                f'        shock = {candidate["shock"]}',
                f'        manuever = {candidate["manuever"]}',
                f'        siege = {candidate["siege"]}',
                "    }",
            ]
        )
    lines.extend(["}", ""])
    return "\n".join(lines)


def render_diplomacy(dependencies: list[dict[str, str]]) -> str:
    blocks: list[str] = [
        "# Generated by tools/apply_lingnan_nations.py from the reviewed manifest.",
    ]
    for relation in dependencies:
        blocks.extend(
            [
                "dependency = {",
                f'    subject_type = "{relation["subject_type"]}"',
                f'    first = {relation["overlord"]}',
                f'    second = {relation["subject"]}',
                f'    start_date = {relation["start_date"]}',
                "    end_date = 1821.1.1",
                "}",
            ]
        )
    return "\n".join(blocks) + "\n"


def update_gdd_linked_events() -> None:
    """Keep the pre-existing heir lifecycle while adopting the new heir identity."""
    for path in GDD_LINKED_EVENTS:
        text = from_escaped_bytes(path.read_bytes())
        text = text.replace('name = "守毅"', 'name = "继垣"')
        text = text.replace('monarch_name = "守毅"', 'monarch_name = "继垣"')
        text = text.replace("Shouyi succeeds Shouqian", "Jiyuan succeeds Shouqian")
        text = text.replace(
            "# Liang Shouqian alone may use the title King of Lingnan. Any succession,\n"
            "# including abdication, clears the flag used by the government-name trigger.",
            "# Track Liang Shouqian's reign for the named-heir lifecycle. Any succession,\n"
            "# including abdication, clears this compatibility flag.",
        )
        text = text.replace(
            "adm = 2\n                dip = 3\n                mil = 5",
            "adm = 4\n                dip = 2\n                mil = 5",
        )
        path.write_bytes(to_escaped_bytes(text))


def render_dai_capital_migration() -> str:
    """Return the one-shot old-save repair that enforces the Hue canon."""
    return f"""{DAI_CAPITAL_BEGIN}
# Old saves may retain Hai Phong from an earlier build. Move the court only
# while Annam still owns Hue, then permanently retire this compatibility pass.
country_event = {{
    id = gdd_startup.7
    hidden = yes
    is_triggered_only = yes

    trigger = {{
        tag = DAI
        NOT = {{ has_country_flag = gdd_dai_hue_capital_checked }}
    }}

    immediate = {{
        if = {{
            limit = {{
                owns = 2373
                NOT = {{ capital = 2373 }}
            }}
            set_capital = 2373
        }}
        set_country_flag = gdd_dai_hue_capital_checked
    }}

    option = {{ name = OK }}
}}
{DAI_CAPITAL_END}
"""


def update_dai_capital_migration() -> None:
    text = from_escaped_bytes(GDD_STARTUP_EVENTS.read_bytes())
    marker_block = re.compile(
        rf"\n?{re.escape(DAI_CAPITAL_BEGIN)}.*?{re.escape(DAI_CAPITAL_END)}\n?",
        re.DOTALL,
    )
    text = marker_block.sub("\n", text).rstrip()
    text = f"{text}\n\n{render_dai_capital_migration()}"
    GDD_STARTUP_EVENTS.write_bytes(to_escaped_bytes(text))


def apply(manifest: dict[str, object]) -> None:
    campaign_start = str(manifest["campaign_start"])
    for tag, raw_config in manifest["countries"].items():
        config = dict(raw_config)
        target = COUNTRIES / str(config["history"])
        target.write_bytes(to_escaped_bytes(render_country(tag, config, campaign_start)))
    DIPLOMACY.parent.mkdir(parents=True, exist_ok=True)
    DIPLOMACY.write_text(render_diplomacy(manifest["dependencies"]), encoding="utf-8")
    update_gdd_linked_events()
    update_dai_capital_migration()


def first_value(text: str, key: str) -> str:
    match = re.search(rf"(?m)^\s*{re.escape(key)}\s*=\s*([^\s#]+)", text)
    if not match:
        raise ValueError(f"missing initial {key}")
    return match.group(1)


def matching_close(text: str, opening: int) -> int:
    depth = 0
    in_string = False
    in_comment = False
    escaped = False
    for index in range(opening, len(text)):
        character = text[index]
        if in_comment:
            if character == "\n":
                in_comment = False
            continue
        if in_string:
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == '"':
                in_string = False
            continue
        if character == "#":
            in_comment = True
        elif character == '"':
            in_string = True
        elif character == "{":
            depth += 1
        elif character == "}":
            depth -= 1
            if depth == 0:
                return index
    raise ValueError("Clausewitz block has no matching close")


def top_level_block(text: str, key: str) -> str:
    match = re.search(rf"(?m)^{re.escape(key)}\s*=\s*\{{", text)
    if not match:
        raise ValueError(f"missing top-level block {key}")
    opening = text.find("{", match.start())
    return text[opening + 1 : matching_close(text, opening)]


def province_history(province_id: int) -> Path:
    matches = sorted(PROVINCES.glob(f"{province_id} -*.txt"))
    if len(matches) != 1:
        raise ValueError(f"capital province {province_id} has {len(matches)} local histories")
    return matches[0]


def validate(manifest: dict[str, object]) -> dict[str, int]:
    countries = manifest["countries"]
    expected_tags = {"GDD", "GUI", "CZC", "HAK", "NUN", "TZZ", "LIL", "DAI"}
    if set(countries) != expected_tags:
        raise ValueError("Lingnan manifest tag set drifted")

    dai_config = countries["DAI"]
    if dai_config["capital"] != 2373:
        raise ValueError("DAI canon capital must be Hue (2373), never Hai Phong (2372)")
    definitions = {
        int(parts[0]): parts[4]
        for line in DEFINITION.read_text(encoding="latin-1").splitlines()
        if len(parts := line.split(";")) >= 5 and parts[0].isdigit()
    }
    if definitions.get(2373) != "Hue" or definitions.get(2372) != "Hai Phong":
        raise ValueError("province identity drifted: 2373 must be Hue and 2372 Hai Phong")

    idea_text = IDEAS.read_text(encoding="utf-8")
    expected_idea_groups = {str(config["idea_group"]) for config in countries.values()}
    idea_keys: set[str] = set()
    for group in expected_idea_groups:
        if len(re.findall(rf"(?m)^{re.escape(group)}\s*=\s*\{{", idea_text)) != 1:
            raise ValueError(f"idea group {group} must be defined exactly once in the mod provider")
        body = top_level_block(idea_text, group)
        direct_blocks = re.findall(r"(?m)^    ([a-zA-Z0-9_]+)\s*=\s*\{", body)
        inner_ideas = [key for key in direct_blocks if key not in {"start", "bonus", "trigger"}]
        if len(inner_ideas) != 7:
            raise ValueError(f"{group}: expected seven ideas, found {len(inner_ideas)}")
        idea_keys.update(inner_ideas)
        if "free = yes" not in body:
            raise ValueError(f"{group}: national ideas must be free at load")

    localisation_pattern = re.compile(r"(?m)^\s*([a-zA-Z0-9_.]+):[0-9]+\s+")
    localisation_text = LOCALISATION_SOURCE.read_text(encoding="utf-8-sig")
    localisation_counts = Counter(localisation_pattern.findall(localisation_text))
    localisation_keys = set(localisation_counts)
    required_localisation = {
        *(tag for tag in expected_tags),
        *(f"{tag}_ADJ" for tag in expected_tags),
        *(group for group in expected_idea_groups),
        *(f"{group}_start" for group in expected_idea_groups),
        *(f"{group}_bonus" for group in expected_idea_groups),
        *(key for key in idea_keys),
        *(f"{key}_desc" for key in idea_keys),
        "GDD_DYNASTIC_FEUDATORY",
        "GDD_EARL",
        "GDD_COUNTESS",
        "GDD_CONSORT",
        "GDD_HEIR",
        "CZC_ELDER_COUNCIL",
        "CZC_RAOPING_EARL",
        "CZC_COUNCIL_ELDER",
        "HAK_REPUBLIC",
        "HAK_PRESIDENT_GENERAL",
        "NUN_TRIBAL_KINGDOM",
        "NUN_GREAT_CAVE_LORD",
        "GDD_CAVE_POLITY",
        "GDD_CAVE_LORD",
        "string_start_gdd",
        "string_start_dai_viet",
    }
    missing_localisation = required_localisation - localisation_keys
    if missing_localisation:
        raise ValueError(f"Lingnan localisation keys are missing: {sorted(missing_localisation)}")
    duplicated_localisation = {
        key: count for key, count in localisation_counts.items() if count != 1
    }
    if duplicated_localisation:
        raise ValueError(
            "Lingnan localisation source keys must be unique: "
            f"{duplicated_localisation}"
        )
    for path in sorted(LOCALISATION_SOURCE_ROOT.rglob("*.txt")):
        if path == LOCALISATION_SOURCE:
            continue
        competing_keys = localisation_keys & set(
            localisation_pattern.findall(path.read_text(encoding="utf-8-sig"))
        )
        if competing_keys:
            raise ValueError(
                f"{path.name}: duplicates canonical Lingnan localisation keys "
                f"{sorted(competing_keys)}"
            )

    general_localisation = GDD_GENERAL_LOCALISATION_SOURCE.read_text(encoding="utf-8-sig")
    treaty_localisation = GDD_TREATY_LOCALISATION_SOURCE.read_text(encoding="utf-8-sig")
    if "梁氏兄弟" in general_localisation or "梁氏兄弟" in treaty_localisation:
        raise ValueError("obsolete Liang-brothers narrative remains in player-facing text")
    if 'GDD_BOOKMARK_NAME:0 "南海中兴"' not in general_localisation:
        raise ValueError("GDD bookmark title does not follow the Nanhai canon")
    if "重建周室旧封南海侯国" not in general_localisation:
        raise ValueError("GDD bookmark description does not follow the Nanhai canon")

    government_names = GOVERNMENT_NAMES.read_text(encoding="utf-8")
    for tag in expected_tags:
        if f"tag = {tag}" not in government_names:
            raise ValueError(f"{tag}: custom government-title trigger is missing")

    school_manifest = json.loads(OPENING_SCHOOLS.read_text(encoding="utf-8"))
    school_by_tag = {
        tag: school
        for school, school_config in school_manifest["schools"].items()
        for tag in school_config["tags"]
    }
    for tag, config in countries.items():
        expected_school = config["opening_doctrine"]
        if school_by_tag.get(tag) != expected_school:
            raise ValueError(
                f"{tag}: opening doctrine {school_by_tag.get(tag)!r}, expected {expected_school!r}"
            )

    for tag, raw_config in countries.items():
        config = dict(raw_config)
        path = COUNTRIES / str(config["history"])
        decoded = from_escaped_bytes(path.read_bytes())
        expected = render_country(tag, config, str(manifest["campaign_start"]))
        if decoded != expected:
            raise ValueError(f"{tag}: generated country history drifted from its manifest")
        for key in ("government", "government_rank", "primary_culture", "religion", "capital"):
            expected_value = {
                "government": config["government"],
                "government_rank": config["rank"],
                "primary_culture": config["primary_culture"],
                "religion": config["religion"],
                "capital": config["capital"],
            }[key]
            if first_value(decoded, key) != str(expected_value):
                raise ValueError(f"{tag}: {key} does not match the manifest")
        province = province_history(int(config["capital"]))
        province_text = province.read_text(encoding="latin-1")
        if first_value(province_text, "owner") != tag:
            raise ValueError(f"{tag}: capital {config['capital']} is not owned at scenario start")
        if tag == "DAI":
            if first_value(province_text, "controller") != "DAI":
                raise ValueError("DAI: Hue must be controlled by DAI at scenario start")
            if not re.search(r"(?m)^\s*add_core\s*=\s*DAI\s*$", province_text):
                raise ValueError("DAI: Hue must be a DAI core at scenario start")

    dependency_text = DIPLOMACY.read_text(encoding="utf-8")
    if dependency_text != render_diplomacy(manifest["dependencies"]):
        raise ValueError("Lingnan dependency history drifted from its manifest")
    if dependency_text.count("dependency = {") != 2:
        raise ValueError("Lingnan dependency history must contain exactly two relations")
    for relation in manifest["dependencies"]:
        if relation["subject_type"] != "tributary_state" or relation["overlord"] != "NUN":
            raise ValueError("only NUN tributary relations are permitted in this batch")
    all_diplomacy = "\n".join(
        path.read_text(encoding="latin-1")
        for path in sorted((MOD / "history/diplomacy").glob("*.txt"))
    )
    for subject in ("TZZ", "LIL"):
        if len(re.findall(rf"(?m)^\s*second\s*=\s*{subject}\s*$", all_diplomacy)) != 1:
            raise ValueError(f"{subject}: must have exactly one historical dependency")
    if re.search(r"(?m)^\s*second\s*=\s*NUN\s*$", all_diplomacy):
        raise ValueError("NUN may not itself begin as a subject")

    gdd_heir = countries["GDD"]["heir"]
    heir_name = str(gdd_heir["name"])
    heir_stats_pattern = re.compile(
        rf'name\s*=\s*"{re.escape(heir_name)}"[\s\S]{{0,320}}?'
        rf'adm\s*=\s*{gdd_heir["adm"]}[\s\S]{{0,100}}?'
        rf'dip\s*=\s*{gdd_heir["dip"]}[\s\S]{{0,100}}?'
        rf'mil\s*=\s*{gdd_heir["mil"]}'
    )
    for path in GDD_LINKED_EVENTS:
        text = from_escaped_bytes(path.read_bytes())
        if 'name = "守毅"' in text or 'monarch_name = "守毅"' in text:
            raise ValueError(f"{path.name}: obsolete displayed heir name remains")
        if not heir_stats_pattern.search(text):
            raise ValueError(
                f"{path.name}: linked heir identity or stats drifted from the manifest"
            )

    on_actions = GDD_ON_ACTIONS.read_text(encoding="utf-8")
    if on_actions.count("gdd_startup.7") != 2:
        raise ValueError("Hue capital repair must run on startup and monthly pulse")
    startup_events = from_escaped_bytes(GDD_STARTUP_EVENTS.read_bytes())
    if startup_events.count(DAI_CAPITAL_BEGIN) != 1 or startup_events.count(DAI_CAPITAL_END) != 1:
        raise ValueError("Hue capital repair marker block must exist exactly once")
    capital_repair = startup_events[
        startup_events.index(DAI_CAPITAL_BEGIN) : startup_events.index(DAI_CAPITAL_END)
    ]
    for required in (
        "id = gdd_startup.7",
        "tag = DAI",
        "owns = 2373",
        "NOT = { capital = 2373 }",
        "set_capital = 2373",
    ):
        if required not in capital_repair:
            raise ValueError(f"Hue capital repair is missing: {required}")
    if "吴氏已经把朝廷迁至顺化" not in localisation_text or "海防为都" in localisation_text:
        raise ValueError("Annam introduction does not follow the Hue-capital canon")

    return {
        "countries": len(countries),
        "idea_groups": len(expected_idea_groups),
        "dependencies": len(manifest["dependencies"]),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    manifest = load_manifest()
    if not args.check:
        apply(manifest)
    result = validate(manifest)
    print(
        "LINGNAN_NATIONS_VALID; "
        f"countries={result['countries']}; idea_groups={result['idea_groups']}; "
        f"dependencies={result['dependencies']}"
    )


if __name__ == "__main__":
    main()
