#!/usr/bin/env python3
"""Build the closed-loop Ritual Teaching guest-school contract.

The native religious-school selector remains the source picker.  This builder
owns the scripted confirmation, twenty-year lifecycle, renewal, honourable
return, early expulsion, AI gates, modifiers, decisions, and source-country
relationship marker.  Main-school flags remain authoritative.
"""

from __future__ import annotations

import argparse
from collections import OrderedDict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "guangdong_independent_practice"

SCHOOLS = OrderedDict(
    (
        ("ru", ("zhx_ru_school", "zhx_doctrine_ru", "zhx_ru_invited_scholar_modifier")),
        ("fa", ("zhx_fa_school", "zhx_doctrine_fa", "zhx_fa_invited_scholar_modifier")),
        ("mo", ("zhx_mo_school", "zhx_doctrine_mo", "zhx_mo_invited_scholar_modifier")),
        ("dao", ("zhx_dao_school", "zhx_doctrine_dao", "zhx_dao_invited_scholar_modifier")),
        ("bing", ("zhx_bing_school", "zhx_doctrine_bing", "zhx_bing_invited_scholar_modifier")),
        (
            "zongheng",
            (
                "zhx_zongheng_school",
                "zhx_doctrine_zongheng",
                "zhx_zongheng_invited_scholar_modifier",
            ),
        ),
    )
)

TARGETS = {
    "triggers": MOD / "common/scripted_triggers/zhx_guest_school_triggers.txt",
    "effects": MOD / "common/scripted_effects/zhx_guest_school_effects.txt",
    "modifiers": MOD / "common/event_modifiers/zhx_guest_school_modifiers.txt",
    "opinions": MOD / "common/opinion_modifiers/zhx_guest_school_opinions.txt",
    "decisions": MOD / "decisions/zhx_guest_school_decisions.txt",
    "events": MOD / "events/zhx_guest_school_events.txt",
}


def or_block(lines: list[str], indent: str = "        ") -> str:
    return "OR = {\n" + "\n".join(f"{indent}{line}" for line in lines) + "\n    }"


def render_triggers() -> str:
    invited = [f"has_country_modifier = {meta[2]}" for meta in SCHOOLS.values()]
    contract_schools = [
        f"has_country_flag = zhx_guest_school_contract_{code}" for code in SCHOOLS
    ]
    parts = [
        "# Generated by tools/build_zhx_guest_school.py. Do not hand-edit.",
        "",
        "zhx_guest_school_has_any_invited_benefit = {",
        "    " + or_block(invited).replace("\n", "\n    "),
        "}",
        "",
        "zhx_guest_school_has_active_contract = {",
        "    has_country_flag = zhx_guest_school_contract_active",
        "    " + or_block(contract_schools).replace("\n", "\n    "),
        "}",
        "",
        "zhx_guest_school_may_invite = {",
        "    zhx_is_lijiao_country = yes",
        "    zhx_has_doctrine = yes",
        "    has_religious_school = yes",
        "    NOT = { zhx_doctrine_reform_invitation_locked = yes }",
        "    NOT = { has_country_flag = zhx_guest_school_contract_active }",
        "    NOT = { zhx_guest_school_has_active_contract = yes }",
        "    NOT = {",
        "        " + or_block(contract_schools).replace("\n", "\n        "),
        "    }",
        "    NOT = { has_country_modifier = zhx_guest_school_dishonour }",
        "    NOT = { zhx_guest_school_has_any_invited_benefit = yes }",
        "    dip_power = 75",
        "    years_of_income = 0.5",
        "}",
    ]

    for code, (native, doctrine, modifier) in SCHOOLS.items():
        parts.extend(
            [
                "",
                f"# Evaluated in the prospective source country; ROOT is the inviter.",
                f"zhx_guest_school_source_is_eligible_{code} = {{",
                "    exists = yes",
                "    NOT = { tag = ROOT }",
                "    zhx_is_lijiao_country = yes",
                f"    has_country_flag = {doctrine}",
                "    religious_school = {",
                "        group = eastern",
                f"        school = {native}",
                "    }",
                "    has_opinion = { who = ROOT value = 150 }",
                "    capital_scope = { ROOT = { has_discovered = PREV } }",
                "    OR = {",
                "        NOT = { is_subject_of = ROOT }",
                "        NOT = { liberty_desire = 50 }",
                "    }",
                "}",
                "",
                f"zhx_guest_school_pending_{code}_is_valid = {{",
                "    zhx_guest_school_may_invite = yes",
                f"    NOT = {{ has_country_flag = {doctrine} }}",
                f"    has_country_flag = zhx_guest_school_pending_{code}",
                "    has_saved_event_target = zhx_guest_school_pending_source",
                "    event_target:zhx_guest_school_pending_source = {",
                f"        zhx_guest_school_source_is_eligible_{code} = yes",
                "    }",
                "}",
                "",
                f"zhx_guest_school_has_valid_{code}_renewal_source = {{",
                f"    has_country_flag = zhx_guest_school_contract_{code}",
                "    dip_power = 75",
                "    years_of_income = 0.5",
                "    any_country = {",
                f"        zhx_guest_school_source_is_eligible_{code} = yes",
                "    }",
                "}",
                "",
                f"# The unused plan flag is a stable future AI strategy port.",
                f"zhx_guest_school_ai_wants_{code} = {{",
                "    OR = {",
                f"        zhx_has_unprotected_{code}_academy = yes",
                f"        has_country_flag = zhx_guest_school_ai_plan_{code}",
                "    }",
                "}",
                "",
                f"# Renewal must inspect raw academy demand: the current guest",
                f"# itself makes zhx_has_unprotected_{code}_academy false until",
                f"# its modifier expires, and same-day callback order is undefined.",
                f"zhx_guest_school_ai_wants_renew_{code} = {{",
                "    OR = {",
                f"        zhx_has_{code}_academy = yes",
                f"        has_country_flag = zhx_guest_school_ai_plan_{code}",
                "    }",
                "}",
            ]
        )

    valid_renewal = [
        f"zhx_guest_school_has_valid_{code}_renewal_source = yes" for code in SCHOOLS
    ]
    parts.extend(
        [
            "",
            "zhx_guest_school_has_valid_renewal_source = {",
            "    " + or_block(valid_renewal).replace("\n", "\n    "),
            "}",
            "",
            "zhx_guest_school_ai_may_renew = {",
            "    ai = yes",
            "    is_at_war = no",
            "    stability = 0",
            "    NOT = { num_of_loans = 1 }",
            "    dip_power = 125",
            "    years_of_income = 0.5",
            "    zhx_guest_school_has_valid_renewal_source = yes",
            "    OR = {",
            *[
                f"        AND = {{ has_country_flag = zhx_guest_school_contract_{code} zhx_guest_school_ai_wants_renew_{code} = yes }}"
                for code in SCHOOLS
            ],
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(parts)


def render_effects() -> str:
    parts = [
        "# Generated by tools/build_zhx_guest_school.py. Do not hand-edit.",
        "",
        "zhx_guest_school_clear_pending = {",
        *[f"    clr_country_flag = zhx_guest_school_pending_{code}" for code in SCHOOLS],
        "}",
        "",
        "zhx_guest_school_clear_source_link = {",
        "    every_country = {",
        "        limit = {",
        "            has_opinion_modifier = {",
        "                who = ROOT",
        "                modifier = zhx_opinion_guest_school_source_link",
        "            }",
        "        }",
        "        remove_opinion = {",
        "            who = ROOT",
        "            modifier = zhx_opinion_guest_school_source_link",
        "        }",
        "    }",
        "}",
        "",
        "# Generation flags deliberately survive cleanup. A subsequent contract",
        "# toggles A/B so callbacks from an expelled earlier term cannot hit it.",
        "zhx_guest_school_clear_contract_state = {",
        *[f"    remove_country_modifier = {meta[2]}" for meta in SCHOOLS.values()],
        "    remove_country_modifier = zhx_guest_school_adjustment",
        "    remove_country_modifier = has_invited_scholar_recently",
        "    clr_country_flag = zhx_guest_school_contract_active",
        *[f"    clr_country_flag = zhx_guest_school_contract_{code}" for code in SCHOOLS],
        "    zhx_guest_school_clear_pending = yes",
        "    zhx_guest_school_clear_source_link = yes",
        "}",
        "",
        "zhx_guest_school_clear_silently = {",
        "    zhx_guest_school_clear_contract_state = yes",
        "}",
        "",
        "zhx_guest_school_toggle_generation_and_schedule = {",
        "    if = {",
        "        limit = { has_country_flag = zhx_guest_school_generation_a }",
        "        clr_country_flag = zhx_guest_school_generation_a",
        "        set_country_flag = zhx_guest_school_generation_b",
        "        country_event = { id = zhx_guest_school.21 days = 6935 }",
        "        country_event = { id = zhx_guest_school.31 days = 7300 }",
        "    }",
        "    else = {",
        "        clr_country_flag = zhx_guest_school_generation_b",
        "        set_country_flag = zhx_guest_school_generation_a",
        "        country_event = { id = zhx_guest_school.20 days = 6935 }",
        "        country_event = { id = zhx_guest_school.30 days = 7300 }",
        "    }",
        "}",
        "",
        "zhx_guest_school_pay_contract_cost = {",
        "    add_dip_power = -75",
        "    add_years_of_income = -0.5",
        "}",
        "",
        "zhx_guest_school_mark_pending_source = {",
        "    zhx_guest_school_clear_source_link = yes",
        "    event_target:zhx_guest_school_pending_source = {",
        "        add_opinion = {",
        "            who = ROOT",
        "            modifier = zhx_opinion_guest_school_source_link",
        "            years = 21",
        "        }",
        "    }",
        "}",
    ]

    for code, (_, _, modifier) in SCHOOLS.items():
        parts.extend(
            [
                "",
                f"zhx_guest_school_begin_{code} = {{",
                "    if = {",
                f"        limit = {{ zhx_guest_school_pending_{code}_is_valid = yes }}",
                "        zhx_guest_school_pay_contract_cost = yes",
                "        zhx_guest_school_mark_pending_source = yes",
                "        set_country_flag = zhx_guest_school_contract_active",
                f"        set_country_flag = zhx_guest_school_contract_{code}",
                f"        add_country_modifier = {{ name = {modifier} duration = 7300 }}",
                "        add_country_modifier = {",
                "            name = zhx_guest_school_adjustment",
                "            duration = 1825",
                "        }",
                "        zhx_guest_school_toggle_generation_and_schedule = yes",
                "        zhx_guest_school_clear_pending = yes",
                "        zhx_refresh_academy_country_effects = yes",
                "    }",
                "}",
                "",
                f"zhx_guest_school_pick_{code}_renewal_source = {{",
                "    if = {",
                "        limit = {",
                "            any_country = {",
                f"                zhx_guest_school_source_is_eligible_{code} = yes",
                "                has_opinion_modifier = {",
                "                    who = ROOT",
                "                    modifier = zhx_opinion_guest_school_source_link",
                "                }",
                "            }",
                "        }",
                "        random_country = {",
                "            limit = {",
                f"                zhx_guest_school_source_is_eligible_{code} = yes",
                "                has_opinion_modifier = {",
                "                    who = ROOT",
                "                    modifier = zhx_opinion_guest_school_source_link",
                "                }",
                "            }",
                "            save_event_target_as = zhx_guest_school_renewal_source",
                "        }",
                "    }",
                "    else = {",
                "        random_country = {",
                f"            limit = {{ zhx_guest_school_source_is_eligible_{code} = yes }}",
                "            save_event_target_as = zhx_guest_school_renewal_source",
                "        }",
                "    }",
                "}",
                "",
                f"zhx_guest_school_renew_{code} = {{",
                "    if = {",
                f"        limit = {{ zhx_guest_school_has_valid_{code}_renewal_source = yes }}",
                f"        zhx_guest_school_pick_{code}_renewal_source = yes",
                "        zhx_guest_school_pay_contract_cost = yes",
                "        zhx_guest_school_clear_source_link = yes",
                "        event_target:zhx_guest_school_renewal_source = {",
                "            add_opinion = {",
                "                who = ROOT",
                "                modifier = zhx_opinion_guest_school_source_link",
                "                years = 21",
                "            }",
                "        }",
                "        clr_country_flag = zhx_guest_school_contract_active",
                "        set_country_flag = zhx_guest_school_contract_active",
                f"        remove_country_modifier = {modifier}",
                f"        add_country_modifier = {{ name = {modifier} duration = 7300 }}",
                "        remove_country_modifier = zhx_guest_school_adjustment",
                "        zhx_guest_school_toggle_generation_and_schedule = yes",
                "        zhx_refresh_academy_country_effects = yes",
                "    }",
                "}",
            ]
        )

    parts.extend(
        [
            "",
            "zhx_guest_school_renew_current = {",
            *sum(
                (
                    [
                        "    if = {" if index == 0 else "    else_if = {",
                        f"        limit = {{ has_country_flag = zhx_guest_school_contract_{code} }}",
                        f"        zhx_guest_school_renew_{code} = yes",
                        "    }",
                    ]
                    for index, code in enumerate(SCHOOLS)
                ),
                [],
            ),
            "}",
            "",
            "zhx_guest_school_honour_source = {",
            "    every_country = {",
            "        limit = {",
            "            has_opinion_modifier = {",
            "                who = ROOT",
            "                modifier = zhx_opinion_guest_school_source_link",
            "            }",
            "        }",
            "        add_opinion = { who = ROOT modifier = zhx_opinion_guest_school_honoured }",
            "    }",
            "}",
            "",
            "zhx_guest_school_close_normally = {",
            "    zhx_guest_school_honour_source = yes",
            "    zhx_guest_school_clear_contract_state = yes",
            "    zhx_refresh_academy_country_effects = yes",
            "    zhx_doctrine_reform_reconcile = yes",
            "}",
            "",
        ]
    )

    # International reaction is generated school-by-school so an invited or
    # old-momentum display mirror can never masquerade as a formal doctrine.
    for code, (_, doctrine, _) in SCHOOLS.items():
        parts.extend(
            [
                f"zhx_guest_school_expel_reaction_{code} = {{",
                "    every_country = {",
                "        limit = {",
                "            exists = yes",
                "            NOT = { tag = ROOT }",
                "            zhx_is_lijiao_country = yes",
                f"            has_country_flag = {doctrine}",
                "            NOT = {",
                "                has_opinion_modifier = {",
                "                    who = ROOT",
                "                    modifier = zhx_opinion_guest_school_source_link",
                "                }",
                "            }",
                "        }",
                "        add_opinion = {",
                "            who = ROOT",
                "            modifier = zhx_opinion_guest_school_expelled_school",
                "        }",
                "    }",
                "}",
                "",
            ]
        )

    parts.extend(
        [
            "zhx_guest_school_expel_current = {",
            "    if = {",
            "        limit = { zhx_guest_school_has_active_contract = yes }",
            *sum(
                (
                    [
                        "        if = {" if index == 0 else "        else_if = {",
                        f"            limit = {{ has_country_flag = zhx_guest_school_contract_{code} }}",
                        f"            zhx_guest_school_expel_reaction_{code} = yes",
                        "        }",
                    ]
                    for index, code in enumerate(SCHOOLS)
                ),
                [],
            ),
            "        every_country = {",
            "            limit = {",
            "                has_opinion_modifier = {",
            "                    who = ROOT",
            "                    modifier = zhx_opinion_guest_school_source_link",
            "                }",
            "            }",
            "            add_opinion = {",
            "                who = ROOT",
            "                modifier = zhx_opinion_guest_school_expelled_source",
            "            }",
            "        }",
            "        add_stability = -1",
            "        add_country_modifier = {",
            "            name = zhx_guest_school_dishonour",
            "            duration = 3650",
            "        }",
            "        zhx_guest_school_clear_contract_state = yes",
            "        zhx_refresh_academy_country_effects = yes",
            "        zhx_doctrine_reform_reconcile = yes",
            "    }",
            "}",
            "",
            "zhx_guest_school_cache_current_source = {",
            "    random_country = {",
            "        limit = {",
            "            has_opinion_modifier = {",
            "                who = ROOT",
            "                modifier = zhx_opinion_guest_school_source_link",
            "            }",
            "        }",
            "        save_event_target_as = zhx_guest_school_current_source",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(parts)


def render_modifiers() -> str:
    return """# Generated by tools/build_zhx_guest_school.py. Do not hand-edit.

zhx_guest_school_adjustment = {
    global_unrest = 1
    stability_cost_modifier = 0.15
    advisor_cost = 0.10
}

zhx_guest_school_dishonour = {
    diplomatic_reputation = -1
    stability_cost_modifier = 0.10
}
"""


def render_opinions() -> str:
    return """# Generated by tools/build_zhx_guest_school.py. Do not hand-edit.

# A deliberately tiny non-decaying pair marker: source country's opinion of
# the inviter. It is safe for simultaneous contracts and survives save/load.
zhx_opinion_guest_school_source_link = {
    opinion = 1
    yearly_decay = 0
}

zhx_opinion_guest_school_honoured = {
    opinion = 25
    yearly_decay = 2.5
}

zhx_opinion_guest_school_expelled_source = {
    opinion = -100
    yearly_decay = 10
}

zhx_opinion_guest_school_expelled_school = {
    opinion = -25
    yearly_decay = 2.5
}
"""


def render_decisions() -> str:
    return """# Generated by tools/build_zhx_guest_school.py. Do not hand-edit.

country_decisions = {
    zhx_expel_guest_school = {
        major = no

        potential = {
            ai = no
            zhx_guest_school_has_active_contract = yes
        }

        allow = { always = yes }

        effect = {
            country_event = { id = zhx_guest_school.50 }
        }

        ai_will_do = { factor = 0 }
    }
}
"""


def render_events() -> str:
    parts = [
        "# Generated by tools/build_zhx_guest_school.py. Do not hand-edit.",
        "namespace = zhx_guest_school",
        "",
    ]
    for index, (code, _) in enumerate(SCHOOLS.items(), start=10):
        parts.extend(
            [
                "country_event = {",
                f"    id = zhx_guest_school.{index}",
                f"    title = zhx_guest_school.confirm_{code}.t",
                f"    desc = zhx_guest_school.confirm_{code}.d",
                "    picture = DIPLOMACY_eventPicture",
                "    is_triggered_only = yes",
                "",
                "    option = {",
                f"        name = zhx_guest_school.confirm_{code}.a",
                "        trigger = {",
                "            custom_trigger_tooltip = {",
                "                tooltip = zhx_guest_school_confirmation_requirements_tt",
                f"                zhx_guest_school_pending_{code}_is_valid = yes",
                "            }",
                "        }",
                "        custom_tooltip = zhx_guest_school_contract_cost_tt",
                f"        hidden_effect = {{ zhx_guest_school_begin_{code} = yes }}",
                "        ai_chance = { factor = 1 }",
                "    }",
                "    option = {",
                "        name = zhx_guest_school.cancel",
                "        hidden_effect = { zhx_guest_school_clear_pending = yes }",
                "        ai_chance = { factor = 0 }",
                "    }",
                "}",
                "",
            ]
        )

    # Hidden A/B callbacks.  Their trigger is deliberately inside immediate:
    # stale callbacks exit harmlessly instead of leaving a blocked event.
    for event_id, generation in ((20, "a"), (21, "b")):
        parts.extend(
            [
                "country_event = {",
                f"    id = zhx_guest_school.{event_id}",
                "    title = OK",
                "    desc = OK",
                "    picture = DIPLOMACY_eventPicture",
                "    hidden = yes",
                "    is_triggered_only = yes",
                "    immediate = {",
                "        if = {",
                "            limit = {",
                "                ai = no",
                "                zhx_guest_school_has_active_contract = yes",
                f"                has_country_flag = zhx_guest_school_generation_{generation}",
                "            }",
                "            country_event = { id = zhx_guest_school.22 }",
                "        }",
                "    }",
                "    option = { name = OK }",
                "}",
                "",
            ]
        )

    parts.extend(
        [
            "country_event = {",
            "    id = zhx_guest_school.22",
            "    title = zhx_guest_school.reminder.t",
            "    desc = {",
            "        trigger = {",
            "            any_country = { has_opinion_modifier = { who = ROOT modifier = zhx_opinion_guest_school_source_link } }",
            "        }",
            "        desc = zhx_guest_school.reminder.d",
            "    }",
            "    desc = {",
            "        trigger = {",
            "            NOT = { any_country = { has_opinion_modifier = { who = ROOT modifier = zhx_opinion_guest_school_source_link } } }",
            "        }",
            "        desc = zhx_guest_school.reminder.no_source.d",
            "    }",
            "    picture = DIPLOMACY_eventPicture",
            "    is_triggered_only = yes",
            "    trigger = { zhx_guest_school_has_active_contract = yes }",
            "    immediate = { zhx_guest_school_cache_current_source = yes }",
            "    option = { name = zhx_guest_school.reminder.a }",
            "}",
            "",
        ]
    )

    for event_id, generation in ((30, "a"), (31, "b")):
        parts.extend(
            [
                "country_event = {",
                f"    id = zhx_guest_school.{event_id}",
                "    title = OK",
                "    desc = OK",
                "    picture = DIPLOMACY_eventPicture",
                "    hidden = yes",
                "    is_triggered_only = yes",
                "    immediate = {",
                "        if = {",
                "            limit = {",
                "                zhx_guest_school_has_active_contract = yes",
                f"                has_country_flag = zhx_guest_school_generation_{generation}",
                "            }",
                "            if = {",
                "                limit = { ai = no }",
                "                country_event = { id = zhx_guest_school.40 }",
                "            }",
                "            else = {",
                "                if = {",
                "                    limit = { zhx_guest_school_ai_may_renew = yes }",
                "                    zhx_guest_school_renew_current = yes",
                "                }",
                "                else = { zhx_guest_school_close_normally = yes }",
                "            }",
                "        }",
                "    }",
                "    option = { name = OK }",
                "}",
                "",
            ]
        )

    parts.extend(
        [
            "country_event = {",
            "    id = zhx_guest_school.40",
            "    title = zhx_guest_school.expiry.t",
            "    desc = {",
            "        trigger = {",
            "            any_country = { has_opinion_modifier = { who = ROOT modifier = zhx_opinion_guest_school_source_link } }",
            "        }",
            "        desc = zhx_guest_school.expiry.d",
            "    }",
            "    desc = {",
            "        trigger = {",
            "            NOT = { any_country = { has_opinion_modifier = { who = ROOT modifier = zhx_opinion_guest_school_source_link } } }",
            "        }",
            "        desc = zhx_guest_school.expiry.no_source.d",
            "    }",
            "    picture = DIPLOMACY_eventPicture",
            "    is_triggered_only = yes",
            "    trigger = { zhx_guest_school_has_active_contract = yes }",
            "    immediate = { zhx_guest_school_cache_current_source = yes }",
            "    option = {",
            "        name = zhx_guest_school.expiry.renew",
            "        trigger = {",
            "            custom_trigger_tooltip = {",
            "                tooltip = zhx_guest_school_renew_requirements_tt",
            "                zhx_guest_school_has_valid_renewal_source = yes",
            "            }",
            "        }",
            "        custom_tooltip = zhx_guest_school_renew_cost_tt",
            "        hidden_effect = { zhx_guest_school_renew_current = yes }",
            "        ai_chance = { factor = 1 }",
            "    }",
            "    option = {",
            "        name = zhx_guest_school.expiry.send_home",
            "        custom_tooltip = zhx_guest_school_send_home_tt",
            "        hidden_effect = { zhx_guest_school_close_normally = yes }",
            "        ai_chance = { factor = 0 }",
            "    }",
            "}",
            "",
            "country_event = {",
            "    id = zhx_guest_school.50",
            "    title = zhx_guest_school.expel.t",
            "    desc = {",
            "        trigger = {",
            "            any_country = { has_opinion_modifier = { who = ROOT modifier = zhx_opinion_guest_school_source_link } }",
            "        }",
            "        desc = zhx_guest_school.expel.d",
            "    }",
            "    desc = {",
            "        trigger = {",
            "            NOT = { any_country = { has_opinion_modifier = { who = ROOT modifier = zhx_opinion_guest_school_source_link } } }",
            "        }",
            "        desc = zhx_guest_school.expel.no_source.d",
            "    }",
            "    picture = DIPLOMACY_eventPicture",
            "    is_triggered_only = yes",
            "    trigger = { zhx_guest_school_has_active_contract = yes }",
            "    immediate = { zhx_guest_school_cache_current_source = yes }",
            "    option = {",
            "        name = zhx_guest_school.expel.a",
            "        custom_tooltip = zhx_guest_school_expel_cost_tt",
            "        hidden_effect = { zhx_guest_school_expel_current = yes }",
            "        ai_chance = { factor = 0 }",
            "    }",
            "    option = {",
            "        name = zhx_guest_school.cancel",
            "        ai_chance = { factor = 1 }",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(parts)


def render_all() -> dict[Path, str]:
    return {
        TARGETS["triggers"]: render_triggers(),
        TARGETS["effects"]: render_effects(),
        TARGETS["modifiers"]: render_modifiers(),
        TARGETS["opinions"]: render_opinions(),
        TARGETS["decisions"]: render_decisions(),
        TARGETS["events"]: render_events(),
    }


def run(check: bool) -> None:
    outputs = render_all()
    stale: list[str] = []
    for path, text in outputs.items():
        text = text.rstrip() + "\n"
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    if stale:
        raise ValueError("stale guest-school outputs: " + ", ".join(stale))
    print(
        f"{'checked' if check else 'built'} guest-school contract: "
        f"schools={len(SCHOOLS)}, outputs={len(outputs)}, term=7300 days"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    run(args.check)


if __name__ == "__main__":
    main()
