#!/usr/bin/env python3
"""Live, read-only score text for the immediate Qinwang invitation.

Uses customizable localization + variable_arithmetic_trigger, not monthly caches
or mutations while hovering. All weights and rounding come from the AI generator.
"""
from pathlib import Path
import argparse
from build_zhx_qinwang_score import MOD, RULES, numeric, localize_variables


def component(name):
    return numeric('zhx_qn', 'THIS') + [f'set_variable = {{ which = zhx_qn_ui_value which = zhx_qn_{name} }}']


def total(kind, offset='$offset$'):
    # Only native numeric exports: scripted triggers cannot be exported to numbers.
    lines=numeric('zhx_qn','THIS')
    lines += [f'set_variable = {{ which = zhx_qn_ui_value value = {offset} }}']
    for name in ('opinion','trust'):
        if kind in ('positive','negative'):
            lines += [f'set_variable = {{ which = zhx_qn_abs which = zhx_qn_{name} }}',
                      'multiply_variable = { which = zhx_qn_abs which = zhx_qn_abs }',
                      'sqrt_variable = { which = zhx_qn_abs value = 0 }']
            operation='change_variable' if kind=='positive' else 'subtract_variable'
            lines += [f'{operation} = {{ which = zhx_qn_abs which = zhx_qn_{name} }}',
                      'divide_variable = { which = zhx_qn_abs value = 2 }',
                      'change_variable = { which = zhx_qn_ui_value which = zhx_qn_abs }']
        else: lines += [f'change_variable = {{ which = zhx_qn_ui_value which = zhx_qn_{name} }}']
    if kind=='net':
        lines += ['multiply_variable = { which = zhx_qn_ui_value value = $sign$ }']
    return lines


def cases(kind):
    from itertools import product
    rules=[r for r in RULES if r[2] and not (kind=='positive' and r[1]<0) and not (kind=='negative' and r[1]>0)]
    groups={}
    for flags in product((False,True),repeat=len(rules)):
        selected=dict(zip((r[0] for r in rules),flags))
        if any(selected.get(a) and selected.get(b) for a,b in [('manpower_low','manpower_mid'),('loans_low','loans_high')]):continue
        offset=sum(r[1] for r,active in zip(rules,flags) if active)
        if kind!='positive':offset-=20
        if kind=='negative':offset=-offset
        condition=' '.join(f'zhx_qn_score_{r[0]} = {"yes" if active else "no"}' for r,active in zip(rules,flags))
        groups.setdefault(offset,[]).append(condition)
    return groups


def generated():
    triggers=['# Generated by tools/build_zhx_qinwang_tooltip.py; recipient scope.']
    defined=[];loc={'zhx_qn_ui_empty':'', 'zhx_qn_ui_minus':'-', 'zhx_qn_ui_plus':'+',
        'zhx_qn_ui_accept':'§G他们愿意应召勤王。§!',
        'zhx_qn_ui_reject':'§R他们不愿意应召勤王。§!',
        'zhx_qn_ui_player':'§Y对方由玩家控制，可以接受或拒绝。§!',
        'zhx_qn_ui_blocked':'§R目前无法邀请勤王。§!',
        'zhx_qn_ui_ready':'§G符合邀请条件。§!',
        'zhx_qn_ui_threshold':'赞成须比反对至少多§Y1§!。',
        'zhx_qn_ui_threshold_player':'以下意愿仅供参考，不限制玩家答复。',
    }
    def vat(name,lines,check):
        triggers.append(name+' = {\n    variable_arithmetic_trigger = {\n        '+'\n        '.join(localize_variables(lines)+[check])+'\n    }\n}')
    def text(name,choices):
        defined.append('defined_text = {\n    name = '+name+'\n'+''.join('    text = { localisation_key = '+key+' trigger = { '+condition+' } }\n' for key,condition in choices)+'}')
    for kind in ('positive','negative','net','signed'):
        calc=total(kind)+[
            'divide_variable = { which = zhx_qn_ui_value value = $divisor$ }',
            'round_variable = { which = zhx_qn_ui_value value = -1 }',
            'modulo_variable = { which = zhx_qn_ui_value value = $modulus$ }',
        ]
        vat('zhx_qn_calc_'+kind,calc,'check_variable = { which = zhx_qn_ui_value value = $threshold$ }')
        branches=[]
        for offset,conditions in cases(kind).items():
            choice='OR = { '+' '.join('AND = { '+c+' }' for c in conditions)+' }'
            sign=' sign = $sign$' if kind=='net' else ''
            branches.append(f'AND = {{ {choice} zhx_qn_calc_{kind} = {{ offset = {offset} divisor = $divisor$ modulus = $modulus$ threshold = $threshold${sign} }} }}')
        triggers.append('zhx_qn_sum_'+kind+('_branch' if kind=='net' else '')+' = { OR = {\n    '+'\n    '.join(branches)+'\n} }')
        if kind=='net':
            triggers.append('zhx_qn_sum_net = { OR = { AND = { zhx_qn_ai_positive = yes zhx_qn_sum_net_branch = { sign = 1 divisor = $divisor$ modulus = $modulus$ threshold = $threshold$ } } AND = { zhx_qn_ai_positive = no zhx_qn_sum_net_branch = { sign = -1 divisor = $divisor$ modulus = $modulus$ threshold = $threshold$ } } } }')
    for name in ('opinion','trust'):
        vat('zhx_qn_ui_'+name+'_nonnegative',component(name),'check_variable = { which = zhx_qn_ui_value value = 0 }')
        vat('zhx_qn_ui_'+name+'_at_least',component(name),'check_variable = { which = zhx_qn_ui_value value = $value$ }')
    text('GetQinwangResponse', [('zhx_qn_ui_player','ai = no'),('zhx_qn_ui_accept','zhx_qn_ai_positive = yes'),('zhx_qn_ui_reject','always = yes')])
    text('GetQinwangAvailability',[('zhx_qn_ui_ready','zhx_qn_can_send = yes'),('zhx_qn_ui_blocked','always = yes')])
    text('GetQinwangThreshold',[('zhx_qn_ui_threshold_player','ai = no'),('zhx_qn_ui_threshold','always = yes')])
    for kind,places in [('positive',(10,1)),('negative',(1000,100,10,1)),('net',(1000,100,10,1))]:
        for place in places:
            prefix=f'zhx_qn_ui_{kind}_{place}'
            triggers.append(f'{prefix}_shown = {{ zhx_qn_sum_{kind} = {{ divisor = 1 modulus = 10000 threshold = {place} }} }}')
            triggers.append(f'{prefix}_digit = {{ zhx_qn_sum_{kind} = {{ divisor = {place} modulus = 10 threshold = $value$ }} }}')
            choices=[] if place==1 else [('zhx_qn_ui_empty',f'NOT = {{ {prefix}_shown = yes }}')]
            for digit in range(9,-1,-1):
                loc[f'zhx_qn_ui_digit_{digit}']=str(digit)
                choices.append((f'zhx_qn_ui_digit_{digit}',f'{prefix}_digit = {{ value = {digit} }}'))
            text(f'GetQinwang{kind.title()}{place}',choices)
    # Exact zero has no misleading minus sign.
    text('GetQinwangNetPrefix',[('zhx_qn_ui_empty','NOT = { zhx_qn_ui_net_1_shown = yes }'),('zhx_qn_ui_plus','zhx_qn_ai_positive = yes'),('zhx_qn_ui_minus','always = yes')])
    for key,weight,condition,label in RULES:
        keyloc='zhx_qn_ui_line_'+key
        loc[keyloc]='\\n'+label+'：§'+('G+' if weight>0 else 'R')+str(weight)+'§!'
        text('GetQinwangLine'+key.title().replace('_',''),[(keyloc,'always = yes' if not condition else f'zhx_qn_score_{key} = yes'),('zhx_qn_ui_empty','always = yes')])
    for name,max_value,label in [('opinion',40,'诸侯对天子的好感'),('trust',25,'诸侯对天子的信任')]:
        for positive in (True,False):
            choices=[]
            for amount in range(max_value,0,-1):
                value=amount if positive else -amount
                key=f'zhx_qn_ui_line_{name}_'+('p' if positive else 'n')+str(amount)
                loc[key]='\\n'+label+'：§'+('G+' if positive else 'R')+str(value)+'§!'
                cond=f'zhx_qn_ui_{name}_at_least = {{ value = {amount} }}' if positive else f'NOT = {{ zhx_qn_ui_{name}_at_least = {{ value = {value+1} }} }}'
                choices.append((key,cond))
            choices.append(('zhx_qn_ui_empty','always = yes'))
            text('GetQinwang'+name.title()+('Positive' if positive else 'Negative'),choices)
    def number(kind,places):return ''.join(f'[From.GetQinwang{kind.title()}{place}]' for place in places)
    tooltip='[From.GetQinwangResponse]\\n赞成：§G'+number('positive',(10,1))+'§!\\n反对：§R-'+number('negative',(1000,100,10,1))+'§!\\n\\n[From.GetQinwangThreshold]当前净意愿：§Y[From.GetQinwangNetPrefix]'+number('net',(1000,100,10,1))+'§!。'
    tooltip+='\\n[From.GetQinwangLineDefensive][From.GetQinwangOpinionPositive][From.GetQinwangTrustPositive]'
    tooltip+='\\n[From.GetQinwangLineBase][From.GetQinwangOpinionNegative][From.GetQinwangTrustNegative]'
    for key,weight,condition,label in RULES:
        if key in ('base','defensive'):continue
        tooltip+='[From.GetQinwangLine'+key.title().replace('_','')+']'
    tooltip+='\\n\\n[From.GetQinwangAvailability]\\n实际参战：兑现§Y25人情§!，诸侯获得§G10主动盟功§!。'
    # The native tooltip processes FROM before calling the text functions. Keep
    # the composed template on the action itself (no nested localisation reliance).
    source_path=MOD/'localisation_source/032_zhx_qinwang_readable_utf8.txt'
    import re
    source=source_path.read_text()
    replacements={
        'zhx_invite_qinwang_tooltip':tooltip,
        'zhx_qn_positive_tt':'对方的赞成分必须大于反对分。',
        'zhx_qn_single_war_tt':'天子须仅参与一场战争，并担任本方领袖。',
        'zhx_qn_peace_tt':'诸侯须独立且处于和平。',
        'zhx_qn_favors_tt':'天子对该国的人情不足25。',
        'zhx_qn_once_tt':'本场已邀请该国，或尚有未处理的旧邀请。',
        'zhx_qn_campaign_tt':'原勤王战争记录尚未结束，暂不能邀请。',
    }
    for key,value in replacements.items():
        source,n=re.subn(r'^ '+re.escape(key)+r':0 ".*"$',lambda _:f' {key}:0 "{value}"',source,flags=re.M)
        assert n==1,key
    return {
        'localisation_source/032_zhx_qinwang_readable_utf8.txt':source,
        'common/scripted_triggers/zhx_qinwang_tooltip_triggers.txt':'\n'.join(triggers)+'\n',
        'customizable_localization/zhx_qinwang_tooltip.txt':'\n'.join(defined)+'\n',
        'localisation_source/034_zhx_qinwang_tooltip_readable_utf8.txt':'l_english:\n'+''.join(f' {k}:0 "{v}"\n' for k,v in loc.items()),
    },tooltip


def main():
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
    files,_=generated()
    for rel,content in files.items():
        path=MOD/rel
        if a.check:assert path.read_text()==content, f'Stale generated file: {path}'
        else:path.write_text(content)
    print('Qinwang single-row tooltip: '+('verified' if a.check else 'generated'))
if __name__=='__main__':main()
