#!/usr/bin/env python3
"""Build narrative events, localisation and DDS derivatives from reviewed art/lore."""
from pathlib import Path
import argparse
import io
import json
import re
from PIL import Image
from encode_eu4_chinese_localisation import to_escaped_bytes, escaped_bytes_to_utf8, from_escaped_bytes

ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "guangdong_independent_practice"
MANIFEST = ROOT / "planning/opening_backgrounds/lingnan_opening_manifest.json"
GONGYI_MANIFEST = ROOT / "planning/opening_backgrounds/gongyi_opening_manifest.json"
CHU_MANIFEST = ROOT / "planning/opening_backgrounds/chu_opening_manifest.json"


def load_manifest():
    data = json.loads(MANIFEST.read_text())
    for manifest in (GONGYI_MANIFEST, CHU_MANIFEST):
        batch = json.loads(manifest.read_text())
        assert batch['start_date'] == data['start_date']
        assert batch['texture_size'] == data['texture_size']
        data['countries'].extend(batch['countries'])
    rows = data['countries']
    for key in ('tag', 'event_id'):
        assert len({r[key] for r in rows}) == len(rows), f'duplicate {key}'
    return data


def render_ruler(row, start_date):
    """Replace only our marked opening ruler; preserve existing country setup."""
    path = MOD / 'history/countries' / row['history_file']
    original = from_escaped_bytes(path.read_bytes())
    group = row.get('history_group', 'GONGYI')
    assert group in ('GONGYI', 'CHU')
    begin, end = f'# ZHX_{group}_OPENING_RULER_BEGIN', f'# ZHX_{group}_OPENING_RULER_END'
    assert original.count(begin) == original.count(end) <= 1
    base = re.sub(re.escape(begin) + r'.*?' + re.escape(end) + r'\n?', '', original, flags=re.S)
    assert not re.search(r'\bmonarch\s*=', base), f'existing ruler requires reconciliation: {path}'
    r = row['ruler']
    lines = [begin, f'{start_date} = {{', '    monarch = {',
             f'        name = "{r["name"]}"', f'        dynasty = "{r["dynasty"]}"',
             f'        birth_date = {r["birth_date"]}']
    lines += [f'        {stat} = {r[stat]}' for stat in ('adm', 'dip', 'mil')]
    if r['female']:
        lines.append('        female = yes')
    lines += [f'        culture = {row["culture"]}', '        religion = confucianism',
              '    }']
    for kind in ('heir', 'queen'):
        if kind not in row:
            continue
        character = row[kind]
        lines += [f'    {kind} = {{', f'        name = "{character["name"]}"',
                  f'        dynasty = "{character["dynasty"]}"',
                  f'        birth_date = {character["birth_date"]}',
                  '        death_date = 1821.1.1']
        lines += [f'        {stat} = {character[stat]}' for stat in ('adm', 'dip', 'mil')]
        if kind == 'heir':
            lines.append(f'        claim = {character.get("claim", 70)}')
        if character.get('female'):
            lines.append('        female = yes')
        if 'country_of_origin' in character:
            lines.append(f'        country_of_origin = {character["country_of_origin"]}')
        lines += [f'        culture = {row["culture"]}', '        religion = confucianism', '    }']
    lines += ['}', end]
    text = base.rstrip() + '\n\n' + '\n'.join(lines) + '\n'
    blob = to_escaped_bytes(text)
    assert from_escaped_bytes(blob) == text
    return path, blob


def render():
    data = load_manifest()
    rows = data["countries"]
    outputs = {}
    events = ["# Generated by tools/build_lingnan_opening_events.py\nnamespace = zhx_opening\n"]
    gfx = ["spriteTypes = {\n"]
    loc = ["l_english:\n"]
    for i, row in enumerate(rows):
        if 'ruler' in row:
            path, blob = render_ruler(row, data['start_date'])
            outputs[path] = blob
        tag, eid = row["tag"], row["event_id"]
        sprite = f"zhx_opening_{tag.lower()}_eventPicture"
        option_tooltip = f"        custom_tooltip = {row['button_tooltip']}\n" if row.get("button_tooltip") else ""
        events.append(f'''
country_event = {{
    id = {eid}
    title = {eid}.t
    desc = {eid}.d
    picture = {sprite}
    is_triggered_only = yes

    trigger = {{
        ai = no
        tag = {tag}
        zhx_should_show_opening_background = yes
    }}

    immediate = {{
        set_country_flag = zhx_opening_background_pending
        set_country_flag = zhx_opening_background_seen
    }}

    option = {{
        name = {eid}.a
{option_tooltip}        hidden_effect = {{ zhx_finish_opening_introduction = yes }}
    }}
}}
''')
        for suffix, value in (("t", row["title"]), ("d", row["body"]), ("a", row["button"])):
            assert '"' not in value and "\\" not in value
            value = value.replace("\n", "\\n")
            loc.append(f' {eid}.{suffix}:0 "{value}"\n')
        texture = f"gfx/event_pictures/zhx_opening/{sprite}.dds"
        gfx.append(f'''    spriteType = {{
        name = "{sprite}"
        texturefile = "{texture}"
        alwaystransparent = yes
    }}
''')
        with Image.open(ROOT / row["source_image"]) as source:
            # Production crop only: original art is kept byte-for-byte.
            width, height = source.size
            crop_height = round(width * data["texture_size"][1] / data["texture_size"][0])
            top = row["crop_top"]
            assert 0 <= top <= height - crop_height, tag
            result = source.crop((0, top, width, top + crop_height)).resize(
                data["texture_size"], Image.Resampling.LANCZOS).convert("RGBA")
            result.putalpha(255)
            buffer = io.BytesIO()
            result.save(buffer, format="DDS")
            outputs[MOD / texture] = buffer.getvalue()
    gfx.append("}\n")
    tags = "\n".join(f'        tag = {r["tag"]}' for r in rows)
    triggers = f'''# Generated. Fixed 1444 historical countries, independent of faith or membership.
zhx_has_opening_background = {{
    OR = {{
{tags}
    }}
}}
'''
    effects = """# Generated. The native on_startup event list owns first display.
# Clicking the story opens the reusable directory synchronously.
zhx_finish_opening_introduction = {
    clr_country_flag = zhx_opening_background_pending
    zhx_open_mod_guide = yes
}
"""
    triggers += """
# Eligibility is independent of world initialization. Keep it separate from
# the event's pending flag so menu/story exclusion works in either hook order.
zhx_should_show_opening_background = {
    zhx_has_opening_background = yes
    start_date = 1444.11.11
    NOT = { start_date = 1444.11.12 }
    NOT = { is_date = 1444.11.14 }
    NOT = { has_country_flag = zhx_opening_background_seen }
    NOT = { has_country_flag = zhx_startup_overview_seen }
}
"""
    startup = "# Generated. Native startup events, no timer or hidden dispatcher.\non_startup = {\n    events = {\n" + "".join("        " + row["event_id"] + "\n" for row in rows) + "        zhx_guide.0\n    }\n}\n"
    for relative, content in {
        "events/zhx_opening_background_events.txt": "".join(events),
        "common/on_actions/zhx_opening_background_on_actions.txt": startup,
        "common/scripted_triggers/zhx_opening_background_triggers.txt": triggers,
        "common/scripted_effects/zhx_opening_background_effects.txt": effects,
        "interface/zhx_opening_background_eventpictures.gfx": "".join(gfx),
        "localisation_source/026_zhx_opening_backgrounds_readable_utf8.txt": "".join(loc),
    }.items():
        outputs[MOD / relative] = content.encode("utf-8")
    outputs[MOD / "localisation/replace/026_zhx_opening_backgrounds_l_english.yml"] = escaped_bytes_to_utf8(to_escaped_bytes("".join(loc)))
    return outputs


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = render()
    for path, content in outputs.items():
        if args.check:
            if not path.is_file() or path.read_bytes() != content:
                raise ValueError(f"missing or stale output: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    count = len(load_manifest()['countries'])
    print(f'{"Checked" if args.check else "Built"} {len(outputs)} outputs: {count} native startup stories, {count} DDS, authored characters, Chinese localisation and routing.')


if __name__ == "__main__":
    main()
