#!/usr/bin/env python3
"""Build the independent state machine for changing a ZHX main doctrine.

This builder deliberately owns only the reform process.  The six authoritative
``zhx_doctrine_*`` flags and ``zhx_doctrine_practice`` variable are updated at
the two moments when the main school genuinely changes, but native-school
mirrors, invited-scholar cleanup, academy refreshes, and Tianxia debate state
remain external integrations exposed through explicit hook flags/triggers.

Fresh-campaign/current-version behaviour is the compatibility boundary.  Every
scheduled event is guarded by durable country flags, and cleanup is idempotent.
"""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "guangdong_independent_practice"

SCHOOLS = {
    "ru": {
        "name": "儒家",
        "flag": "zhx_doctrine_ru",
        "invited": "zhx_ru_invited_scholar_modifier",
        "academies": ("zhx_academy_chongli", "zhx_academy_minglun"),
        "summary": "以礼乐、名分与教化整饬国家，使上下各安其位。",
    },
    "fa": {
        "name": "法家",
        "flag": "zhx_doctrine_fa",
        "invited": "zhx_fa_invited_scholar_modifier",
        "academies": ("zhx_academy_yifa", "zhx_academy_xunming"),
        "summary": "以法、术、势明赏罚而一政令，使国家强干而有制。",
    },
    "mo": {
        "name": "墨家",
        "flag": "zhx_doctrine_mo",
        "invited": "zhx_mo_invited_scholar_modifier",
        "academies": ("zhx_academy_jianai", "zhx_academy_shangtong"),
        "summary": "尚贤、兼爱、非攻并重实用，使民力用于守御与公利。",
    },
    "dao": {
        "name": "道家",
        "flag": "zhx_doctrine_dao",
        "invited": "zhx_dao_invited_scholar_modifier",
        "academies": ("zhx_academy_xuantong", "zhx_academy_baopu"),
        "summary": "崇尚清静、因循与无为，节制扰民政令并休养生息。",
    },
    "bing": {
        "name": "兵家",
        "flag": "zhx_doctrine_bing",
        "invited": "zhx_bing_invited_scholar_modifier",
        "academies": ("zhx_academy_miaosuan", "zhx_academy_zhisheng"),
        "summary": "讲求庙算、形势与治军，使国家常备不懈而能制胜。",
    },
    "zongheng": {
        "name": "纵横家",
        "flag": "zhx_doctrine_zongheng",
        "invited": "zhx_zongheng_invited_scholar_modifier",
        "academies": ("zhx_academy_baihe", "zhx_academy_lianheng"),
        "summary": "审天下之势而合纵连横，以盟约、声名与权变制衡诸侯。",
    },
}

OUTPUTS = {
    "triggers": MOD / "common/scripted_triggers/zhx_doctrine_reform_triggers.txt",
    "effects": MOD / "common/scripted_effects/zhx_doctrine_reform_effects.txt",
    "modifiers": MOD / "common/event_modifiers/zhx_doctrine_reform_modifiers.txt",
    "secondary_modifiers": MOD / "common/static_modifiers/zhx_doctrine_reform_secondary_modifiers.txt",
    "opinions": MOD / "common/opinion_modifiers/zhx_doctrine_reform_opinions.txt",
    "decisions": MOD / "decisions/zhx_doctrine_reform_decisions.txt",
    "events": MOD / "events/zhx_doctrine_reform_events.txt",
    "localisation": MOD / "localisation_source/zhx_doctrine_reform_readable_utf8.txt",
}

GUEST_CONTRACT_ACTIVE_FLAG = "zhx_guest_school_contract_active"
# ``had_country_flag days = N`` becomes true on day N.  A one-day safety
# margin keeps the 1825-day cultivation callback away from the 7300-day guest
# expiry callback, whose same-day ordering is not guaranteed by the engine.
GUEST_CONTRACT_REFORM_WINDOW_DAYS = 5475


def indent(text: str, spaces: int = 4) -> str:
    prefix = " " * spaces
    return "\n".join(prefix + line if line else line for line in text.splitlines())


def or_block(lines: list[str], spaces: int = 0) -> str:
    pad = " " * spaces
    body = "\n".join(f"{pad}    {line}" for line in lines)
    return f"{pad}OR = {{\n{body}\n{pad}}}"


def academy_root_body(code: str) -> str:
    modifiers = SCHOOLS[code]["academies"]
    provinces = [
        "AND = { "
        f"has_province_modifier = {modifier} "
        "NOT = { has_province_modifier = zhx_academy_under_expulsion } "
        "}"
        for modifier in modifiers
    ]
    return (
        "any_owned_province = {\n"
        + indent(or_block(provinces), 4)
        + "\n}"
    )


def render_triggers() -> str:
    target_flags = [f"has_country_flag = zhx_doctrine_reform_target_{code}" for code in SCHOOLS]
    old_flags = [f"has_country_flag = zhx_doctrine_reform_old_{code}" for code in SCHOOLS]
    reversal_flags = [
        f"has_country_flag = zhx_doctrine_reform_reversal_secondary_{code}"
        for code in SCHOOLS
    ]
    sections = [
        "# Generated by tools/build_zhx_doctrine_reform.py. Do not hand-edit.",
        "# Public integration contract:",
        "# - invitation gates should require NOT = { zhx_doctrine_reform_invitation_locked = yes }",
        "# - Tianxia proposal gates should require zhx_doctrine_reform_may_file_tianxia_proposal = yes,",
        "# - academy protection should OR the school-specific reform protection trigger,",
        "# - consumers should process hook flags and call acknowledge_integration_hooks.",
        "",
        "zhx_doctrine_reform_is_cultivating = {\n"
        "    has_country_flag = zhx_doctrine_reform_cultivating\n"
        "}",
        "",
        "zhx_doctrine_reform_is_in_transition = {\n"
        "    OR = {\n"
        "        has_country_flag = zhx_doctrine_reform_transition\n"
        "        has_country_flag = zhx_doctrine_reform_forced_extension\n"
        "    }\n"
        "}",
        "",
        "zhx_doctrine_reform_is_active = {\n"
        "    OR = {\n"
        "        zhx_doctrine_reform_is_cultivating = yes\n"
        "        zhx_doctrine_reform_is_in_transition = yes\n"
        "    }\n"
        "}",
        "",
        "zhx_doctrine_reform_invitation_locked = {\n"
        "    OR = {\n"
        "        zhx_doctrine_reform_is_active = yes\n"
        "        zhx_doctrine_reform_has_reversal_secondary = yes\n"
        "    }\n"
        "}",
        "",
        "zhx_doctrine_reform_may_file_tianxia_proposal = {\n"
        "    NOT = { zhx_doctrine_reform_is_cultivating = yes }\n"
        "}",
        "",
        "zhx_doctrine_reform_formal_adoption_blocked = {\n"
        "    zhx_tianxia_council_is_busy = yes\n"
        "}",
        "",
        "zhx_doctrine_reform_has_any_target = {\n"
        + indent(or_block(target_flags), 4)
        + "\n}",
        "",
        "zhx_doctrine_reform_has_any_old_school = {\n"
        + indent(or_block(old_flags), 4)
        + "\n}",
        "",
        "zhx_doctrine_reform_has_reversal_secondary = {\n"
        + indent(or_block(reversal_flags), 4)
        + "\n}",
        "",
        "zhx_doctrine_reform_can_begin = {\n"
        "    zhx_is_lijiao_country = yes\n"
        "    zhx_has_doctrine = yes\n"
        "    is_at_war = no\n"
        "    stability = 0\n"
        "    capital_scope = { controlled_by = ROOT }\n"
        "    NOT = { zhx_doctrine_reform_is_active = yes }\n"
        "    NOT = { has_country_modifier = zhx_doctrine_reform_cooldown }\n"
        "}",
    ]

    for code, meta in SCHOOLS.items():
        academy_body = academy_root_body(code)
        guest_contract_flag = f"zhx_guest_school_contract_{code}"
        sections.extend(
            [
                "",
                f"zhx_doctrine_reform_has_active_{code}_academy_root = {{\n"
                + indent(academy_body, 4)
                + "\n}",
                "",
                f"zhx_doctrine_reform_has_{code}_invited_root_now = {{\n"
                f"    has_country_modifier = {meta['invited']}\n"
                f"    has_country_flag = {GUEST_CONTRACT_ACTIVE_FLAG}\n"
                f"    has_country_flag = {guest_contract_flag}\n"
                "}",
                "",
                f"zhx_doctrine_reform_has_{code}_invited_root_with_five_years = {{\n"
                f"    zhx_doctrine_reform_has_{code}_invited_root_now = yes\n"
                "    NOT = {\n"
                "        had_country_flag = {\n"
                f"            flag = {GUEST_CONTRACT_ACTIVE_FLAG}\n"
                f"            days = {GUEST_CONTRACT_REFORM_WINDOW_DAYS}\n"
                "        }\n"
                "    }\n"
                "}",
                "",
                f"zhx_doctrine_reform_has_{code}_root_now = {{\n"
                "    OR = {\n"
                f"        zhx_doctrine_reform_has_{code}_invited_root_now = yes\n"
                f"        zhx_doctrine_reform_has_active_{code}_academy_root = yes\n"
                "    }\n"
                "}",
                "",
                f"zhx_doctrine_reform_can_target_{code} = {{\n"
                "    zhx_doctrine_reform_can_begin = yes\n"
                f"    NOT = {{ has_country_flag = {meta['flag']} }}\n"
                "    OR = {\n"
                "        NOT = { zhx_guest_school_has_active_contract = yes }\n"
                f"        has_country_flag = {guest_contract_flag}\n"
                "    }\n"
                "    OR = {\n"
                f"        zhx_doctrine_reform_has_{code}_invited_root_with_five_years = yes\n"
                f"        zhx_doctrine_reform_has_active_{code}_academy_root = yes\n"
                "    }\n"
                "}",
                "",
                f"zhx_doctrine_reform_target_{code}_retains_root = {{\n"
                f"    has_country_flag = zhx_doctrine_reform_target_{code}\n"
                "    OR = {\n"
                f"        zhx_doctrine_reform_has_{code}_invited_root_now = yes\n"
                f"        zhx_doctrine_reform_has_active_{code}_academy_root = yes\n"
                "    }\n"
                "}",
                "",
                f"zhx_doctrine_reform_old_momentum_protects_{code}_academies = {{\n"
                "    zhx_doctrine_reform_is_in_transition = yes\n"
                f"    has_country_flag = zhx_doctrine_reform_old_{code}\n"
                "}",
                "",
                f"zhx_doctrine_reform_protects_{code}_academies = {{\n"
                "    OR = {\n"
                f"        zhx_doctrine_reform_old_momentum_protects_{code}_academies = yes\n"
                f"        has_country_flag = zhx_doctrine_reform_reversal_secondary_{code}\n"
                "    }\n"
                "}",
                "",
                f"zhx_doctrine_reform_reversal_secondary_is_{code} = {{\n"
                f"    has_country_flag = zhx_doctrine_reform_reversal_secondary_{code}\n"
                "}",
            ]
        )

    retained = [
        f"zhx_doctrine_reform_target_{code}_retains_root = yes" for code in SCHOOLS
    ]
    sections.extend(
        [
            "",
            "zhx_doctrine_reform_target_retains_root = {\n"
            + indent(or_block(retained), 4)
            + "\n}",
            "",
            "zhx_doctrine_reform_has_integration_hooks = {\n"
            "    OR = {\n"
            "        has_country_flag = zhx_doctrine_reform_hook_main_school_changed\n"
            "        has_country_flag = zhx_doctrine_reform_hook_clear_invited_school\n"
            "        has_country_flag = zhx_doctrine_reform_hook_cancel_pending_tianxia_petition\n"
            "        has_country_flag = zhx_doctrine_reform_hook_refresh_doctrine_presentation\n"
            "        has_country_flag = zhx_doctrine_reform_hook_refresh_academies\n"
            "    }\n"
            "}",
            "",
            "zhx_doctrine_reform_ai_may_attempt = {\n"
            "    ai = yes\n"
            "    is_year = 1475\n"
            "    zhx_doctrine_reform_can_begin = yes\n"
            "    stability = 1\n"
            "    has_any_disaster = no\n"
            "    is_bankrupt = no\n"
            "    check_variable = { which = zhx_doctrine_reform_ai_low_practice_years value = 5 }\n"
            "    OR = {\n"
            + "\n".join(
                f"        AND = {{ zhx_doctrine_reform_has_{code}_invited_root_with_five_years = yes NOT = {{ has_country_flag = {meta['flag']} }} }}"
                for code, meta in SCHOOLS.items()
            )
            + "\n    }\n"
            "}",
        ]
    )
    return "\n".join(sections) + "\n"


def render_modifiers() -> str:
    return """# Generated by tools/build_zhx_doctrine_reform.py. Do not hand-edit.

zhx_doctrine_reform_cultivation = {
    global_unrest = 1
    stability_cost_modifier = 0.15
    advisor_cost = 0.15
}

zhx_doctrine_reform_conflict = {
    global_unrest = 2
    stability_cost_modifier = 0.25
    governing_capacity_modifier = -0.10
    global_tax_modifier = -0.10
    manpower_recovery_speed = -0.10
}

# The second five-year push retains the conflict package.  Its extra price is
# the one-time stability loss charged when the player refuses restoration.
zhx_doctrine_reform_forced_extension = {
    global_unrest = 2
    stability_cost_modifier = 0.25
    governing_capacity_modifier = -0.10
    global_tax_modifier = -0.10
    manpower_recovery_speed = -0.10
}

zhx_doctrine_reform_new_order = {
    global_unrest = -1
    stability_cost_modifier = -0.10
    reform_progress_growth = 0.15
    advisor_cost = -0.10
}

zhx_doctrine_reform_reversal = {
    all_power_cost = 0.05
    reform_progress_growth = -0.25
    diplomatic_reputation = -1
    stability_cost_modifier = 0.20
}

zhx_doctrine_reform_indecision = {
    stability_cost_modifier = 0.10
    diplomatic_reputation = -1
}

# Empty, visible timer.  Successful and ordinary settlements use ten years;
# restoration uses fifteen years.
zhx_doctrine_reform_cooldown = { }
"""


def render_opinions() -> str:
    return """# Generated by tools/build_zhx_doctrine_reform.py. Do not hand-edit.

zhx_opinion_abandoned_our_doctrine = {
    opinion = -20
    yearly_decay = 2
}

zhx_opinion_joined_our_doctrine = {
    opinion = 10
    yearly_decay = 1
}
"""


def render_secondary_modifiers() -> str:
    lines = [
        "# Generated by tools/build_zhx_doctrine_reform.py. Do not hand-edit.",
        "# These are display/state tokens, not invited-scholar benefits.  The",
        "# existing mouse-transparent school overlays should also test these",
        "# modifier names so they reuse the exact six invited-school emblems.",
    ]
    for code in SCHOOLS:
        lines.extend(
            [
                "",
                f"zhx_doctrine_reform_secondary_{code} = {{",
                "    religion_sub_modifier = yes",
                "    religion = yes",
                "    is_scholar_modifier = yes",
                "}",
            ]
        )
    return "\n".join(lines) + "\n"


def clear_flag_effect(name: str, flags: list[str]) -> str:
    lines = [f"{name} = {{"]
    lines.extend(f"    clr_country_flag = {flag}" for flag in flags)
    lines.append("}")
    return "\n".join(lines)


def snapshot_old_school() -> str:
    branches = []
    for index, (code, meta) in enumerate(SCHOOLS.items()):
        keyword = "if" if index == 0 else "else_if"
        branches.append(
            f"{keyword} = {{\n"
            f"    limit = {{ has_country_flag = {meta['flag']} }}\n"
            f"    set_country_flag = zhx_doctrine_reform_old_{code}\n"
            "}"
        )
    return "\n".join(branches)


def set_target_as_main() -> str:
    branches = []
    for index, (code, meta) in enumerate(SCHOOLS.items()):
        keyword = "if" if index == 0 else "else_if"
        branches.append(
            f"{keyword} = {{\n"
            f"    limit = {{ has_country_flag = zhx_doctrine_reform_target_{code} }}\n"
            f"    set_country_flag = {meta['flag']}\n"
            "}"
        )
    return "\n".join(branches)


def restore_old_as_main() -> str:
    branches = []
    for index, (code, meta) in enumerate(SCHOOLS.items()):
        keyword = "if" if index == 0 else "else_if"
        branches.append(
            f"{keyword} = {{\n"
            f"    limit = {{ has_country_flag = zhx_doctrine_reform_old_{code} }}\n"
            f"    set_country_flag = {meta['flag']}\n"
            "}"
        )
    return "\n".join(branches)


def mark_target_as_reversal_secondary() -> str:
    branches = []
    for index, code in enumerate(SCHOOLS):
        keyword = "if" if index == 0 else "else_if"
        branches.append(
            f"{keyword} = {{\n"
            f"    limit = {{ has_country_flag = zhx_doctrine_reform_target_{code} }}\n"
            f"    set_country_flag = zhx_doctrine_reform_reversal_secondary_{code}\n"
            "}"
        )
    return "\n".join(branches)


def add_school_secondary(source: str, duration: int) -> str:
    """Render a mutually-exclusive school flag -> display modifier dispatch."""

    branches = []
    for index, code in enumerate(SCHOOLS):
        keyword = "if" if index == 0 else "else_if"
        branches.append(
            f"{keyword} = {{\n"
            f"    limit = {{ has_country_flag = zhx_doctrine_reform_{source}_{code} }}\n"
            "    add_country_modifier = {\n"
            f"        name = zhx_doctrine_reform_secondary_{code}\n"
            f"        duration = {duration}\n"
            "    }\n"
            "}"
        )
    return "\n".join(branches)


def international_reaction() -> str:
    pieces = []
    for code, meta in SCHOOLS.items():
        pieces.append(
            f"if = {{\n"
            f"    limit = {{ has_country_flag = zhx_doctrine_reform_old_{code} }}\n"
            "    every_country = {\n"
            "        limit = {\n"
            "            exists = yes\n"
            "            NOT = { tag = event_target:zhx_doctrine_reform_actor }\n"
            "            zhx_is_lijiao_country = yes\n"
            f"            has_country_flag = {meta['flag']}\n"
            "        }\n"
            "        add_opinion = { who = event_target:zhx_doctrine_reform_actor modifier = zhx_opinion_abandoned_our_doctrine }\n"
            "    }\n"
            "}"
        )
    for code, meta in SCHOOLS.items():
        pieces.append(
            f"if = {{\n"
            f"    limit = {{ has_country_flag = zhx_doctrine_reform_target_{code} }}\n"
            "    every_country = {\n"
            "        limit = {\n"
            "            exists = yes\n"
            "            NOT = { tag = event_target:zhx_doctrine_reform_actor }\n"
            "            zhx_is_lijiao_country = yes\n"
            f"            has_country_flag = {meta['flag']}\n"
            "        }\n"
            "        add_opinion = { who = event_target:zhx_doctrine_reform_actor modifier = zhx_opinion_joined_our_doctrine }\n"
            "    }\n"
            "}"
        )
    return "\n".join(pieces)


def begin_effect(code: str) -> str:
    meta = SCHOOLS[code]
    return f"""zhx_doctrine_reform_begin_{code} = {{
    if = {{
        limit = {{ zhx_doctrine_reform_can_target_{code} = yes }}
        zhx_doctrine_reform_clear_process_state = yes
        set_country_flag = zhx_doctrine_reform_cultivating
        set_country_flag = zhx_doctrine_reform_target_{code}
{indent(snapshot_old_school(), 8)}
        if = {{
            limit = {{ zhx_doctrine_reform_has_{code}_invited_root_now = yes }}
            set_country_flag = zhx_doctrine_reform_root_invited_{code}
        }}
        add_country_modifier = {{
            name = zhx_doctrine_reform_cultivation
            duration = 1825
        }}
        country_event = {{ id = zhx_doctrine_reform.90 days = 365 }}
        country_event = {{ id = zhx_doctrine_reform.100 days = 1825 }}
    }}
}}
"""


def render_effects() -> str:
    target_flags = [f"zhx_doctrine_reform_target_{code}" for code in SCHOOLS]
    old_flags = [f"zhx_doctrine_reform_old_{code}" for code in SCHOOLS]
    root_flags = [f"zhx_doctrine_reform_root_invited_{code}" for code in SCHOOLS]
    reversal_flags = [f"zhx_doctrine_reform_reversal_secondary_{code}" for code in SCHOOLS]
    doctrine_flags = [str(meta["flag"]) for meta in SCHOOLS.values()]
    parts = [
        "# Generated by tools/build_zhx_doctrine_reform.py. Do not hand-edit.\n"
        "# The *_hook_* country flags are output ports.  Existing doctrine,\n"
        "# invitation, academy and Tianxia layers consume them, perform their\n"
        "# own refresh, then call acknowledge_integration_hooks.\n",
        clear_flag_effect("zhx_doctrine_reform_clear_target_flags", target_flags),
        clear_flag_effect("zhx_doctrine_reform_clear_old_flags", old_flags),
        clear_flag_effect("zhx_doctrine_reform_clear_root_flags", root_flags),
        clear_flag_effect("zhx_doctrine_reform_clear_reversal_secondary_flags", reversal_flags),
        clear_flag_effect("zhx_doctrine_reform_clear_authoritative_doctrine_flags", doctrine_flags),
        """zhx_doctrine_reform_clear_secondary_modifiers = {
"""
        + "\n".join(
            f"    remove_country_modifier = zhx_doctrine_reform_secondary_{code}"
            for code in SCHOOLS
        )
        + "\n}\n",
        """zhx_doctrine_reform_add_old_secondary_10y = {
    zhx_doctrine_reform_clear_secondary_modifiers = yes
"""
        + indent(add_school_secondary("old", 3650), 4)
        + "\n}\n",
        """zhx_doctrine_reform_add_old_secondary_5y = {
    zhx_doctrine_reform_clear_secondary_modifiers = yes
"""
        + indent(add_school_secondary("old", 1825), 4)
        + "\n}\n",
        """zhx_doctrine_reform_add_target_secondary_10y = {
    zhx_doctrine_reform_clear_secondary_modifiers = yes
"""
        + indent(add_school_secondary("target", 3650), 4)
        + "\n}\n",
        """zhx_doctrine_reform_acknowledge_integration_hooks = {
    clr_country_flag = zhx_doctrine_reform_hook_main_school_changed
    clr_country_flag = zhx_doctrine_reform_hook_clear_invited_school
    clr_country_flag = zhx_doctrine_reform_hook_cancel_pending_tianxia_petition
    clr_country_flag = zhx_doctrine_reform_hook_refresh_doctrine_presentation
    clr_country_flag = zhx_doctrine_reform_hook_refresh_academies
}
""",
        """zhx_doctrine_reform_clear_process_state = {
    remove_country_modifier = zhx_doctrine_reform_cultivation
    remove_country_modifier = zhx_doctrine_reform_conflict
    remove_country_modifier = zhx_doctrine_reform_forced_extension
    clr_country_flag = zhx_doctrine_reform_cultivating
    clr_country_flag = zhx_doctrine_reform_transition
    clr_country_flag = zhx_doctrine_reform_forced_extension
    clr_country_flag = zhx_doctrine_reform_waiting_for_tianxia_close
    zhx_doctrine_reform_clear_target_flags = yes
    zhx_doctrine_reform_clear_old_flags = yes
    zhx_doctrine_reform_clear_root_flags = yes
}
""",
        """zhx_doctrine_reform_clear_all_state = {
    zhx_doctrine_reform_clear_process_state = yes
    zhx_doctrine_reform_clear_reversal_secondary_flags = yes
    zhx_doctrine_reform_clear_secondary_modifiers = yes
    zhx_doctrine_reform_acknowledge_integration_hooks = yes
    remove_country_modifier = zhx_doctrine_reform_new_order
    remove_country_modifier = zhx_doctrine_reform_reversal
    remove_country_modifier = zhx_doctrine_reform_indecision
    remove_country_modifier = zhx_doctrine_reform_cooldown
    set_variable = { which = zhx_doctrine_reform_ai_low_practice_years value = 0 }
}
""",
        """zhx_doctrine_reform_cancel = {
    if = {
        limit = { zhx_doctrine_reform_is_cultivating = yes }
        zhx_doctrine_reform_clear_process_state = yes
        add_country_modifier = {
            name = zhx_doctrine_reform_indecision
            duration = 1825
        }
        add_country_modifier = {
            name = zhx_doctrine_reform_cooldown
            duration = 3650
        }
        set_country_flag = zhx_doctrine_reform_hook_refresh_academies
        zhx_consume_doctrine_reform_integration_hooks = yes
    }
}
""",
    ]
    parts.extend(begin_effect(code) for code in SCHOOLS)
    parts.extend(
        [
            """zhx_doctrine_reform_apply_international_reaction = {
    save_event_target_as = zhx_doctrine_reform_actor
"""
            + indent(international_reaction(), 4)
            + "\n}\n",
            """zhx_doctrine_reform_formal_adopt_target = {
    if = {
        limit = {
            zhx_doctrine_reform_is_cultivating = yes
            zhx_doctrine_reform_target_retains_root = yes
            NOT = { zhx_doctrine_reform_formal_adoption_blocked = yes }
        }
        remove_country_modifier = zhx_doctrine_reform_cultivation
        clr_country_flag = zhx_doctrine_reform_cultivating
        clr_country_flag = zhx_doctrine_reform_waiting_for_tianxia_close
        set_country_flag = zhx_doctrine_reform_transition
        zhx_doctrine_reform_clear_authoritative_doctrine_flags = yes
"""
            + indent(set_target_as_main(), 8)
            + """
        set_country_flag = zhx_doctrine_practice_initialised
        set_variable = { which = zhx_doctrine_practice value = 15 }
        set_variable = { which = zhx_doctrine_reform_ai_low_practice_years value = 0 }
        add_stability = -1
        add_prestige = -25
        add_country_modifier = {
            name = zhx_doctrine_reform_conflict
            duration = 3650
        }
        set_country_flag = zhx_doctrine_reform_hook_main_school_changed
        set_country_flag = zhx_doctrine_reform_hook_clear_invited_school
        set_country_flag = zhx_doctrine_reform_hook_cancel_pending_tianxia_petition
        set_country_flag = zhx_doctrine_reform_hook_refresh_doctrine_presentation
        set_country_flag = zhx_doctrine_reform_hook_refresh_academies
        zhx_doctrine_reform_add_old_secondary_10y = yes
        zhx_doctrine_reform_apply_international_reaction = yes
        zhx_consume_doctrine_reform_integration_hooks = yes
        country_event = { id = zhx_doctrine_reform.101 }
        country_event = { id = zhx_doctrine_reform.200 days = 3650 }
    }
}
""",
            """zhx_doctrine_reform_resume_formal_adoption = {
    if = {
        limit = {
            zhx_doctrine_reform_is_cultivating = yes
            has_country_flag = zhx_doctrine_reform_waiting_for_tianxia_close
            NOT = { zhx_doctrine_reform_formal_adoption_blocked = yes }
        }
        zhx_doctrine_reform_formal_adopt_target = yes
    }
}
""",
            """zhx_doctrine_reform_finish_success = {
    if = {
        limit = { has_country_flag = zhx_doctrine_reform_transition }
        zhx_doctrine_reform_clear_secondary_modifiers = yes
        zhx_doctrine_reform_clear_process_state = yes
        add_country_modifier = {
            name = zhx_doctrine_reform_new_order
            duration = 3650
        }
        add_country_modifier = {
            name = zhx_doctrine_reform_cooldown
            duration = 3650
        }
        set_country_flag = zhx_doctrine_reform_hook_refresh_doctrine_presentation
        set_country_flag = zhx_doctrine_reform_hook_refresh_academies
        zhx_consume_doctrine_reform_integration_hooks = yes
        country_event = { id = zhx_doctrine_reform.201 }
    }
}

zhx_doctrine_reform_finish_without_reward = {
    if = {
        limit = { has_country_flag = zhx_doctrine_reform_transition }
        zhx_doctrine_reform_clear_secondary_modifiers = yes
        zhx_doctrine_reform_clear_process_state = yes
        add_country_modifier = {
            name = zhx_doctrine_reform_cooldown
            duration = 3650
        }
        set_country_flag = zhx_doctrine_reform_hook_refresh_doctrine_presentation
        set_country_flag = zhx_doctrine_reform_hook_refresh_academies
        zhx_consume_doctrine_reform_integration_hooks = yes
        country_event = { id = zhx_doctrine_reform.202 }
    }
}

zhx_doctrine_reform_settle_transition = {
    if = {
        limit = { has_country_flag = zhx_doctrine_reform_transition }
        if = {
            limit = { NOT = { zhx_is_lijiao_country = yes } }
            zhx_doctrine_reform_clear_all_state = yes
        }
        else_if = {
            limit = {
                check_variable = { which = zhx_doctrine_practice value = 50 }
                stability = 1
            }
            zhx_doctrine_reform_finish_success = yes
        }
        else_if = {
            limit = { check_variable = { which = zhx_doctrine_practice value = 25 } }
            zhx_doctrine_reform_finish_without_reward = yes
        }
        else = {
            country_event = { id = zhx_doctrine_reform.210 }
        }
    }
}
""",
            """zhx_doctrine_reform_force_new_school = {
    if = {
        limit = { has_country_flag = zhx_doctrine_reform_transition }
        remove_country_modifier = zhx_doctrine_reform_conflict
        clr_country_flag = zhx_doctrine_reform_transition
        set_country_flag = zhx_doctrine_reform_forced_extension
        add_stability = -1
        add_country_modifier = {
            name = zhx_doctrine_reform_forced_extension
            duration = 1825
        }
        zhx_doctrine_reform_add_old_secondary_5y = yes
        country_event = { id = zhx_doctrine_reform.300 days = 1825 }
    }
}
""",
            """zhx_doctrine_reform_restore_old_school = {
    if = {
        limit = { has_country_flag = zhx_doctrine_reform_transition }
        remove_country_modifier = zhx_doctrine_reform_conflict
"""
            + indent(mark_target_as_reversal_secondary(), 8)
            + """
        zhx_doctrine_reform_add_target_secondary_10y = yes
        zhx_doctrine_reform_clear_authoritative_doctrine_flags = yes
"""
            + indent(restore_old_as_main(), 8)
            + """
        set_country_flag = zhx_doctrine_practice_initialised
        set_variable = { which = zhx_doctrine_practice value = 25 }
        set_variable = { which = zhx_doctrine_reform_ai_low_practice_years value = 0 }
        zhx_doctrine_reform_clear_process_state = yes
        add_country_modifier = {
            name = zhx_doctrine_reform_reversal
            duration = 3650
        }
        add_country_modifier = {
            name = zhx_doctrine_reform_cooldown
            duration = 5475
        }
        set_country_flag = zhx_doctrine_reform_hook_main_school_changed
        set_country_flag = zhx_doctrine_reform_hook_clear_invited_school
        set_country_flag = zhx_doctrine_reform_hook_refresh_doctrine_presentation
        set_country_flag = zhx_doctrine_reform_hook_refresh_academies
        zhx_consume_doctrine_reform_integration_hooks = yes
        country_event = { id = zhx_doctrine_reform.400 days = 3650 }
    }
}
""",
            """zhx_doctrine_reform_finish_forced_extension = {
    if = {
        limit = { has_country_flag = zhx_doctrine_reform_forced_extension }
        zhx_doctrine_reform_clear_secondary_modifiers = yes
        zhx_doctrine_reform_clear_process_state = yes
        add_country_modifier = {
            name = zhx_doctrine_reform_cooldown
            duration = 3650
        }
        set_country_flag = zhx_doctrine_reform_hook_refresh_doctrine_presentation
        set_country_flag = zhx_doctrine_reform_hook_refresh_academies
        zhx_consume_doctrine_reform_integration_hooks = yes
        country_event = { id = zhx_doctrine_reform.301 }
    }
}
""",
            """zhx_doctrine_reform_after_initial_foundation = {
    # Public entry for the unified "诸子临朝" adoption route.  It prevents a
    # newly founded doctrine from immediately entering the reform process.
    add_country_modifier = {
        name = zhx_doctrine_reform_cooldown
        duration = 3650
    }
    set_variable = { which = zhx_doctrine_reform_ai_low_practice_years value = 0 }
}

zhx_doctrine_reform_reconcile = {
    if = {
        limit = { NOT = { zhx_is_lijiao_country = yes } }
        zhx_doctrine_reform_clear_all_state = yes
    }
    else = {
        if = {
            limit = {
                zhx_doctrine_reform_is_cultivating = yes
                NOT = { zhx_doctrine_reform_target_retains_root = yes }
            }
            zhx_doctrine_reform_cancel = yes
            country_event = { id = zhx_doctrine_reform.91 }
        }
        else_if = {
            limit = {
                zhx_doctrine_reform_is_cultivating = yes
                NOT = { has_country_modifier = zhx_doctrine_reform_cultivation }
                NOT = { zhx_doctrine_reform_formal_adoption_blocked = yes }
            }
            zhx_doctrine_reform_formal_adopt_target = yes
        }
        if = {
            limit = {
                has_country_flag = zhx_doctrine_reform_transition
                NOT = { has_country_modifier = zhx_doctrine_reform_conflict }
            }
            zhx_doctrine_reform_settle_transition = yes
        }
        if = {
            limit = {
                has_country_flag = zhx_doctrine_reform_forced_extension
                NOT = { has_country_modifier = zhx_doctrine_reform_forced_extension }
            }
            zhx_doctrine_reform_finish_forced_extension = yes
        }
        if = {
            limit = {
                zhx_doctrine_reform_has_reversal_secondary = yes
                NOT = { has_country_modifier = zhx_doctrine_reform_reversal }
            }
            zhx_doctrine_reform_clear_secondary_modifiers = yes
            zhx_doctrine_reform_clear_reversal_secondary_flags = yes
            set_country_flag = zhx_doctrine_reform_hook_clear_invited_school
            set_country_flag = zhx_doctrine_reform_hook_refresh_doctrine_presentation
            set_country_flag = zhx_doctrine_reform_hook_refresh_academies
            zhx_consume_doctrine_reform_integration_hooks = yes
        }
    }
}

# Call from the existing religion-change hook.  Repeated calls are harmless.
zhx_doctrine_reform_on_religion_change = {
    if = {
        limit = { NOT = { zhx_is_lijiao_country = yes } }
        zhx_doctrine_reform_clear_all_state = yes
    }
}

# Call once from the existing yearly doctrine event after practice settlement.
# AI uses only a genuinely invited secondary school as a reform root.
zhx_doctrine_reform_yearly_tick = {
    zhx_doctrine_reform_reconcile = yes
    if = {
        limit = {
            ai = yes
            zhx_is_lijiao_country = yes
            zhx_has_doctrine = yes
        }
        if = {
            limit = { NOT = { check_variable = { which = zhx_doctrine_practice value = 25 } } }
            change_variable = { which = zhx_doctrine_reform_ai_low_practice_years value = 1 }
        }
        else = {
            set_variable = { which = zhx_doctrine_reform_ai_low_practice_years value = 0 }
        }
        if = {
            limit = { zhx_doctrine_reform_ai_may_attempt = yes }
            random = {
                chance = 8
                country_event = { id = zhx_doctrine_reform.50 }
            }
        }
    }
    else_if = {
        limit = { ai = yes }
        set_variable = { which = zhx_doctrine_reform_ai_low_practice_years value = 0 }
    }
}
""",
        ]
    )
    return "\n\n".join(part.rstrip() for part in parts) + "\n"


def render_decisions() -> str:
    target_checks = [f"zhx_doctrine_reform_can_target_{code} = yes" for code in SCHOOLS]
    return (
        "# Generated by tools/build_zhx_doctrine_reform.py. Do not hand-edit.\n\n"
        "country_decisions = {\n"
        "    zhx_begin_doctrine_reform = {\n"
        "        major = yes\n\n"
        "        potential = {\n"
        "            ai = no\n"
        "            zhx_is_lijiao_country = yes\n"
        "            zhx_has_doctrine = yes\n"
        "        }\n\n"
        "        allow = {\n"
        "            custom_trigger_tooltip = {\n"
        "                tooltip = zhx_begin_doctrine_reform_requirements_tt\n"
        + indent(or_block(target_checks), 16)
        + "\n            }\n"
        "        }\n\n"
        "        effect = { country_event = { id = zhx_doctrine_reform.1 } }\n"
        "        ai_will_do = { factor = 0 }\n"
        "    }\n\n"
        "    zhx_cancel_doctrine_reform = {\n"
        "        major = no\n\n"
        "        potential = {\n"
        "            ai = no\n"
        "            zhx_doctrine_reform_is_cultivating = yes\n"
        "        }\n\n"
        "        allow = { always = yes }\n"
        "        effect = {\n"
        "            custom_tooltip = zhx_cancel_doctrine_reform_effect_tt\n"
        "            hidden_effect = { zhx_doctrine_reform_cancel = yes }\n"
        "        }\n"
        "        ai_will_do = { factor = 0 }\n"
        "    }\n"
        "}\n"
    )


def target_option(code: str, confirm_id: int, spaces: int = 4) -> str:
    return indent(
        f"option = {{\n"
        f"    name = zhx_doctrine_reform.choose_{code}\n"
        "    trigger = {\n"
        "        custom_trigger_tooltip = {\n"
        f"            tooltip = zhx_doctrine_reform_target_{code}_requirements_tt\n"
        f"            zhx_doctrine_reform_can_target_{code} = yes\n"
        "        }\n"
        "    }\n"
        f"    country_event = {{ id = zhx_doctrine_reform.{confirm_id} }}\n"
        "    ai_chance = { factor = 1 }\n"
        "}",
        spaces,
    )


def render_events() -> str:
    first = list(SCHOOLS)[:3]
    second = list(SCHOOLS)[3:]
    sections = [
        "namespace = zhx_doctrine_reform",
        "",
        "# Player target catalogue: three options per page keep the event safe at",
        "# ordinary UI scales.  Every school receives a separate confirmation card.",
        "country_event = {",
        "    id = zhx_doctrine_reform.1",
        "    title = zhx_doctrine_reform.1.t",
        "    desc = zhx_doctrine_reform.1.d",
        "    picture = DIPLOMACY_eventPicture",
        "    is_triggered_only = yes",
        "    trigger = { zhx_doctrine_reform_can_begin = yes }",
        "",
        *(target_option(code, 10 + index).rstrip() for index, code in enumerate(first)),
        "    option = {",
        "        name = zhx_doctrine_reform.next_page",
        "        country_event = { id = zhx_doctrine_reform.2 }",
        "        ai_chance = { factor = 0 }",
        "    }",
        "    option = { name = zhx_doctrine_reform.not_now ai_chance = { factor = 0 } }",
        "}",
        "",
        "country_event = {",
        "    id = zhx_doctrine_reform.2",
        "    title = zhx_doctrine_reform.2.t",
        "    desc = zhx_doctrine_reform.2.d",
        "    picture = DIPLOMACY_eventPicture",
        "    is_triggered_only = yes",
        "    trigger = { zhx_doctrine_reform_can_begin = yes }",
        "",
        *(target_option(code, 10 + len(first) + index).rstrip() for index, code in enumerate(second)),
        "    option = {",
        "        name = zhx_doctrine_reform.previous_page",
        "        country_event = { id = zhx_doctrine_reform.1 }",
        "        ai_chance = { factor = 0 }",
        "    }",
        "    option = { name = zhx_doctrine_reform.not_now ai_chance = { factor = 0 } }",
        "}",
    ]

    for index, (code, meta) in enumerate(SCHOOLS.items()):
        event_id = 10 + index
        sections.extend(
            [
                "",
                "country_event = {",
                f"    id = zhx_doctrine_reform.{event_id}",
                f"    title = zhx_doctrine_reform.confirm_{code}.t",
                f"    desc = zhx_doctrine_reform.confirm_{code}.d",
                "    picture = DIPLOMACY_eventPicture",
                "    is_triggered_only = yes",
                f"    trigger = {{ zhx_doctrine_reform_can_target_{code} = yes }}",
                "",
                "    option = {",
                f"        name = zhx_doctrine_reform.confirm_{code}.a",
                "        custom_tooltip = zhx_doctrine_reform_confirm_cost_tt",
                f"        hidden_effect = {{ zhx_doctrine_reform_begin_{code} = yes }}",
                "        ai_chance = { factor = 1 }",
                "    }",
                "    option = {",
                "        name = zhx_doctrine_reform.back_to_catalogue",
                "        country_event = { id = zhx_doctrine_reform.1 }",
                "        ai_chance = { factor = 0 }",
                "    }",
                "}",
            ]
        )

    ai_branches = []
    for index, (code, meta) in enumerate(SCHOOLS.items()):
        keyword = "if" if index == 0 else "else_if"
        ai_branches.extend(
            [
                f"        {keyword} = {{",
                "            limit = {",
                f"                zhx_doctrine_reform_has_{code}_invited_root_with_five_years = yes",
                f"                NOT = {{ has_country_flag = {meta['flag']} }}",
                f"                zhx_doctrine_reform_can_target_{code} = yes",
                "            }",
                f"            zhx_doctrine_reform_begin_{code} = yes",
                "        }",
            ]
        )

    sections.extend(
        [
            "",
            "# Conservative AI entry.  The yearly public hook owns the five-year",
            "# low-practice counter and rare 8% attempt; this event only dispatches",
            "# the currently invited school and never uses an academy shortcut.",
            "country_event = {",
            "    id = zhx_doctrine_reform.50",
            "    title = zhx_doctrine_reform.91.t",
            "    desc = zhx_doctrine_reform.91.d",
            "    picture = DIPLOMACY_eventPicture",
            "    hidden = yes",
            "    is_triggered_only = yes",
            "    trigger = { zhx_doctrine_reform_ai_may_attempt = yes }",
            "    immediate = {",
            *ai_branches,
            "    }",
            "    option = { name = OK }",
            "}",
            "",
            "# Annual cultivation watchdog.  An invitation present at the start is",
            "# deliberately locked as a valid root; academy-only roots must still exist",
            "# and must not be under an expulsion order.",
            "country_event = {",
            "    id = zhx_doctrine_reform.90",
            "    title = zhx_doctrine_reform.91.t",
            "    desc = zhx_doctrine_reform.91.d",
            "    picture = DIPLOMACY_eventPicture",
            "    hidden = yes",
            "    is_triggered_only = yes",
            "    trigger = { zhx_doctrine_reform_is_cultivating = yes }",
            "    immediate = {",
            "        zhx_doctrine_reform_reconcile = yes",
            "        if = {",
            "            limit = { zhx_doctrine_reform_is_cultivating = yes }",
            "            country_event = { id = zhx_doctrine_reform.90 days = 365 }",
            "        }",
            "    }",
            "    option = { name = OK }",
            "}",
            "",
            "country_event = {",
            "    id = zhx_doctrine_reform.91",
            "    title = zhx_doctrine_reform.91.t",
            "    desc = zhx_doctrine_reform.91.d",
            "    picture = DIPLOMACY_eventPicture",
            "    is_triggered_only = yes",
            "    option = { name = zhx_doctrine_reform.91.a }",
            "}",
            "",
            "# Five-year deadline.  The shared Tianxia busy trigger delays formal",
            "# adoption, so the country finishes any already-open ballot as its old school.",
            "country_event = {",
            "    id = zhx_doctrine_reform.100",
            "    title = zhx_doctrine_reform.91.t",
            "    desc = zhx_doctrine_reform.91.d",
            "    picture = DIPLOMACY_eventPicture",
            "    hidden = yes",
            "    is_triggered_only = yes",
            "    trigger = { zhx_doctrine_reform_is_cultivating = yes }",
            "    immediate = {",
            "        zhx_doctrine_reform_reconcile = yes",
            "        if = {",
            "            limit = {",
            "                zhx_doctrine_reform_is_cultivating = yes",
            "                zhx_doctrine_reform_formal_adoption_blocked = yes",
            "            }",
            "            set_country_flag = zhx_doctrine_reform_waiting_for_tianxia_close",
            "            country_event = { id = zhx_doctrine_reform.100 days = 30 }",
            "        }",
            "        else_if = {",
            "            limit = { zhx_doctrine_reform_is_cultivating = yes }",
            "            zhx_doctrine_reform_formal_adopt_target = yes",
            "        }",
            "    }",
            "    option = { name = OK }",
            "}",
            "",
            "country_event = {",
            "    id = zhx_doctrine_reform.101",
            "    title = zhx_doctrine_reform.101.t",
            "    desc = zhx_doctrine_reform.101.d",
            "    picture = DIPLOMACY_eventPicture",
            "    is_triggered_only = yes",
            "    trigger = { has_country_flag = zhx_doctrine_reform_transition }",
            "    option = { name = zhx_doctrine_reform.101.a }",
            "}",
            "",
            "country_event = {",
            "    id = zhx_doctrine_reform.200",
            "    title = zhx_doctrine_reform.91.t",
            "    desc = zhx_doctrine_reform.91.d",
            "    picture = DIPLOMACY_eventPicture",
            "    hidden = yes",
            "    is_triggered_only = yes",
            "    trigger = { has_country_flag = zhx_doctrine_reform_transition }",
            "    immediate = { zhx_doctrine_reform_settle_transition = yes }",
            "    option = { name = OK }",
            "}",
            "",
            "country_event = {",
            "    id = zhx_doctrine_reform.201",
            "    title = zhx_doctrine_reform.201.t",
            "    desc = zhx_doctrine_reform.201.d",
            "    picture = DIPLOMACY_eventPicture",
            "    is_triggered_only = yes",
            "    option = { name = zhx_doctrine_reform.201.a }",
            "}",
            "",
            "country_event = {",
            "    id = zhx_doctrine_reform.202",
            "    title = zhx_doctrine_reform.202.t",
            "    desc = zhx_doctrine_reform.202.d",
            "    picture = DIPLOMACY_eventPicture",
            "    is_triggered_only = yes",
            "    option = { name = zhx_doctrine_reform.202.a }",
            "}",
            "",
            "country_event = {",
            "    id = zhx_doctrine_reform.210",
            "    title = zhx_doctrine_reform.210.t",
            "    desc = zhx_doctrine_reform.210.d",
            "    picture = DIPLOMACY_eventPicture",
            "    is_triggered_only = yes",
            "    trigger = { has_country_flag = zhx_doctrine_reform_transition }",
            "",
            "    option = {",
            "        name = zhx_doctrine_reform.210.a",
            "        custom_tooltip = zhx_doctrine_reform_force_tt",
            "        hidden_effect = { zhx_doctrine_reform_force_new_school = yes }",
            "        ai_chance = {",
            "            factor = 1",
            "            modifier = { factor = 0.25 NOT = { stability = 1 } }",
            "            modifier = { factor = 2 stability = 2 }",
            "        }",
            "    }",
            "    option = {",
            "        name = zhx_doctrine_reform.210.b",
            "        custom_tooltip = zhx_doctrine_reform_restore_tt",
            "        hidden_effect = { zhx_doctrine_reform_restore_old_school = yes }",
            "        ai_chance = {",
            "            factor = 2",
            "            modifier = { factor = 3 NOT = { stability = 1 } }",
            "            modifier = { factor = 2 NOT = { check_variable = { which = zhx_doctrine_practice value = 15 } } }",
            "        }",
            "    }",
            "}",
            "",
            "country_event = {",
            "    id = zhx_doctrine_reform.300",
            "    title = zhx_doctrine_reform.91.t",
            "    desc = zhx_doctrine_reform.91.d",
            "    picture = DIPLOMACY_eventPicture",
            "    hidden = yes",
            "    is_triggered_only = yes",
            "    trigger = { has_country_flag = zhx_doctrine_reform_forced_extension }",
            "    immediate = { zhx_doctrine_reform_finish_forced_extension = yes }",
            "    option = { name = OK }",
            "}",
            "",
            "country_event = {",
            "    id = zhx_doctrine_reform.301",
            "    title = zhx_doctrine_reform.301.t",
            "    desc = zhx_doctrine_reform.301.d",
            "    picture = DIPLOMACY_eventPicture",
            "    is_triggered_only = yes",
            "    option = { name = zhx_doctrine_reform.301.a }",
            "}",
            "",
            "country_event = {",
            "    id = zhx_doctrine_reform.400",
            "    title = zhx_doctrine_reform.91.t",
            "    desc = zhx_doctrine_reform.91.d",
            "    picture = DIPLOMACY_eventPicture",
            "    hidden = yes",
            "    is_triggered_only = yes",
            "    trigger = { zhx_doctrine_reform_has_reversal_secondary = yes }",
            "    immediate = {",
            "        zhx_doctrine_reform_clear_secondary_modifiers = yes",
            "        zhx_doctrine_reform_clear_reversal_secondary_flags = yes",
            "        set_country_flag = zhx_doctrine_reform_hook_clear_invited_school",
            "        set_country_flag = zhx_doctrine_reform_hook_refresh_doctrine_presentation",
            "        set_country_flag = zhx_doctrine_reform_hook_refresh_academies",
            "        zhx_consume_doctrine_reform_integration_hooks = yes",
            "    }",
            "    option = { name = OK }",
            "}",
        ]
    )
    return "\n".join(sections) + "\n"


def render_localisation() -> str:
    lines = [
        "l_english:",
        ' zhx_begin_doctrine_reform_title:0 "更张国论"',
        ' zhx_begin_doctrine_reform_desc:0 "以受邀第二学派或境内未遭逐学的活跃学宫为根基，扶植一种新学说。培植五年后，新学将取代现行主学派。"',
        ' zhx_begin_doctrine_reform_requirements_tt:0 "可开启国论更张：国家处于和平、稳定度至少为§Y0§!、首都受控，且不在更张或冷却期；至少一门其他学派已由受邀学者扎根五年，或拥有一座未遭逐学的活跃学宫。已有宾学时，只能更张为该宾学。"',
        ' zhx_cancel_doctrine_reform_title:0 "罢议更张"',
        ' zhx_cancel_doctrine_reform_desc:0 "撤回正在培植的新论。朝廷将因朝议无定而承受五年余波，十年内不得再次发动更张。"',
        ' zhx_cancel_doctrine_reform_effect_tt:0 "撤回正在培植的新论，承受§Y5年§!朝议无定，并在§Y10年§!内不得再次发动国论更张。"',
        ' zhx_doctrine_reform.1.t:0 "广开新论"',
        ' zhx_doctrine_reform.1.d:0 "诸子再至朝堂。唯有已经受邀入廷，或在我国拥有一座未遭逐学的活跃学宫者，才有资格成为更张国论的根基。"',
        ' zhx_doctrine_reform.2.t:0 "广开新论·后席"',
        ' zhx_doctrine_reform.2.d:0 "道、兵、纵横诸家亦各陈其说。国论一旦开始培植，五年内不得另邀客学，正式更张之后还要经历十年新旧相攻。"',
        ' zhx_doctrine_reform.next_page:0 "再听诸家"',
        ' zhx_doctrine_reform.previous_page:0 "返回前席"',
        ' zhx_doctrine_reform.not_now:0 "今日暂不更张"',
        ' zhx_doctrine_reform.back_to_catalogue:0 "返回诸家席次"',
        ' zhx_doctrine_reform_confirm_cost_tt:0 "开始§Y五年§!培植：全国叛乱§R+1§!、提升稳定度花费§R+15%§!、顾问花费§R+15%§!。正式采用时失去§R1§!稳定度和§R25§!威望，新学践履设为§Y15§!，并进入十年§Y新旧相攻§!。"',
        ' zhx_doctrine_reform.91.t:0 "新论失其根基"',
        ' zhx_doctrine_reform.91.d:0 "支持更张的国内根基已经全部消失，朝廷不得不撤回新论。此后五年朝议无定，十年内不能再次发动更张。"',
        ' zhx_doctrine_reform.91.a:0 "朝议遂罢"',
        ' zhx_doctrine_reform.101.t:0 "更张国论"',
        ' zhx_doctrine_reform.101.d:0 "五年培植已足，新学正式升为国家主学派。旧学仍有十年余势，只保护其学宫而不再提供主学派或客学收益。若十年内不能把新学践履提高到50，朝廷将无法宣告新政既定。"',
        ' zhx_doctrine_reform.101.a:0 "新旧之争，由此而始"',
        ' zhx_doctrine_reform.201.t:0 "新政既定"',
        ' zhx_doctrine_reform.201.d:0 "十年之间，新学践履已经达到50，国家稳定度也至少为1。旧学余势消散，新的国论获得朝野承认；国家将在未来十年享受新政既定的恢复收益。"',
        ' zhx_doctrine_reform.201.a:0 "国论于是定矣"',
        ' zhx_doctrine_reform.202.t:0 "国论勉强安定"',
        ' zhx_doctrine_reform.202.d:0 "新学践履尚未达到50，却已不再处于空疏之境。新旧相攻就此结束，但朝廷不能获得新政既定的奖励。"',
        ' zhx_doctrine_reform.202.a:0 "先使争论止息"',
        ' zhx_doctrine_reform.210.t:0 "更张未成"',
        ' zhx_doctrine_reform.210.d:0 "十年已过，新学践履仍低于25。朝廷可以再付稳定代价强推五年，也可以迎还旧学，承认此前更张失败。"',
        ' zhx_doctrine_reform.210.a:0 "再推新学五年"',
        ' zhx_doctrine_reform.210.b:0 "迎还旧学"',
        ' zhx_doctrine_reform_force_tt:0 "失去§R1§!稳定度，§Y新旧相攻§!延长五年。第二次到期不再授予成功奖励，之后进入十年冷却。"',
        ' zhx_doctrine_reform_restore_tt:0 "旧学恢复为主学派且践履设为§Y25§!；新学暂居第二槽十年。国家承受十年§Y朝令夕改§!，并在十五年内不得再次更张。"',
        ' zhx_doctrine_reform.301.t:0 "强推告终"',
        ' zhx_doctrine_reform.301.d:0 "朝廷又以五年强推新学。无论其践履高低，新旧相攻都不再延长，也不再授予新政既定奖励；国家将在十年后才能重新讨论更张。"',
        ' zhx_doctrine_reform.301.a:0 "此议到此为止"',
        ' zhx_doctrine_reform_cultivation:0 "广开新论"',
        ' zhx_doctrine_reform_cultivation_desc:0 "朝廷正在培植一种有国内根基的新学。五年内不能邀请或替换第二学派，也不能代表本国提出新的天下大辩提案。"',
        ' zhx_doctrine_reform_conflict:0 "新旧相攻"',
        ' zhx_doctrine_reform_conflict_desc:0 "新学已升为国论，旧学仍有余势。十年到期时，新学践履达到50且稳定度至少为1，才能获得新政既定奖励；低于25则判定更张失败。"',
        ' zhx_doctrine_reform_forced_extension:0 "强推新学"',
        ' zhx_doctrine_reform_forced_extension_desc:0 "第一次更张已经失败，朝廷仍要强推新学五年。到期后不再授予新政既定奖励。"',
        ' zhx_doctrine_reform_new_order:0 "新政既定"',
        ' zhx_doctrine_reform_new_order_desc:0 "新学在十年争论中站稳脚跟，朝廷与百姓逐渐适应新的治国原则。"',
        ' zhx_doctrine_reform_reversal:0 "朝令夕改"',
        ' zhx_doctrine_reform_reversal_desc:0 "朝廷迎还旧学，避免了继续动荡，却因政策反复而失去制度信用。"',
        ' zhx_doctrine_reform_indecision:0 "朝议无定"',
        ' zhx_doctrine_reform_indecision_desc:0 "公开培植的新论被中途撤回，朝廷一时难以取信于内外。"',
        ' zhx_doctrine_reform_cooldown:0 "更张余波"',
        ' zhx_doctrine_reform_cooldown_desc:0 "国家刚刚结束一次国论更张或撤议，在此修正到期前不得再次启动更张。"',
        ' zhx_doctrine_reform_cultivating:0 "正在培植新论"',
        ' zhx_doctrine_reform_transition:0 "处于新旧相攻期"',
        ' zhx_doctrine_practice:0 "国论践履"',
        ' zhx_opinion_abandoned_our_doctrine:0 "背弃旧论"',
        ' zhx_opinion_joined_our_doctrine:0 "同声相应"',
    ]
    for code, meta in SCHOOLS.items():
        lines.extend(
            [
                f' {meta["flag"]}:0 "{meta["name"]}国论"',
                f' zhx_doctrine_reform_target_{code}_requirements_tt:0 "{meta["name"]}在我国已有合格根基，并满足当前国论更张的全部条件。"',
                f' zhx_doctrine_reform.choose_{code}:0 "听取{meta["name"]}之论"',
                f' zhx_doctrine_reform.confirm_{code}.t:0 "扶植{meta["name"]}"',
                f' zhx_doctrine_reform.confirm_{code}.d:0 "{meta["summary"]}我国已经拥有相应的受邀客学或活跃学宫，可据此广开{meta["name"]}之论。五年培植期内可以撤回；一旦正式更张，便要承担十年新旧相攻。"',
                f' zhx_doctrine_reform.confirm_{code}.a:0 "广开{meta["name"]}之论"',
                f' zhx_doctrine_reform_secondary_{code}:0 "{meta["name"]}余势"',
                f' zhx_doctrine_reform_secondary_{code}_desc:0 "作为过渡性的第二学派，仅保护境内同派具名学宫；不提供主学派效果，也不提供受邀客学收益。"',
            ]
        )
    return "\n".join(lines) + "\n"


def balanced_braces(text: str, label: str) -> None:
    depth = 0
    in_string = False
    escaped = False
    in_comment = False
    for character in text:
        if in_comment:
            if character == "\n":
                in_comment = False
            continue
        if in_string:
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == '"':
                in_string = False
            continue
        if character == "#":
            in_comment = True
        elif character == '"':
            in_string = True
        elif character == "{":
            depth += 1
        elif character == "}":
            depth -= 1
            if depth < 0:
                raise ValueError(f"{label}: closing brace without opener")
    if in_string or depth:
        raise ValueError(f"{label}: unbalanced text (brace depth {depth})")


def render_all() -> dict[str, str]:
    rendered = {
        "triggers": render_triggers(),
        "effects": render_effects(),
        "modifiers": render_modifiers(),
        "secondary_modifiers": render_secondary_modifiers(),
        "opinions": render_opinions(),
        "decisions": render_decisions(),
        "events": render_events(),
        "localisation": render_localisation(),
    }
    for label, text in rendered.items():
        balanced_braces(text, label)
    return rendered


def run(check: bool) -> None:
    rendered = render_all()
    for label, path in OUTPUTS.items():
        expected = rendered[label]
        if check:
            if not path.exists() or path.read_text(encoding="utf-8-sig") != expected:
                raise ValueError(f"stale generated doctrine reform file: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    action = "checked" if check else "built"
    print(f"{action} doctrine reform state machine: schools={len(SCHOOLS)}, outputs={len(OUTPUTS)}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    run(args.check)


if __name__ == "__main__":
    main()
