#!/usr/bin/env python3
"""Manifest-driven academy directory. Presentation only; lifecycle owns actions.

ROOT/FROM on the religion GUI are the viewing country. Global site targets are
shared world indexes, never the academy authority. Every reader validates the
permanent modifier. Selected entry/scroll/ruin counts belong to the viewer.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from build_zhx_academy_lifecycle import SCHOOLS, balanced_braces
from build_zhx_academy_directory_art import SPRITES, FONTS

ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "guangdong_independent_practice"
MANIFEST = ROOT / "planning/religion_academies/academy_manifest.json"
PREFIX = "zhx_ad"
VISIBLE_ROWS = 6
HEADER = "# Generated by tools/build_zhx_academy_directory.py. Do not hand-edit.\n"


def eq(var: str, value: int) -> str:
    return (f"check_variable = {{ which = {var} value = {value} }} "
            f"NOT = {{ check_variable = {{ which = {var} value = {value + 1} }} }}")


def block(kind: str, name: str, body: str) -> str:
    return f'{kind} = {{\n    name = "{name}"\n{body}\n}}\n'


def render() -> dict[str, str]:
    manifest = json.loads(MANIFEST.read_text())
    entries = sorted(manifest["academies"], key=lambda e: list(SCHOOLS).index(e["school"]))
    if len({e["key"] for e in entries}) != len(entries):
        raise ValueError("duplicate academy key")
    last = max(0, len(entries) - VISIBLE_ROWS)
    loc: dict[str, str] = {}
    custom, dyn, effects, triggers, events = [], [], [], [], ["namespace = zhx_ad\n"]
    gui = []

    def tr(name, body):
        body = "\n".join("    " + line for line in body.splitlines())
        triggers.append(f"{name} = {{\n{body}\n}}\n")

    def eff(name, body):
        body = "\n".join(("    " + line).rstrip() for line in body.strip().splitlines())
        effects.append(f"{name} = {{\n{body}\n}}\n")

    def dt(name, cases):
        dyn.append(f"defined_text = {{\n name = {name}\n random = no\n" + "".join(
            f" text = {{ localisation_key = {key} trigger = {{ {cond} }} }}\n"
            for key, cond in cases) + "}\n")

    def bind(kind, name, potential="", body=""):
        custom.append(block(kind, name, f" potential = {{ {potential} }}\n{body}"))

    def text(name, value, x, y, width, potential="", font="zhx_ad_body", height=24, tooltip=None):
        loc[name] = value
        bind("custom_text_box", name, potential, f"tooltip = {tooltip}" if tooltip else "")
        return block("instantTextBoxType", name,
                     f' position = {{ x = {x} y = {y} }}\n font = "{font}"\n'
                     f' text = ""\n maxWidth = {width}\n maxHeight = {height}\n'
                     ' borderSize = { x = 0 y = 0 }\n format = left\n'
                     ' fixedsize = yes\n scripted = yes\n')

    def button(name, label, x, y, sprite, potential="", condition="always = yes", effect="", tip=None, font="zhx_ad_body"):
        loc[name] = label
        bind("custom_button", name, potential,
             f" trigger = {{ {condition} }}\n effect = {{ {effect} }}\n" +
             (f" tooltip = {tip}\n" if tip else ""))
        return block("guiButtonType", name,
                     f' position = {{ x = {x} y = {y} }}\n quadTextureSprite = "{sprite}"\n'
                     f' buttonText = "{name}"\n buttonFont = "{font}"\n'
                     ' clicksound = click\n scripted = yes\n')

    def icon(name, sprite, x, y, potential="", scale=1):
        bind("custom_icon", name, potential)
        return block("iconType", name,
                     f' position = {{ x = {x} y = {y} }}\n spriteType = "{sprite}"\n'
                     f' scale = {scale}\n alwaystransparent = yes\n scripted = yes\n')

    # No new mechanics, no DLC or exploration requirement added to the entry.
    tr("zhx_ad_access", "zhx_is_lijiao_country = yes\nai = no")
    loc.update({
        "zhx_ad_empty": "-", "zhx_ad_blank": "", "zhx_ad_active": "§G传承中§!",
        "zhx_ad_expelling": "§R逐学中§!", "zhx_ad_dormant": "流散中",
        "zhx_ad_missing": "暂无讲席", "zhx_ad_foreign": "外国学宫：可查看与定位。",
        "zhx_ad_synergy": "§G本派协同§!：同派多座不叠加。",
        "zhx_ad_guest": "§G宾学保护§!：不计思想张力，不授予本派协同。",
        "zhx_ad_reform": "§G改制保护§!：当前受改制规则保护，不计思想张力。",
        "zhx_ad_tension": "§R思想张力§!：按未受保护学派种类计算。",
        "zhx_ad_no_site": "暂无驻地，不能定位；悬停查看学统说明。",
        "zhx_ad_dormant_rules": "流散学统保留。天子每年有10%概率尝试另寻庇护；没有合格且愿意接纳的国家时继续流散。",
        "zhx_ad_not_active": "没有活跃讲席，暂不提供地方收益。",
        "zhx_ad_ruin_name": "[This.GetName]",
        "zhx_ad_ruins_tt": "历史遗址（非当前讲席）：",
        "zhx_ad_goto_tt": "打开学宫驻地说明，点击窗口内的原生定位按钮前往。",
        "zhx_ad_open_tt": "查看天下所有学宫的当前驻地、持有国与学统状态。",
        "zhx_ad_cancel": "返回名录", "zhx_ad_accept_expel": "确认颁布逐学令",
        "zhx_ad_accept_withdraw": "确认撤销逐学令", "zhx_ad_dismiss": "合卷",
        "zhx_ad_return_tt": "返回时保留选中学宫和滚动位置。",
    })
    eff("zhx_ad_normalize", f"""
if = {{ limit = {{ NOT = {{ has_country_flag = zhx_ad_initialized }} }}
 set_country_flag = zhx_ad_initialized
 set_variable = {{ which = zhx_ad_offset value = 0 }}
 set_variable = {{ which = zhx_ad_selected value = 1 }}
}}
if = {{ limit = {{ NOT = {{ check_variable = {{ which = zhx_ad_offset value = 0 }} }} }}
 set_variable = {{ which = zhx_ad_offset value = 0 }} }}
if = {{ limit = {{ check_variable = {{ which = zhx_ad_offset value = {last + 1} }} }}
 set_variable = {{ which = zhx_ad_offset value = {last} }} }}
if = {{ limit = {{ OR = {{
 NOT = {{ check_variable = {{ which = zhx_ad_selected value = 1 }} }}
 check_variable = {{ which = zhx_ad_selected value = {len(entries) + 1} }}
}} }} set_variable = {{ which = zhx_ad_selected value = 1 }} }}
""")
    # One world pass on open/refresh; never scan the world in GUI potentials.
    refresh = []
    for e in entries:
        k = e["key"]
        refresh += [f"clear_global_event_target = zhx_ad_site_{k}",
                    f"set_variable = {{ which = zhx_ad_ruins_{k} value = 0 }}"]
    refresh.append("every_province = {")
    for e in entries:
        k = e["key"]
        refresh += [f"if = {{ limit = {{ has_province_modifier = {e['modifier']} }} "
                    f"save_global_event_target_as = zhx_ad_site_{k} }}",
                    f"if = {{ limit = {{ has_province_modifier = zhx_academy_ruins_{k} }} "
                    f"PREV = {{ change_variable = {{ which = zhx_ad_ruins_{k} value = 1 }} }} }}"]
    refresh.append("}")
    eff("zhx_ad_refresh", "\n".join(refresh))
    # Lifecycle calls this after a move: only viewers that opened the UI need
    # their derived ruin counts refreshed; no recurring world scan is added.
    eff("zhx_ad_refresh_viewers", """every_country = {
 limit = { ai = no has_country_flag = zhx_ad_initialized }
 zhx_ad_refresh = yes
}""")
    eff("zhx_ad_open", """if = { limit = { zhx_ad_access = yes }
 zhx_ad_normalize = yes
 zhx_ad_refresh = yes
 set_country_flag = zhx_ad_visible
}""")

    gui.append(button("zhx_ad_open_button", "天下学宫", 366, 76,
                      "GFX_button_straight_148_32", "zhx_ad_access = yes", effect="hidden_effect = { zhx_ad_open = yes }", tip="zhx_ad_open_tt", font="vic_18"))
    panel = []
    bind("custom_window", "zhx_ad_panel", "zhx_ad_access = yes has_country_flag = zhx_ad_visible")
    # Inert background absorbs clicks between rows instead of selecting map
    # provinces behind the directory. Later controls retain the top hit layer.
    panel += [button("zhx_ad_background", "", 0, 0, "GFX_zhx_ad_background"),
              text("zhx_ad_title", "天下学宫", 30, 20, 230, font="zhx_ad_title", height=32),
              button("zhx_ad_close", "", 648, 15, "GFX_zhx_ad_close", effect="hidden_effect = { clr_country_flag = zhx_ad_visible }"),
              text("zhx_ad_subtitle", "讲席有迁徙，学统有传承", 31, 53, 500, font="zhx_ad_muted"),
              icon("zhx_ad_seal", "GFX_zhx_ad_seal", 564, 26),
              text("zhx_ad_seal_text", "六家", 575, 32, 38, font="zhx_ad_red")]
    for label, x, width in [("学宫", 48, 116), ("学派", 180, 55), ("当前驻地", 242, 105),
                            ("所属国", 357, 100), ("状态", 470, 90), ("定位", 580, 60)]:
        panel.append(text(f"zhx_ad_head_{x}", label, x, 88, width, font="zhx_ad_muted"))
    panel.append(icon("zhx_ad_track", "GFX_zhx_ad_track", 661, 140))
    panel.append(button("zhx_ad_up", "", 650, 113, "GFX_zhx_ad_up",
                        condition="check_variable = { which = zhx_ad_offset value = 1 }",
                        effect="hidden_effect = { subtract_variable = { which = zhx_ad_offset value = 1 } }"))
    panel.append(button("zhx_ad_down", "", 650, 312, "GFX_zhx_ad_down",
                        condition=f"NOT = {{ check_variable = {{ which = zhx_ad_offset value = {last} }} }}",
                        effect="hidden_effect = { change_variable = { which = zhx_ad_offset value = 1 } }"))
    for offset in range(last + 1):
        panel.append(icon(f"zhx_ad_thumb_{offset}", "GFX_zhx_ad_thumb", 659,
                          143 + round(140 * offset / max(last, 1)), eq("zhx_ad_offset", offset)))
        panel.append(text(f"zhx_ad_range_{offset}", f"名录 {offset+1}-{offset+VISIBLE_ROWS} / {len(entries)}", 510, 343, 140,
                          eq("zhx_ad_offset", offset), font="zhx_ad_muted"))
    panel.append(text("zhx_ad_scroll_hint", "点选讲席查看详情 · 右侧箭头翻阅", 30, 343, 460, font="zhx_ad_muted"))
    panel.append(icon("zhx_ad_detail_bg", "GFX_zhx_ad_detail", 24, 371))

    names = {"local_development_cost": "发展成本", "local_institution_spread": "思潮传播",
             "local_tax_modifier": "本地税收", "local_governing_cost": "本地治理成本",
             "local_build_cost": "本地建设成本", "local_unrest": "本地叛乱度",
             "local_manpower_modifier": "本地人力", "province_trade_power_modifier": "本地贸易力量"}
    for i, e in enumerate(entries):
        k, school = e["key"], e["school"]
        site = f"zhx_ad_site_{k}"
        live = f"zhx_ad_live_{k} = yes"
        owned = f"{live} event_target:{site} = {{ owned_by = ROOT }}"
        sel = eq("zhx_ad_selected", i + 1)
        cap = k.capitalize()
        tr(f"zhx_ad_live_{k}", f"has_saved_global_event_target = {site}\nevent_target:{site} = {{ has_province_modifier = {e['modifier']} }}")
        # Confirmation gates use authoritative ownership/protection, not cache.
        tr(f"zhx_ad_can_expel_{k}", f"""zhx_ad_access = yes
zhx_has_doctrine = yes
is_at_war = no
stability = 1
adm_power = 30
NOT = {{ has_country_modifier = zhx_academy_expulsion_campaign }}
NOT = {{ has_country_modifier = zhx_academy_expulsion_cooldown }}
zhx_academy_has_unprotected_{k} = yes""")
        tr(f"zhx_ad_can_withdraw_{k}", f"""zhx_ad_access = yes
has_country_modifier = zhx_academy_expulsion_campaign
has_country_flag = zhx_academy_expelling_{k}
any_owned_province = {{ has_province_modifier = {e['modifier']} has_province_modifier = zhx_academy_under_expulsion }}""")
        loc[f"zhx_ad_location_{k}"] = f"[{site}.GetName]"
        loc[f"zhx_ad_owner_{k}"] = f"[{site}.Owner.GetName]"
        dt(f"GetZhxAd{cap}Location", [(f"zhx_ad_location_{k}", live), ("zhx_ad_empty", "always = yes")])
        dt(f"GetZhxAd{cap}Owner", [(f"zhx_ad_owner_{k}", f"{live} event_target:{site} = {{ owner = {{ exists = yes }} }}"), ("zhx_ad_empty", "always = yes")])
        dt(f"GetZhxAd{cap}Status", [
            ("zhx_ad_expelling", f"{live} event_target:{site} = {{ has_province_modifier = zhx_academy_under_expulsion owner = {{ has_country_flag = zhx_academy_expelling_{k} has_country_modifier = zhx_academy_expulsion_campaign }} }}"),
            ("zhx_ad_active", live), ("zhx_ad_dormant", f"has_global_flag = zhx_academy_dormant_{k}"),
            ("zhx_ad_missing", "always = yes")])
        dt(f"GetZhxAd{cap}Relation", [
            ("zhx_ad_no_site", f"NOT = {{ {live} }}"),
            ("zhx_ad_foreign", f"NOT = {{ {owned} }}"),
            ("zhx_ad_synergy", f"has_country_flag = zhx_doctrine_{school}"),
            ("zhx_ad_guest", f"has_country_modifier = zhx_{school}_invited_scholar_modifier"),
            ("zhx_ad_reform", f"zhx_doctrine_reform_protects_{school}_academies = yes"),
            ("zhx_ad_tension", "always = yes")])
        bonuses = dict(manifest["common_local_effects"], **manifest["school_local_effects"][school])
        benefit = " · ".join(f"{names[key]} §G{value:+g}§!" if key == "local_unrest"
                             else f"{names[key]} §G{value * 100:+g}%§!" for key, value in bonuses.items())
        loc[f"zhx_ad_benefit_{k}"] = benefit
        loc[f"zhx_ad_future_benefit_{k}"] = "复兴后：" + benefit
        dt(f"GetZhxAd{cap}Benefit", [(f"zhx_ad_benefit_{k}", live),
            (f"zhx_ad_future_benefit_{k}", f"has_global_flag = zhx_academy_dormant_{k}"),
            ("zhx_ad_not_active", "always = yes")])
        dt(f"GetZhxAd{cap}Revival", [("zhx_ad_dormant_rules", f"NOT = {{ {live} }} has_global_flag = zhx_academy_dormant_{k}"), ("zhx_ad_blank", "always = yes")])

        # Values come from the same manifest as the actual national synergy.
        synergy_names = {"advisor_cost": "顾问花费", "stability_cost_modifier": "稳定度花费",
                         "global_autonomy": "月度自治度变化", "core_creation": "造核花费",
                         "fort_maintenance_modifier": "要塞维护费", "defensiveness": "要塞防御",
                         "global_unrest": "全国叛乱度", "war_exhaustion": "月度厌战",
                         "manpower_recovery_speed": "人力恢复速度", "army_tradition_decay": "陆军传统衰减",
                         "improve_relation_modifier": "改善关系", "diplomatic_reputation": "外交声誉"}
        flat = {"global_autonomy", "global_unrest", "war_exhaustion", "diplomatic_reputation"}
        synergy = "\\n".join(f"{synergy_names[key]}：§G{value if key in flat else value*100:+g}{'' if key in flat else '%'}§!"
                            for key, value in manifest["country_synergies"][school]["effects"].items())
        loc[f"zhx_ad_synergy_values_{k}"] = "本派学宫国家协同（不叠加）：\\n" + synergy
        dt(f"GetZhxAd{cap}Synergy", [(f"zhx_ad_synergy_values_{k}", f"{owned} has_country_flag = zhx_doctrine_{school}"),
                                    ("zhx_ad_blank", "always = yes")])

        for offset in range(last + 1):
            row = i - offset
            if not 0 <= row < VISIBLE_ROWS:
                continue
            gate, y = eq("zhx_ad_offset", offset), 115 + row * 36
            n = f"zhx_ad_row_{k}_{offset}"
            panel.append(button(n, "", 20, y, "GFX_zhx_ad_row", gate,
                                effect=f"hidden_effect = {{ set_variable = {{ which = zhx_ad_selected value = {i+1} }} }}"))
            panel.append(icon(n + "_selected", "GFX_zhx_ad_selected", 20, y, gate + " " + sel))
            panel.append(icon(n + "_emblem", f"GFX_zhx_doctrine_{school}_school", 24, y + 5, gate, .5))
            panel.append(icon(n + "_status_seal", "GFX_zhx_ad_status", 466, y + 5, gate))
            for suffix, value, x, width in [
                ("name", e["name"], 55, 120), ("school", SCHOOLS[school]["name"], 180, 58),
                ("site", f"[Root.GetZhxAd{cap}Location]", 242, 106),
                ("owner", f"[Root.GetZhxAd{cap}Owner]", 357, 106),
                ("status", f"[Root.GetZhxAd{cap}Status]", 481, 78)]:
                font = "zhx_ad_name" if suffix == "name" else "zhx_ad_body" if suffix == "status" else "zhx_ad_muted"
                element = text(n + "_" + suffix, value, x, y + (8 if suffix == "name" else 10), width, gate, font)
                # All label hit tests pass through to the row-selection button.
                panel.append(element.replace(" fixedsize = yes", " alwaystransparent = yes\n fixedsize = yes"))
            panel.append(button(n + "_goto", "定位", 575, y + 4, "GFX_zhx_ad_small_button", gate,
                                live, f"hidden_effect = {{ set_variable = {{ which = zhx_ad_selected value = {i+1} }} clr_country_flag = zhx_ad_visible country_event = {{ id = zhx_ad.{100+i} }} }}", "zhx_ad_goto_tt"))
        panel.append(text(f"zhx_ad_detail_{k}", f"{e['name']} · {SCHOOLS[school]['name']}", 38, 383, 590, sel, "zhx_ad_name", 28))
        panel.append(text(f"zhx_ad_detail_place_{k}", f"驻地：[Root.GetZhxAd{cap}Location]    所属国：[Root.GetZhxAd{cap}Owner]", 38, 499, 612, sel, "zhx_ad_muted", 22))
        panel.append(text(f"zhx_ad_detail_benefit_{k}", f"[Root.GetZhxAd{cap}Benefit]", 38, 450, 612, sel, height=44))
        panel.append(text(f"zhx_ad_detail_relation_{k}", f"[Root.GetZhxAd{cap}Relation]", 38, 417, 612, sel, height=28,
                          tooltip=f"zhx_ad_revival_{k}"))
        loc[f"zhx_ad_revival_{k}"] = f"[Root.GetZhxAd{cap}Relation]\\n[Root.GetZhxAd{cap}Synergy][Root.GetZhxAd{cap}Revival]"
        # Tooltip-only effect: no writes, not a second action or history cache.
        panel.append(button(f"zhx_ad_ruins_button_{k}", "遗址", 38, 532, "GFX_zhx_ad_small_button", sel,
                            effect=f"every_province = {{ limit = {{ has_province_modifier = zhx_academy_ruins_{k} }} custom_tooltip = zhx_ad_ruin_name }}", tip="zhx_ad_ruins_tt"))
        panel.append(text(f"zhx_ad_ruins_count_{k}", f"共 [Root.zhx_ad_ruins_{k}.GetValue] 处", 116, 539, 130, sel, "zhx_ad_muted"))
        panel.append(button(f"zhx_ad_expel_{k}", "颁布逐学令", 328, 532, "GFX_zhx_ad_action_button", sel + " " + owned,
                            f"zhx_ad_can_expel_{k} = yes", f"hidden_effect = {{ country_event = {{ id = zhx_ad.{200+i} }} }}", "zhx_academy_issue_expulsion_tt"))
        panel.append(button(f"zhx_ad_withdraw_{k}", "撤销逐学令", 492, 532, "GFX_zhx_ad_action_button", sel + " " + owned,
                            f"zhx_ad_can_withdraw_{k} = yes", f"hidden_effect = {{ country_event = {{ id = zhx_ad.{300+i} }} }}", "zhx_academy_withdraw_expulsion_tt"))

        # Per-key events freeze identity even if selection changes while open.
        loc[f"zhx_ad_goto_{k}_title"] = e["name"] + "驻地"
        loc[f"zhx_ad_goto_{k}_desc"] = ("当前讲席位于§Y[zhx_ad_goto_province.GetName]§!，由§Y[zhx_ad_goto_province.Owner.GetName]§!持有。\\n\\n点击本窗口的原生定位按钮前往省份。")
        # EU4 1.37.5 CEvent::GetGoToProvince only reads event-local saved
        # targets, unlike scripted event_target scopes which also read globals.
        # Snapshot the validated world index inside each opened event. Reusing
        # this local name does not let another viewer overwrite its destination.
        events.append(f"""country_event = {{
 id = zhx_ad.{100+i}
 title = zhx_ad_goto_{k}_title
 desc = zhx_ad_goto_{k}_desc
 picture = DIPLOMACY_eventPicture
 goto = zhx_ad_goto_province
 is_triggered_only = yes
 trigger = {{ zhx_ad_access = yes {live} }}
 immediate = {{
  if = {{ limit = {{ {live} }}
   event_target:{site} = {{ save_event_target_as = zhx_ad_goto_province }}
  }}
 }}
 option = {{ name = zhx_ad_cancel hidden_effect = {{ zhx_ad_open = yes }} }}
 option = {{ name = zhx_ad_dismiss }}
}}""")
        for action, number, condition, execute, tip in [
            ("expel", 200+i, f"zhx_ad_can_expel_{k}", f"zhx_academy_begin_expulsion_{k}", "zhx_academy_issue_expulsion_tt"),
            ("withdraw", 300+i, f"zhx_ad_can_withdraw_{k}", "zhx_academy_withdraw_current_expulsion", "zhx_academy_withdraw_expulsion_tt")]:
            loc[f"zhx_ad_{action}_{k}_title"] = ("颁布逐学令：" if action == "expel" else "撤销逐学令：") + e["name"]
            loc[f"zhx_ad_{action}_{k}_desc"] = (f"本次操作对象为§Y{e['name']}§!。确认时将再次检查其当前归属和操作资格。\\n\\n" +
                ("花费30行政点、1稳定度与5威望。三年逐学期间承受国家与地方代价，并引起相关列国不满。" if action == "expel" else "终止本次逐学，保留原址讲席；此后十年不能再次颁布逐学令。"))
            events.append(f"""country_event = {{
 id = zhx_ad.{number}
 title = zhx_ad_{action}_{k}_title
 desc = zhx_ad_{action}_{k}_desc
 picture = DIPLOMACY_eventPicture
 is_triggered_only = yes
 trigger = {{ {condition} = yes }}
 option = {{ name = zhx_ad_accept_{action}
  trigger = {{ {condition} = yes }}
  custom_tooltip = {tip}
  hidden_effect = {{ if = {{ limit = {{ {condition} = yes }} {execute} = yes }} zhx_ad_refresh = yes }}
 }}
 option = {{ name = zhx_ad_cancel hidden_effect = {{ zhx_ad_open = yes }} }}
}}""")

    gui.append(block("windowType", "zhx_ad_panel", ' position = { x = 535 y = 0 }\n size = { x = 690 y = 580 }\n moveable = 0\n scripted = yes\n' + "\n".join(panel)))
    gfx = []
    for name, (_, _, kind) in SPRITES.items():
        gfx.append(block(kind, f"GFX_zhx_ad_{name}",
                         f' texturefile = "gfx/interface/zhx_academy_directory/{name}.dds"'))
    fonts = []
    for name, (size, color) in FONTS.items():
        fonts.append(block("bitmapfont", f"zhx_ad_{name}",
            f' path = "gfx/fonts/zh-hans-{size}"\n color = 0xff{color}\n'
            ' textcolors = { G = { 123 185 134 } R = { 224 128 105 } Y = { 220 192 120 } }'))
    return {
        "common/custom_gui/zhx_academy_directory.txt": HEADER + "\n".join(custom),
        "common/scripted_triggers/zhx_academy_directory.txt": HEADER + "\n".join(triggers),
        "common/scripted_effects/zhx_academy_directory.txt": HEADER + "\n".join(effects),
        "events/zhx_academy_directory.txt": HEADER + "\n".join(events),
        "customizable_localization/zhx_academy_directory.txt": HEADER + "\n".join(dyn),
        "localisation_source/zhx_academy_directory_readable_utf8.txt": 'l_english:\n' + "\n".join(f' {k}:0 "{v}"' for k, v in loc.items()) + "\n",
        "interface/zhx_academy_directory.gfx": HEADER + "spriteTypes = {\n" + "\n".join(gfx) + "}\nbitmapfonts = {\n" + "\n".join(fonts) + "}\n",
        # Included by the pinned religion-view builder, not loaded as a root.
        "directory_gui_fragment": "\n".join(gui),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for relative, content in render().items():
        if relative == "directory_gui_fragment":
            continue
        if not relative.startswith("localisation_source/"):
            balanced_braces(content, relative)
        path = MOD / relative
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"stale: {relative}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    print("academy directory: " + ("checked" if args.check else "built"))


if __name__ == "__main__":
    main()
