#!/usr/bin/env python3
"""Generate the same deterministic score for the diplomacy reasons and AI pulse.

Source is the approved rules here. No random acceptance and no persistent score cache.
"""
from pathlib import Path
import argparse
ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / 'guangdong_independent_practice'
HOST = 'event_target:zhx_tianzi'
# Conditions run in recipient scope, including when exported by native acceptance.
RULES = [
    ('base', -20, None, '基础意愿'),
    ('defensive', 30, f'{HOST} = {{ is_in_war = {{ defender_leader = THIS }} }}', '天子领导防御战争'),
    ('manpower_low', -30, 'NOT = { manpower_percentage = 0.25 }', '人力不足四分之一'),
    ('manpower_mid', -15, 'manpower_percentage = 0.25 NOT = { manpower_percentage = 0.5 }', '人力不足一半'),
    ('loans_low', -10, 'num_of_loans = 1 NOT = { num_of_loans = 5 }', '一至四笔贷款'),
    ('loans_high', -30, 'num_of_loans = 5', '至少五笔贷款'),
    ('war_burden', -1000, f'OR = {{ is_at_war = yes {HOST} = {{ NOT = {{ zhx_qn_single_war = yes }} }} }}', '天子多线作战或诸侯已经在战'),
    ('truce', -1000, f'any_country = {{ war_with = {HOST} zhx_qn_enemy_leader = {{ host = {HOST} }} truce_with = PREV }}', '与敌方战争领袖有停战'),
    ('alliance', -1000, f'any_country = {{ war_with = {HOST} zhx_qn_enemy_leader = {{ host = {HOST} }} alliance_with = PREV }}', '与敌方战争领袖结盟'),
]

def localize_variables(lines):
    # EU4 only permits arithmetic writes to names registered in the local pool.
    # Register every scratch name with a supported native export before overwriting.
    import re
    targets=set(re.findall(r'which = (zhx_\w+|ai_value)', '\n'.join(lines)))
    exported=set(re.findall(r'variable_name = (\w+)', '\n'.join(lines)))
    return [f'export_to_variable = {{ variable_name = {name} value = trigger_value:num_of_cities }}' for name in sorted(targets-exported)] + lines

def numeric(var, who):
    operations = [
        f'export_to_variable = {{ variable_name = {var}_opinion value = opinion who = {who} with = {HOST} }}',
        f'divide_variable = {{ which = {var}_opinion value = 5 }}',
        f'export_to_variable = {{ variable_name = {var}_trust value = trust who = {who} with = {HOST} }}',
        f'subtract_variable = {{ which = {var}_trust value = 50 }}',
        f'divide_variable = {{ which = {var}_trust value = 2 }}',
    ]
    # Native CScriptedAIAcceptance::CalcValue truncates EACH component toward zero.
    # round_variable mode <0 floors, >0 ceils: use the opposite sign of the value.
    for suffix in ('opinion', 'trust'):
        operations += [
            f'set_variable = {{ which = zhx_qn_round_direction which = {var}_{suffix} }}',
            'multiply_variable = { which = zhx_qn_round_direction value = -1 }',
            f'round_variable = {{ which = {var}_{suffix} which = zhx_qn_round_direction }}',
        ]
    return [line.replace(' who = THIS','') for line in operations]

def generated():
    helpers = ['# Generated by tools/build_zhx_qinwang_score.py; recipient scope.']
    entries = []
    for key, weight, cond, _ in RULES:
        if cond:
            helpers.append(f'zhx_qn_score_{key} = {{ {cond} }}')
        limit = f'limit = {{ FROM = {{ zhx_qn_score_{key} = yes }} }}' if cond else ''
        entries.append(f'    add_entry = {{ name = zhx_qn_reason_{key} {limit} export_to_variable = {{ variable_name = ai_value value = trigger_value:num_of_cities }} set_variable = {{ which = ai_value value = {weight} }} }}')
    helpers.append('zhx_qn_ai_positive = { zhx_qn_sum_signed = { divisor = 1 modulus = 10000 threshold = 1 } }')
    for key, divisor in [('opinion',5),('trust',2)]:
        calc=f'export_to_variable = {{ variable_name = ai_value value = {key} who = FROM with = {HOST} }}'
        if key=='trust': calc+='\n        subtract_variable = { which = ai_value value = 50 }'
        calc+=f'\n        divide_variable = {{ which = ai_value value = {divisor} }}'
        entries.append('    add_entry = {\n        name = zhx_qn_reason_'+key+'\n        '+calc+'\n    }')
    action='''# ROOT = Tianzi, FROM = recipient. Immediate submission captures the campaign
# BEFORE player consent (event .10); the native action itself is the invitation.
# Live customizable localization presents the score directly on this row.
# Keep immediate dispatch: enabling native consent would lose send-time snapshots.
zhx_invite_qinwang = {
    category = is_emperor_of_china
    require_acceptance = no
    is_visible = {
        has_global_flag = zhx_system_initialised_v14
        zhx_is_tianzi = yes
        is_subject = no
        FROM = { is_subject = no zhx_is_tianxia_member = yes NOT = { zhx_is_tianzi = yes } }
    }
    is_allowed = {
        # Show only unmet hard requirements; live score breakdown is in _tooltip.
        if = {
            limit = { NOT = { zhx_qn_single_war = yes } }
            custom_trigger_tooltip = { tooltip = zhx_qn_single_war_tt zhx_qn_single_war = yes }
        }
        if = {
            limit = { NOT = { FROM = { is_at_war = no is_subject = no } } }
            custom_trigger_tooltip = { tooltip = zhx_qn_peace_tt FROM = { is_at_war = no is_subject = no } }
        }
        if = {
            limit = { NOT = { FROM = { owes_favors = { who = ROOT value = 25 } } } }
            custom_trigger_tooltip = { tooltip = zhx_qn_favors_tt FROM = { owes_favors = { who = ROOT value = 25 } } }
        }
        if = {
            limit = { NOT = { FROM = { NOT = { has_country_flag = zhx_qn_sent } NOT = { has_country_flag = zhx_qn_pending } NOT = { has_country_flag = zhx_qn_joining } } } }
            custom_trigger_tooltip = { tooltip = zhx_qn_once_tt FROM = { NOT = { has_country_flag = zhx_qn_sent } NOT = { has_country_flag = zhx_qn_pending } NOT = { has_country_flag = zhx_qn_joining } } }
        }
        if = {
            limit = { NOT = { OR = { NOT = { has_global_flag = zhx_qn_active } zhx_qn_original_war = yes } } }
            custom_trigger_tooltip = { tooltip = zhx_qn_campaign_tt OR = { NOT = { has_global_flag = zhx_qn_active } zhx_qn_original_war = yes } }
        }
        if = {
            limit = { NOT = { FROM = { OR = { ai = no zhx_qn_ai_positive = yes } } } }
            custom_trigger_tooltip = { tooltip = zhx_qn_positive_tt FROM = { OR = { ai = no zhx_qn_ai_positive = yes } } }
        }
    }
    on_accept = {
        custom_tooltip = zhx_qn_sent_tt
        hidden_effect = { if = { limit = { zhx_is_tianzi = yes } FROM = { zhx_qn_dispatch = yes } } }
    }
    on_decline = { }
    ai_will_do = { always = no }
}
# Hidden legacy definition retained as a native arithmetic regression reference.
# Never show a second score row to the player.
zhx_qinwang_willingness = {
    category = is_emperor_of_china
    require_acceptance = yes
    is_visible = { always = no }
    is_allowed = { custom_trigger_tooltip = { tooltip = zhx_qn_assessment_tt always = no } }
    on_accept = { }
    on_decline = { }
    ai_will_do = { always = no }
    ai_acceptance = {
'''+ '\n'.join(entries)+ '\n    }\n}\n'
    return {'common/scripted_triggers/zhx_qinwang_score_triggers.txt':'\n'.join(helpers)+'\n','common/new_diplomatic_actions/zhx_qinwang_actions.txt':action}

def main():
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
    for rel, content in generated().items():
        path=MOD/rel
        if a.check:
            assert path.read_text()==content, f'Stale generated file: {path}'
        else: path.write_text(content)
    print('Qinwang shared score: '+('verified' if a.check else 'generated'))
if __name__=='__main__': main()
