#!/usr/bin/env python3
"""Build the read-only guide from reviewed prose and original generated paintings."""
from pathlib import Path
import argparse
import io
import json
import re
import math
import unicodedata
from PIL import Image, ImageDraw
from encode_eu4_chinese_localisation import to_escaped_bytes, escaped_bytes_to_utf8

ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / 'guangdong_independent_practice'
MANIFEST = ROOT / 'planning/mod_guide/guide_manifest.json'
# Scope conditions only affect the applicability sentence, never page availability.
STATUS = {
 'all': ('always = yes', '所有国家均可阅读；本册不执行政务操作。', '所有国家均可阅读。'),
 'tianxia': ('zhx_is_tianxia_polity = yes', '本国属于周天下；具体行动仍须满足当时条件。', '本国不属于周天下；可阅读规则，入列后方享成员权利。'),
 'worldcourt': ('zhx_is_tianxia_polity = yes', '本国属于周天下；适用政体以政府页当前改革为准。', '本国在周天下之外；以下制度可供了解，不能直接套用。'),
 'feudatory': ('zhx_feudatory_has_reform = yes', '本国采用普通诸侯爵制；请封仍须满足对应门槛。', '本国未采用普通子、伯、侯、公改革；本页晋封入口暂不适用。'),
 'tianzi': ('zhx_is_tianzi = yes', '本国为当前天子；改革收益须由实际政府改革提供。', '本国不是当前天子；本页介绍天子专属制度。'),
 'gongyi': ('has_reform = zhx_gongyi_reform', '本国采用公邑改革，须守一省边界。', '本国未采用公邑改革；申请须满足本页全部资格。'),
 'yang': ('has_reform = zhx_yang_trade_league_reform', '本国采用扬国商盟改革。', '本国未采用扬国商盟改革；以下为该专属政体规则。'),
 'republics': ('OR = { has_reform = gdd_czc_council_reform has_reform = gdd_hak_revolutionary_army_reform has_reform = gdd_hak_communal_republic_reform }', '本国采用本页介绍的一种专属共和国改革。', '本国未采用这几种专属共和国改革；内容可供了解。'),
 'lijiao': ('zhx_is_lijiao_country = yes', '本国适用礼教机制；各项操作另有资格与冷却。', '本国当前不适用礼教国论机制；仍可查阅全部规则。'),
 'academy': ('zhx_is_lijiao_country = yes', '本国为礼教国；持有学宫时计算地方收益、协同与张力。', '本国非礼教国；持有学宫仍有地方收益，无礼教协同与张力。'),
}

def plain_text(text):
 return re.sub(r'§[YBGR!]', '', text)


def markdown_body(text):
 lines=[]
 for line in text.split('\n'):
  if line.startswith('§Y'):
   lines.append('\n### '+plain_text(line)+'\n')
  elif line.startswith('• '):
   # Markdown keeps explicit list structure; HTML preview carries actual colours.
   value=re.sub(r'§[YBGR](.*?)§!', r'**\1**', line[2:])
   lines.append('- '+value)
  else:lines.append(plain_text(line))
 return '\n'.join(lines)


def estimated_display_lines(text, columns=28):
 # Conservative content budget; native font/UI-scale layout still needs a game check.
 return sum(max(1, math.ceil(sum(1 if unicodedata.east_asian_width(c) in 'WF' else .55
     for c in plain_text(line)) / columns)) for line in text.split('\n'))


def render():
 data = json.loads(MANIFEST.read_text())
 pages = {p['key']: p for p in data['pages']}
 out = {}; loc = {}; events = ['# Generated by tools/build_mod_guide.py\nnamespace = zhx_guide\n']
 loc.update(zhx_mod_guide_title='模组介绍', zhx_mod_guide_desc='查阅周天下、朝廷、礼教与学宫的分类介绍。可反复打开，不花费资源。', zhx_mod_guide_open_tt='打开分类目录，自由选读。', zhx_mod_guide_available_tt='先结束当前介绍或开局背景，再重新打开。', zhx_guide_close='合卷，日后再读', zhx_guide_home='返回总目录')
 startup_page = dict(pages['home'], key='startup', event_id='zhx_guide.0')
 for p in [*pages.values(), startup_page]:
  trigger = 'ai = no'
  if p['key'] == 'startup':
   trigger += '\n        NOT = { has_country_flag = zhx_startup_overview_seen }\n        NOT = { has_country_flag = zhx_opening_background_pending }\n        NOT = { zhx_should_show_opening_background = yes }'
  eid=p['event_id']; loc[eid+'.t']=p['title']
  loc[eid+'.d']='[Root.GetZhxGuideStatus'+p['status'].title()+']\n\n'+p['body']
  events.append(f'''\ncountry_event = {{
    id = {eid}
    title = {eid}.t
    desc = {eid}.d
    picture = zhx_guide_{p['category']}_eventPicture
    is_triggered_only = yes
    trigger = {{ {trigger} }}
    immediate = {{ set_country_flag = zhx_mod_guide_open set_country_flag = zhx_startup_overview_seen }}
''')
  nav=list(p['links'])
  if p['parent']:
   nav.append(dict(label=('返回总目录' if p['parent']=='home' else '返回：'+pages[p['parent']]['title']),target=p['parent']))
  if p['parent'] not in (None, 'home') and len(nav) < 5:
   nav.append(dict(label='返回总目录',target='home'))
  for i,link in enumerate(nav):
   key=f'{eid}.o{i}';loc[key]=link['label'];target=pages[link['target']]['event_id']
   events.append(f'''    option = {{
        name = {key}
        hidden_effect = {{ country_event = {{ id = {target} }} }}
    }}
''')
  events.append('    option = { name = zhx_guide_close hidden_effect = { clr_country_flag = zhx_mod_guide_open } }\n}\n')
 out[MOD/'events/zhx_mod_guide_events.txt']=''.join(events).encode()
 custom=[]
 for key,(trigger,yes,no) in STATUS.items():
  loc['zhx_guide_status_'+key+'_yes']='§Y本国适用§!：'+yes
  loc['zhx_guide_status_'+key+'_no']='§Y适用说明§!：'+no
  custom.append(f'''defined_text = {{
    name = GetZhxGuideStatus{key.title()}
    text = {{ localisation_key = zhx_guide_status_{key}_yes trigger = {{ {trigger} }} }}
    text = {{ localisation_key = zhx_guide_status_{key}_no trigger = {{ always = yes }} }}
}}
''')
 out[MOD/'customizable_localization/zhx_mod_guide_localization.txt']=''.join(custom).encode()
 out[MOD/'common/scripted_effects/zhx_mod_guide_effects.txt']=b'''# Open from a player action without advancing the game date.
zhx_open_mod_guide = {
    if = {
        limit = {
            ai = no
            NOT = { has_country_flag = zhx_mod_guide_open }
            NOT = { has_country_flag = zhx_opening_background_pending }
        }
        set_country_flag = zhx_mod_guide_open
        country_event = { id = zhx_guide.1 }
    }
}
'''
 out[MOD/'decisions/zhx_mod_guide_decisions.txt']=b'''# A permanent, all-human-country reader; no faith, culture or discovery gate.
country_decisions = {
    zhx_mod_guide = {
        major = yes
        potential = { ai = no }
        allow = {
            custom_trigger_tooltip = {
                tooltip = zhx_mod_guide_available_tt
                NOT = { has_country_flag = zhx_mod_guide_open }
                NOT = { has_country_flag = zhx_opening_background_pending }
            }
        }
        effect = {
            custom_tooltip = zhx_mod_guide_open_tt
            hidden_effect = { zhx_open_mod_guide = yes }
        }
        ai_will_do = { factor = 0 }
    }
}
'''
 gfx=['spriteTypes = {\n'];thumbs=[]
 for cat,art in data['art'].items():
  sprite=f'zhx_guide_{cat}_eventPicture';texture=f'gfx/event_pictures/zhx_guide/{sprite}.dds'
  gfx.append(f'    spriteType = {{ name = "{sprite}" texturefile = "{texture}" alwaystransparent = yes }}\n')
  with Image.open(ROOT/art['source_image']) as im:
   w,h=im.size;crop_h=round(w*132/512);top=art['crop_top'];assert 0<=top<=h-crop_h,(cat,im.size,top,crop_h)
   thumb=im.crop((0,top,w,top+crop_h)).resize((512,132),Image.Resampling.LANCZOS).convert('RGBA');thumb.putalpha(255)
   buf=io.BytesIO();thumb.save(buf,format='DDS');out[MOD/texture]=buf.getvalue()
   buf=io.BytesIO();thumb.save(buf,format='PNG');out[ROOT/f'planning/mod_guide/{cat}_event_preview.png']=buf.getvalue();thumbs.append((cat,thumb))
 gfx.append('}\n');out[MOD/'interface/zhx_mod_guide_eventpictures.gfx']=''.join(gfx).encode()
 source='l_english:\n'
 for key,val in loc.items():
  assert '"' not in val and '\\' not in val,key
  source+=f' {key}:0 "'+val.replace('\n','\\n')+'"\n'
 out[MOD/'localisation_source/027_zhx_mod_guide_readable_utf8.txt']=source.encode()
 out[MOD/'localisation/replace/027_zhx_mod_guide_l_english.yml']=escaped_bytes_to_utf8(to_escaped_bytes(source))
 md=['# 模组分类介绍：游戏内文案与配图\n\n生成自 `planning/mod_guide/guide_manifest.json`。各页均可按需阅读；以下为制作预览，不是游戏截图。\n\n']
 for p in pages.values():
  md.append(f"## {p['title']}\n\n")
  if p['key'] in ('world','court','religion','academy'):
   md.append(f"![{p['title']}]({p['category']}_event_preview.png)\n\n")
  md.append(f"适用提示：{STATUS[p['status']][1]} / {STATUS[p['status']][2]}\n\n{markdown_body(p['body'])}\n\n")
  if p['links']: md.append('可选：'+'；'.join(x['label'] for x in p['links'])+'。\n\n')
  md.append('返回：'+(pages[p['parent']]['title'] if p['parent'] else '无（总目录）')+'；随时合卷。\n\n')
 out[ROOT/'planning/mod_guide/模组分类介绍_图文预览.md']=''.join(md).encode()
 from render_mod_guide_preview import render_html
 out[ROOT/'planning/mod_guide/模组分类介绍_彩色预览.html']=render_html(data, STATUS)
 canvas=Image.new('RGB',(536,4*164+12),'#252722');draw=ImageDraw.Draw(canvas)
 for i,(cat,im) in enumerate(thumbs):draw.text((12,12+i*164),cat,fill='#ddd0ac');canvas.paste(im,(12,32+i*164))
 buf=io.BytesIO();canvas.save(buf,format='PNG');out[ROOT/'planning/mod_guide/分类事件横幅预览.png']=buf.getvalue()
 return out

def main():
 parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
 outputs=render();bad=[]
 for path,blob in outputs.items():
  if args.check:
   if not path.exists() or path.read_bytes()!=blob:bad.append(str(path.relative_to(ROOT)))
  else:path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(blob)
 if bad:raise SystemExit('Out of date:\n'+'\n'.join(bad))
 print(('PASS reproducible' if args.check else 'Built')+f': {len(outputs)} guide outputs')
if __name__=='__main__':main()
