#!/usr/bin/env python3
"""Build the first playable lifecycle for the twelve named ZHX academies.

The province's unique permanent modifier remains the sole authority for an
active academy.  Global dormant flags exist only while that modifier is absent
from the map; every other flag/modifier generated here is disposable process
or presentation state.
"""

from __future__ import annotations

import argparse
import json
from itertools import combinations
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "guangdong_independent_practice"
MANIFEST = ROOT / "planning/religion_academies/academy_manifest.json"

SCHOOLS = {
    "ru": {
        "name": "儒家",
        "flag": "zhx_doctrine_ru",
        "invited": "zhx_ru_invited_scholar_modifier",
    },
    "fa": {
        "name": "法家",
        "flag": "zhx_doctrine_fa",
        "invited": "zhx_fa_invited_scholar_modifier",
    },
    "mo": {
        "name": "墨家",
        "flag": "zhx_doctrine_mo",
        "invited": "zhx_mo_invited_scholar_modifier",
    },
    "dao": {
        "name": "道家",
        "flag": "zhx_doctrine_dao",
        "invited": "zhx_dao_invited_scholar_modifier",
    },
    "bing": {
        "name": "兵家",
        "flag": "zhx_doctrine_bing",
        "invited": "zhx_bing_invited_scholar_modifier",
    },
    "zongheng": {
        "name": "纵横家",
        "flag": "zhx_doctrine_zongheng",
        "invited": "zhx_zongheng_invited_scholar_modifier",
    },
}

OUTPUTS = {
    "triggers": MOD / "common/scripted_triggers/zhx_academy_lifecycle_triggers.txt",
    "effects": MOD / "common/scripted_effects/zhx_academy_lifecycle_effects.txt",
    "modifiers": MOD / "common/event_modifiers/zhx_academy_lifecycle_modifiers.txt",
    "opinions": MOD / "common/opinion_modifiers/zhx_academy_opinions.txt",
    "decisions": MOD / "decisions/zhx_academy_decisions.txt",
    "events": MOD / "events/zhx_academy_lifecycle_events.txt",
    "localisation": MOD / "localisation_source/zhx_academy_lifecycle_readable_utf8.txt",
}


def indent(text: str, spaces: int = 4) -> str:
    prefix = " " * spaces
    return "\n".join(prefix + line if line else line for line in text.splitlines())


def load_academies() -> list[dict[str, object]]:
    payload = json.loads(MANIFEST.read_text(encoding="utf-8"))
    academies = payload["academies"]
    if len(academies) != 12:
        raise ValueError(f"expected 12 opening academies, found {len(academies)}")
    keys = [str(entry["key"]) for entry in academies]
    modifiers = [str(entry["modifier"]) for entry in academies]
    if len(set(keys)) != len(keys) or len(set(modifiers)) != len(modifiers):
        raise ValueError("academy keys and active modifiers must be unique")
    unknown = sorted({str(entry["school"]) for entry in academies} - set(SCHOOLS))
    if unknown:
        raise ValueError(f"unknown academy schools: {', '.join(unknown)}")
    return academies


def or_block(lines: list[str], level: int = 0) -> str:
    pad = " " * level
    inner = "\n".join(f"{pad}    {line}" for line in lines)
    return f"{pad}OR = {{\n{inner}\n{pad}}}"


def protection_trigger(school: str) -> str:
    meta = SCHOOLS[school]
    return (
        "OR = {\n"
        f"    has_country_flag = {meta['flag']}\n"
        f"    has_country_modifier = {meta['invited']}\n"
        f"    zhx_doctrine_reform_protects_{school}_academies = yes\n"
        "}"
    )


def candidate_limit(school: str, tier: str, *, refugee: bool) -> str:
    meta = SCHOOLS[school]
    lines = [
        "exists = yes",
        "zhx_is_lijiao_country = yes",
        "zhx_academy_has_empty_host_province = yes",
        "NOT = { has_country_flag = zhx_academy_refuge_offer_pending }",
    ]
    if refugee:
        lines.append("NOT = { tag = event_target:zhx_academy_expeller }")
    if tier == "main":
        lines.append(f"has_country_flag = {meta['flag']}")
    elif tier == "invited":
        lines.append(f"has_country_modifier = {meta['invited']}")
    elif tier == "friendly":
        lines.append(
            "has_opinion = { who = event_target:zhx_academy_expeller value = 50 }"
        )
    elif tier != "any":
        raise ValueError(tier)
    return "\n".join(lines)


def render_triggers(academies: list[dict[str, object]]) -> str:
    active = [f"has_province_modifier = {entry['modifier']}" for entry in academies]
    ruins = [
        f"has_province_modifier = zhx_academy_ruins_{entry['key']}"
        for entry in academies
    ]
    sections = [
        "# Generated by tools/build_zhx_academy_lifecycle.py. Do not hand-edit.",
        "# Active academy truth is the unique permanent province modifier.",
        "",
        "zhx_academy_is_active_province = {\n"
        + indent(or_block(active), 4)
        + "\n}",
        "",
        "zhx_academy_is_former_site = {\n"
        + indent(or_block(ruins), 4)
        + "\n}",
        "",
        "zhx_academy_is_empty_host_province = {\n"
        "    is_city = yes\n"
        "    NOT = { zhx_academy_is_active_province = yes }\n"
        "    NOT = { zhx_academy_is_former_site = yes }\n"
        "    NOT = { has_province_modifier = zhx_academy_under_expulsion }\n"
        "}",
        "",
        "zhx_academy_has_empty_host_province = {\n"
        "    any_owned_province = { zhx_academy_is_empty_host_province = yes }\n"
        "}",
    ]

    for entry in academies:
        key = entry["key"]
        school = str(entry["school"])
        sections.extend(
            [
                "",
                f"zhx_academy_has_unprotected_{key} = {{\n"
                f"    any_owned_province = {{ has_province_modifier = {entry['modifier']} }}\n"
                f"    NOT = {{ has_country_flag = {SCHOOLS[school]['flag']} }}\n"
                f"    NOT = {{ has_country_modifier = {SCHOOLS[school]['invited']} }}\n"
                f"    NOT = {{ zhx_doctrine_reform_protects_{school}_academies = yes }}\n"
                "}",
            ]
        )

    unprotected_province_lines = []
    for entry in academies:
        school = str(entry["school"])
        unprotected_province_lines.append(
            "AND = { "
            f"has_province_modifier = {entry['modifier']} "
            "owner = { "
            f"NOT = {{ has_country_flag = {SCHOOLS[school]['flag']} }} "
            f"NOT = {{ has_country_modifier = {SCHOOLS[school]['invited']} }} "
            f"NOT = {{ zhx_doctrine_reform_protects_{school}_academies = yes }} "
            "} }"
        )
    sections.extend(
        [
            "",
            "zhx_academy_is_unprotected_active_province = {\n"
            + indent(or_block(unprotected_province_lines), 4)
            + "\n}",
            "",
            "zhx_academy_has_any_unprotected = {\n"
            "    any_owned_province = { zhx_academy_is_unprotected_active_province = yes }\n"
            "}",
        ]
    )

    pair_lines = [
        "AND = { "
        f"zhx_has_unprotected_{left}_academy = yes "
        f"zhx_has_unprotected_{right}_academy = yes "
        "}"
        for left, right in combinations(SCHOOLS, 2)
    ]
    sections.extend(
        [
            "",
            "zhx_academy_has_two_unprotected_school_types = {\n"
            + indent(or_block(pair_lines), 4)
            + "\n}",
            "",
            "zhx_academy_has_any_dormant = {\n"
            + indent(
                or_block(
                    [
                        f"has_global_flag = zhx_academy_dormant_{entry['key']}"
                        for entry in academies
                    ]
                ),
                4,
            )
            + "\n}",
        ]
    )
    return "\n".join(sections) + "\n"


def render_modifiers(academies: list[dict[str, object]]) -> str:
    lines = [
        "# Generated by tools/build_zhx_academy_lifecycle.py. Do not hand-edit.",
        "",
        "zhx_academy_expulsion_campaign = {",
        "    global_unrest = 0.5",
        "    stability_cost_modifier = 0.05",
        "}",
        "",
        "zhx_academy_under_expulsion = {",
        "    local_unrest = 3",
        "    local_development_cost = 0.05",
        "    local_institution_spread = -0.10",
        "    local_tax_modifier = -0.05",
        "    local_production_efficiency = -0.05",
        "    local_manpower_modifier = -0.05",
        "}",
        "",
        "zhx_academy_expulsion_cooldown = { }",
    ]
    for entry in academies:
        lines.extend(
            [
                "",
                f"zhx_academy_ruins_{entry['key']} = {{",
                "    local_institution_spread = 0.05",
                "}",
            ]
        )
    return "\n".join(lines) + "\n"


def render_opinions() -> str:
    return """# Generated by tools/build_zhx_academy_lifecycle.py. Do not hand-edit.

zhx_opinion_expelled_our_school = {
    opinion = -50
    yearly_decay = 2
}
"""


def outrage_effect(school: str) -> str:
    meta = SCHOOLS[school]
    return f"""zhx_academy_outrage_{school} = {{
    every_country = {{
        limit = {{
            exists = yes
            NOT = {{ tag = ROOT }}
            zhx_is_lijiao_country = yes
            OR = {{
                has_country_flag = {meta['flag']}
                has_country_modifier = {meta['invited']}
            }}
        }}
        add_opinion = {{
            who = ROOT
            modifier = zhx_opinion_expelled_our_school
        }}
        add_aggressive_expansion = {{
            who = ROOT
            value = 10
            apply_calc = no
        }}
    }}
}}"""


def start_effect(entry: dict[str, object]) -> str:
    key = entry["key"]
    return f"""zhx_academy_begin_expulsion_{key} = {{
    if = {{
        limit = {{
            is_at_war = no
            stability = 1
            adm_power = 30
            NOT = {{ has_country_modifier = zhx_academy_expulsion_campaign }}
            NOT = {{ has_country_modifier = zhx_academy_expulsion_cooldown }}
            zhx_academy_has_unprotected_{key} = yes
        }}
        add_adm_power = -30
        add_stability = -1
        add_prestige = -5
        add_country_modifier = {{
            name = zhx_academy_expulsion_campaign
            duration = 1100
        }}
        set_country_flag = zhx_academy_expelling_{key}
        random_owned_province = {{
            limit = {{ has_province_modifier = {entry['modifier']} }}
            add_province_modifier = {{
                name = zhx_academy_under_expulsion
                duration = 1100
            }}
            province_event = {{ id = zhx_academy.200 days = 1095 }}
        }}
        zhx_academy_outrage_{entry['school']} = yes
        zhx_refresh_academy_country_effects = yes
    }}
}}"""


def offer_effect(entry: dict[str, object], *, refugee: bool) -> str:
    key = entry["key"]
    school = str(entry["school"])
    name = f"zhx_academy_offer_{'refuge' if refugee else 'revival'}_{key}"
    tiers = ["main", "invited", "friendly" if refugee else "any"]
    blocks = []
    for index, tier in enumerate(tiers):
        limit = candidate_limit(school, tier, refugee=refugee)
        keyword = "if" if index == 0 else "else_if"
        blocks.append(
            f"""    {keyword} = {{
        limit = {{
            any_country = {{
{indent(limit, 16)}
            }}
        }}
        random_country = {{
            limit = {{
{indent(limit, 16)}
            }}
            set_country_flag = zhx_academy_refuge_offer_pending
            set_country_flag = zhx_academy_refuge_offer_{key}
            country_event = {{ id = zhx_academy.210 }}
        }}
    }}"""
        )
    return f"{name} = {{\n" + "\n".join(blocks) + "\n}"


def install_effect(entry: dict[str, object]) -> str:
    key = entry["key"]
    modifier = entry["modifier"]
    destination = f"""add_permanent_province_modifier = {{
    name = {modifier}
    duration = -1
}}
if = {{
    limit = {{ owner = {{ ai = no }} }}
    save_global_event_target_as = zhx_academy_arrival_province
}}"""
    return f"""zhx_academy_install_{key} = {{
    if = {{
        limit = {{
            any_owned_province = {{
                zhx_academy_is_empty_host_province = yes
                development = 20
            }}
        }}
        random_owned_province = {{
            limit = {{
                zhx_academy_is_empty_host_province = yes
                development = 20
            }}
{indent(destination, 12)}
        }}
    }}
    else_if = {{
        limit = {{
            any_owned_province = {{
                zhx_academy_is_empty_host_province = yes
                development = 12
            }}
        }}
        random_owned_province = {{
            limit = {{
                zhx_academy_is_empty_host_province = yes
                development = 12
            }}
{indent(destination, 12)}
        }}
    }}
    else = {{
        random_owned_province = {{
            limit = {{ zhx_academy_is_empty_host_province = yes }}
{indent(destination, 12)}
        }}
    }}
    clr_global_flag = zhx_academy_dormant_{key}
    zhx_academy_clear_refuge_offer_flags = yes
    zhx_refresh_academy_country_effects = yes
}}"""


def finish_effect(entry: dict[str, object]) -> str:
    key = entry["key"]
    return f"""zhx_academy_finish_expulsion_{key} = {{
    owner = {{ save_event_target_as = zhx_academy_expeller }}
    remove_province_modifier = {entry['modifier']}
    remove_province_modifier = zhx_academy_under_expulsion
    add_permanent_province_modifier = {{
        name = zhx_academy_ruins_{key}
        duration = -1
    }}
    set_global_flag = zhx_academy_dormant_{key}
    owner = {{
        if = {{
            limit = {{ ai = no }}
            set_country_flag = zhx_academy_result_{key}
            country_event = {{ id = zhx_academy.220 }}
        }}
        zhx_academy_clear_expulsion_state = yes
        zhx_refresh_academy_country_effects = yes
    }}
    zhx_academy_offer_refuge_{key} = yes
}}"""


def render_effects(academies: list[dict[str, object]]) -> str:
    clear_expelling = "\n".join(
        f"    clr_country_flag = zhx_academy_expelling_{entry['key']}"
        for entry in academies
    )
    clear_offers = "\n".join(
        f"    clr_country_flag = zhx_academy_refuge_offer_{entry['key']}"
        for entry in academies
    )
    clear_results = "\n".join(
        f"    clr_country_flag = zhx_academy_result_{entry['key']}"
        for entry in academies
    )
    withdraw_result_branches = []
    for index, entry in enumerate(academies):
        keyword = "if" if index == 0 else "else_if"
        withdraw_result_branches.append(
            f"""{keyword} = {{
    limit = {{ has_country_flag = zhx_academy_expelling_{entry['key']} }}
    set_country_flag = zhx_academy_result_{entry['key']}
}}"""
        )
    withdraw_result_selection = indent("\n".join(withdraw_result_branches), 8)
    owner_change_identity_pairs = "\n".join(
        "            AND = {\n"
        f"                has_province_modifier = {entry['modifier']}\n"
        "                FROM = { "
        f"has_country_flag = zhx_academy_expelling_{entry['key']}"
        " }\n"
        "            }"
        for entry in academies
    )
    sections = [
        "# Generated by tools/build_zhx_academy_lifecycle.py. Do not hand-edit.",
        "# Scope contracts are documented immediately above each public effect.",
        "",
        "# Country scope. Clears only disposable process state.",
        "zhx_academy_clear_expulsion_state = {\n"
        "    remove_country_modifier = zhx_academy_expulsion_campaign\n"
        + clear_expelling
        + "\n}",
        "",
        "# Country scope. Clears the one pending refuge/revival offer.",
        "zhx_academy_clear_refuge_offer_flags = {\n"
        "    clr_country_flag = zhx_academy_refuge_offer_pending\n"
        + clear_offers
        + "\n}",
        "",
        "# Country scope. Clears one disposable deadline-result presentation flag.",
        "zhx_academy_clear_result_flags = {\n"
        "    clr_country_flag = zhx_academy_result_protected\n"
        + clear_results
        + "\n}",
        "",
        "# Country scope. Player withdrawal; the active academy never moves.",
        "zhx_academy_withdraw_current_expulsion = {\n"
        "    if = {\n"
        "        limit = { ai = no }\n"
        "        random_owned_province = {\n"
        "            limit = { has_province_modifier = zhx_academy_under_expulsion }\n"
        "            save_global_event_target_as = zhx_academy_withdrawn_province\n"
        "        }\n"
        + withdraw_result_selection
        + "\n"
        "    }\n"
        "    every_owned_province = {\n"
        "        limit = { has_province_modifier = zhx_academy_under_expulsion }\n"
        "        remove_province_modifier = zhx_academy_under_expulsion\n"
        "    }\n"
        "    zhx_academy_clear_expulsion_state = yes\n"
        "    add_country_modifier = {\n"
        "        name = zhx_academy_expulsion_cooldown\n"
        "        duration = 3650\n"
        "    }\n"
        "    zhx_refresh_academy_country_effects = yes\n"
        "    if = {\n"
        "        limit = {\n"
        "            ai = no\n"
        "            has_saved_global_event_target = zhx_academy_withdrawn_province\n"
        "        }\n"
        "        country_event = { id = zhx_academy.230 }\n"
        "    }\n"
        "}",
        "",
        "# Province scope during on_province_owner_change; FROM is the old owner.",
        "# Identity pairing cannot rely on a temporary modifier surviving transfer.",
        "zhx_academy_cancel_expulsion_on_owner_change = {\n"
        "    if = {\n"
        "        limit = {\n"
        "            FROM = { exists = yes }\n"
        "            OR = {\n"
        + owner_change_identity_pairs
        + "\n            }\n"
        "        }\n"
        "        FROM = { zhx_academy_clear_expulsion_state = yes }\n"
        "    }\n"
        "    if = {\n"
        "        limit = { has_province_modifier = zhx_academy_under_expulsion }\n"
        "        remove_province_modifier = zhx_academy_under_expulsion\n"
        "    }\n"
        "}",
    ]
    sections.extend(["", *[outrage_effect(school) for school in SCHOOLS]])
    sections.extend(["", *[start_effect(entry) for entry in academies]])

    random_branches = []
    for index, entry in enumerate(academies):
        keyword = "if" if index == 0 else "else_if"
        random_branches.append(
            f"""        {keyword} = {{
            limit = {{ has_province_modifier = {entry['modifier']} }}
            owner = {{ zhx_academy_begin_expulsion_{entry['key']} = yes }}
        }}"""
        )
    sections.extend(
        [
            "",
            "# Country scope. Used only after the strict AI annual gate passes.",
            "zhx_academy_begin_random_unprotected_expulsion = {\n"
            "    random_owned_province = {\n"
            "        limit = { zhx_academy_is_unprotected_active_province = yes }\n"
            + "\n".join(random_branches)
            + "\n    }\n}",
        ]
    )

    for entry in academies:
        sections.extend(
            [
                "",
                finish_effect(entry),
                "",
                offer_effect(entry, refugee=True),
                "",
                offer_effect(entry, refugee=False),
                "",
                install_effect(entry),
            ]
        )

    accept_branches = []
    for index, entry in enumerate(academies):
        keyword = "if" if index == 0 else "else_if"
        accept_branches.append(
            f"""    {keyword} = {{
        limit = {{ has_country_flag = zhx_academy_refuge_offer_{entry['key']} }}
        zhx_academy_install_{entry['key']} = yes
    }}"""
        )
    sections.extend(
        [
            "",
            "# Candidate country scope. Exactly one offer flag should be set.",
            "zhx_academy_accept_pending_offer = {\n"
            + "\n".join(accept_branches)
            + "\n}",
            "",
            "# Tianzi country scope. Each dormant identity gets an independent",
            "# ten-percent yearly revival attempt; active truth repairs stale flags.",
            "zhx_academy_attempt_dormant_revivals = {",
        ]
    )
    for entry in academies:
        key = entry["key"]
        sections.extend(
            [
                "    if = {",
                "        limit = {",
                f"            has_global_flag = zhx_academy_dormant_{key}",
                "            any_country = {",
                "                any_owned_province = {",
                f"                    has_province_modifier = {entry['modifier']}",
                "                }",
                "            }",
                "        }",
                f"        clr_global_flag = zhx_academy_dormant_{key}",
                "    }",
                "    else_if = {",
                "        limit = {",
                f"            has_global_flag = zhx_academy_dormant_{key}",
                "        }",
                "        random = {",
                "            chance = 10",
                f"            zhx_academy_offer_revival_{key} = yes",
                "        }",
                "    }",
            ]
        )
    sections.append("}")
    return "\n".join(sections) + "\n"


def render_decisions() -> str:
    return """# Generated by tools/build_zhx_academy_lifecycle.py. Do not hand-edit.

country_decisions = {
    zhx_manage_unprotected_academies = {
        major = no

        potential = {
            ai = no
            zhx_is_lijiao_country = yes
            zhx_has_doctrine = yes
            zhx_academy_has_any_unprotected = yes
        }

        allow = {
            is_at_war = no
            stability = 1
            adm_power = 30
            NOT = { has_country_modifier = zhx_academy_expulsion_campaign }
            NOT = { has_country_modifier = zhx_academy_expulsion_cooldown }
        }

        effect = { country_event = { id = zhx_academy.100 } }
        ai_will_do = { factor = 0 }
    }

    zhx_withdraw_academy_expulsion = {
        major = no

        potential = {
            ai = no
            has_country_modifier = zhx_academy_expulsion_campaign
            any_owned_province = {
                has_province_modifier = zhx_academy_under_expulsion
            }
        }

        allow = { always = yes }
        effect = {
            custom_tooltip = zhx_academy_withdraw_expulsion_tt
            hidden_effect = { zhx_academy_withdraw_current_expulsion = yes }
        }
        ai_will_do = { factor = 0 }
    }
}
"""


def event_option(entry: dict[str, object]) -> str:
    key = entry["key"]
    return f"""    option = {{
        name = zhx_academy_lifecycle.expel_{key}
        trigger = {{
            custom_trigger_tooltip = {{
                tooltip = zhx_academy_expulsion_requirements_tt
                is_at_war = no
                stability = 1
                adm_power = 30
                NOT = {{ has_country_modifier = zhx_academy_expulsion_campaign }}
                NOT = {{ has_country_modifier = zhx_academy_expulsion_cooldown }}
                zhx_academy_has_unprotected_{key} = yes
            }}
        }}
        custom_tooltip = zhx_academy_issue_expulsion_tt
        hidden_effect = {{ zhx_academy_begin_expulsion_{key} = yes }}
        ai_chance = {{ factor = 0 }}
    }}"""


def render_events(academies: list[dict[str, object]]) -> str:
    pages = [academies[:6], academies[6:]]
    sections = [
        "# Generated by tools/build_zhx_academy_lifecycle.py. Do not hand-edit.",
        "namespace = zhx_academy",
    ]
    for page_index, entries in enumerate(pages, start=1):
        event_id = 99 + page_index
        sections.extend(
            [
                "",
                "country_event = {",
                f"    id = zhx_academy.{event_id}",
                "    title = zhx_academy_lifecycle.100.t",
                f"    desc = zhx_academy_lifecycle.100.d{page_index}",
                "    picture = DIPLOMACY_eventPicture",
                "    is_triggered_only = yes",
                "",
                "    trigger = {",
                "        ai = no",
                "        zhx_is_lijiao_country = yes",
                "        zhx_has_doctrine = yes",
                "    }",
                "",
                "\n\n".join(event_option(entry) for entry in entries),
                "",
            ]
        )
        if page_index == 1:
            sections.extend(
                [
                    "    option = {",
                    "        name = zhx_academy_lifecycle.next_page",
                    "        country_event = { id = zhx_academy.101 }",
                    "        ai_chance = { factor = 0 }",
                    "    }",
                ]
            )
        else:
            sections.extend(
                [
                    "    option = {",
                    "        name = zhx_academy_lifecycle.previous_page",
                    "        country_event = { id = zhx_academy.100 }",
                    "        ai_chance = { factor = 0 }",
                    "    }",
                ]
            )
        sections.extend(
            [
                "    option = {",
                "        name = zhx_academy_lifecycle.tolerate",
                "        ai_chance = { factor = 0 }",
                "    }",
                "}",
            ]
        )

    # Deadline event: each unique active modifier selects exactly one branch.
    resolution_branches = []
    for index, entry in enumerate(academies):
        key = entry["key"]
        school = str(entry["school"])
        keyword = "if" if index == 0 else "else_if"
        resolution_branches.append(
            f"""        {keyword} = {{
            limit = {{
                has_province_modifier = {entry['modifier']}
                owner = {{ has_country_flag = zhx_academy_expelling_{key} }}
            }}
            if = {{
                limit = {{
                    owner = {{
{indent(protection_trigger(school), 24)}
                    }}
                }}
                remove_province_modifier = zhx_academy_under_expulsion
                owner = {{
                    if = {{
                        limit = {{ ai = no }}
                        set_country_flag = zhx_academy_result_{key}
                        set_country_flag = zhx_academy_result_protected
                        country_event = {{ id = zhx_academy.221 }}
                    }}
                    zhx_academy_clear_expulsion_state = yes
                    zhx_refresh_academy_country_effects = yes
                }}
            }}
            else = {{ zhx_academy_finish_expulsion_{key} = yes }}
        }}"""
        )
    sections.extend(
        [
            "",
            "province_event = {",
            "    id = zhx_academy.200",
            "    title = zhx_academy_lifecycle.200.t",
            "    desc = zhx_academy_lifecycle.200.d",
            "    picture = DIPLOMACY_eventPicture",
            "    hidden = yes",
            "    is_triggered_only = yes",
            "",
            "    trigger = {",
            "        has_province_modifier = zhx_academy_under_expulsion",
            "    }",
            "",
            "    immediate = {",
            "\n".join(resolution_branches),
            "        else = {",
            "            remove_province_modifier = zhx_academy_under_expulsion",
            "            owner = { zhx_refresh_academy_country_effects = yes }",
            "        }",
            "    }",
            "",
            "    option = { name = OK }",
            "}",
        ]
    )

    # The expelling player receives a visible result after the hidden province
    # deadline resolver has finished.  Per-academy flags select the narrative;
    # the shared protected flag distinguishes cancellation from departure.
    for event_id, protected in ((220, False), (221, True)):
        sections.extend(
            [
                "",
                "country_event = {",
                f"    id = zhx_academy.{event_id}",
                f"    title = zhx_academy_lifecycle.{event_id}.t",
            ]
        )
        for entry in academies:
            sections.append(
                "    desc = { "
                f"trigger = {{ has_country_flag = zhx_academy_result_{entry['key']} }} "
                f"desc = zhx_academy_lifecycle.{event_id}.d.{entry['key']} "
                "}"
            )
        sections.extend(
            [
                "    picture = DIPLOMACY_eventPicture",
                "    is_triggered_only = yes",
                "",
                "    trigger = {",
                "        ai = no",
                (
                    "        has_country_flag = zhx_academy_result_protected"
                    if protected
                    else "        NOT = { has_country_flag = zhx_academy_result_protected }"
                ),
                "        OR = {",
                *(
                    f"            has_country_flag = zhx_academy_result_{entry['key']}"
                    for entry in academies
                ),
                "        }",
                "    }",
                "",
                "    option = {",
                f"        name = zhx_academy_lifecycle.{event_id}.a",
                "        hidden_effect = { zhx_academy_clear_result_flags = yes }",
                "    }",
                "}",
            ]
        )

    sections.extend(
        [
            "",
            "country_event = {",
            "    id = zhx_academy.210",
            "    title = zhx_academy_lifecycle.210.t",
        ]
    )
    for entry in academies:
        sections.append(
            "    desc = { "
            f"trigger = {{ has_country_flag = zhx_academy_refuge_offer_{entry['key']} }} "
            f"desc = zhx_academy_lifecycle.210.d.{entry['key']} "
            "}"
        )
    sections.extend(
        [
            "    picture = DIPLOMACY_eventPicture",
            "    is_triggered_only = yes",
            "",
            "    trigger = {",
            "        has_country_flag = zhx_academy_refuge_offer_pending",
            "    }",
            "",
            "    option = {",
            "        name = zhx_academy_lifecycle.210.a",
            "        trigger = {",
            "            custom_trigger_tooltip = {",
            "                tooltip = zhx_academy_refuge_host_requirements_tt",
            "                zhx_academy_has_empty_host_province = yes",
            "            }",
            "        }",
            "        custom_tooltip = zhx_academy_accept_refuge_tt",
            "        hidden_effect = {",
            "            zhx_academy_accept_pending_offer = yes",
            "            if = {",
            "                limit = {",
            "                    ai = no",
            "                    has_saved_global_event_target = zhx_academy_arrival_province",
            "                }",
            "                country_event = { id = zhx_academy.211 }",
            "            }",
            "        }",
            "        ai_chance = {",
            "            factor = 2",
            "            modifier = { factor = 2 stability = 1 }",
            "            modifier = { factor = 0.5 is_at_war = yes }",
            "        }",
            "    }",
            "    option = {",
            "        name = zhx_academy_lifecycle.210.b",
            "        custom_tooltip = zhx_academy_refuse_refuge_tt",
            "        hidden_effect = { zhx_academy_clear_refuge_offer_flags = yes }",
            "        ai_chance = { factor = 1 }",
            "    }",
            "}",
            "",
            "# The successful province branch saves its exact destination globally;",
            "# .210 then opens this receipt from the current human country scope.",
            "country_event = {",
            "    id = zhx_academy.211",
            "    title = zhx_academy_lifecycle.211.t",
        ]
    )
    for entry in academies:
        sections.append(
            "    desc = { "
            "trigger = { event_target:zhx_academy_arrival_province = { "
            f"has_province_modifier = {entry['modifier']} "
            "} } "
            f"desc = zhx_academy_lifecycle.211.d.{entry['key']} "
            "}"
        )
    sections.extend(
        [
            "    picture = DIPLOMACY_eventPicture",
            "    goto = zhx_academy_arrival_province",
            "    is_triggered_only = yes",
            "",
            "    trigger = {",
            "        ai = no",
            "        has_saved_global_event_target = zhx_academy_arrival_province",
            "        event_target:zhx_academy_arrival_province = {",
            "            owned_by = ROOT",
            "            zhx_academy_is_active_province = yes",
            "        }",
            "    }",
            "",
            "    option = {",
            "        name = zhx_academy_lifecycle.211.a",
            "        hidden_effect = {",
            "            clear_global_event_target = zhx_academy_arrival_province",
            "        }",
            "    }",
            "}",
        ]
    )
    sections.extend(
        [
            "",
            "# A player who withdraws an edict receives one named, province-linked",
            "# result after pressure and process state have been cleared.",
            "country_event = {",
            "    id = zhx_academy.230",
            "    title = zhx_academy_lifecycle.230.t",
        ]
    )
    for entry in academies:
        sections.append(
            "    desc = { trigger = { "
            f"has_country_flag = zhx_academy_result_{entry['key']} "
            "event_target:zhx_academy_withdrawn_province = { "
            f"has_province_modifier = {entry['modifier']} "
            "} } "
            f"desc = zhx_academy_lifecycle.230.d.{entry['key']} "
            "}"
        )
    sections.extend(
        [
            "    picture = DIPLOMACY_eventPicture",
            "    goto = zhx_academy_withdrawn_province",
            "    is_triggered_only = yes",
            "",
            "    trigger = {",
            "        ai = no",
            "        has_saved_global_event_target = zhx_academy_withdrawn_province",
            "        event_target:zhx_academy_withdrawn_province = { owned_by = ROOT }",
            "        OR = {",
        ]
    )
    for entry in academies:
        sections.append(
            "            AND = { "
            f"has_country_flag = zhx_academy_result_{entry['key']} "
            "event_target:zhx_academy_withdrawn_province = { "
            f"has_province_modifier = {entry['modifier']} "
            "} }"
        )
    sections.extend(
        [
            "        }",
            "    }",
            "",
            "    option = {",
            "        name = zhx_academy_lifecycle.230.a",
            "        hidden_effect = {",
            "            zhx_academy_clear_result_flags = yes",
            "            clear_global_event_target = zhx_academy_withdrawn_province",
            "        }",
            "    }",
            "}",
            "",
            "# Annual AI gate. The eight-percent roll occurs only after all strict",
            "# peace, capacity and plurality conditions have passed.",
            "country_event = {",
            "    id = zhx_academy.300",
            "    title = zhx_academy_lifecycle.300.t",
            "    desc = zhx_academy_lifecycle.300.d",
            "    picture = DIPLOMACY_eventPicture",
            "    hidden = yes",
            "    is_triggered_only = yes",
            "    trigger = { exists = yes }",
            "",
            "    immediate = {",
            "        if = {",
            "            limit = {",
            "                NOT = { has_country_modifier = zhx_academy_expulsion_campaign }",
            "                OR = {",
        ]
    )
    sections.extend(
        f"                    has_country_flag = zhx_academy_expelling_{entry['key']}"
        for entry in academies
    )
    sections.extend(
        [
            "                }",
            "            }",
            "            zhx_academy_clear_expulsion_state = yes",
            "        }",
            "        if = {",
            "            limit = {",
            "                ai = yes",
            "                zhx_is_lijiao_country = yes",
            "                zhx_has_doctrine = yes",
            "                is_at_war = no",
            "                stability = 2",
            "                adm_power = 100",
            "                NOT = { has_country_modifier = zhx_academy_expulsion_campaign }",
            "                NOT = { has_country_modifier = zhx_academy_expulsion_cooldown }",
            "                zhx_academy_has_two_unprotected_school_types = yes",
            "            }",
            "            random = {",
            "                chance = 8",
            "                zhx_academy_begin_random_unprotected_expulsion = yes",
            "            }",
            "        }",
            "    }",
            "    option = { name = OK }",
            "}",
            "",
            "# One annual revival scheduler: only the current Tianzi may pass.",
            "country_event = {",
            "    id = zhx_academy.301",
            "    title = zhx_academy_lifecycle.301.t",
            "    desc = zhx_academy_lifecycle.301.d",
            "    picture = DIPLOMACY_eventPicture",
            "    hidden = yes",
            "    is_triggered_only = yes",
            "    trigger = {",
            "        exists = yes",
            "        zhx_is_tianzi = yes",
            "        zhx_academy_has_any_dormant = yes",
            "    }",
            "    immediate = { zhx_academy_attempt_dormant_revivals = yes }",
            "    option = { name = OK }",
            "}",
        ]
    )
    return "\n".join(sections) + "\n"


def render_localisation(academies: list[dict[str, object]]) -> str:
    lines = [
        "l_english:",
        ' zhx_manage_unprotected_academies_title:0 "处置异派学宫"',
        ' zhx_manage_unprotected_academies_desc:0 "检视国内未受本国主学派或受邀第二学派保护的具名学宫。你可以继续容忍其讲学，也可以颁布为期三年的逐学令。"',
        ' zhx_withdraw_academy_expulsion_title:0 "撤销逐学令"',
        ' zhx_withdraw_academy_expulsion_desc:0 "停止正在执行的逐学令，保留学宫原址；此后十年内不得再次发起逐学。"',
        ' zhx_academy_withdraw_expulsion_tt:0 "停止当前逐学，保留学宫原址并解除逐学压制；此后§Y10年§!内不得再次逐学。"',
        ' zhx_academy_lifecycle.100.t:0 "异派学宫"',
        ' zhx_academy_lifecycle.100.d1:0 "以下学宫并不属于本国主学派，也未获受邀第二学派庇护。逐学将耗费行政资源、稳定与声望，并激怒奉行该学派的诸国。"',
        ' zhx_academy_lifecycle.100.d2:0 "余下异派学宫列于此页。任何逐学令都需三年执行；其间若该学派成为本国主学派或受邀第二学派，命令将在到期时自动撤销。"',
        ' zhx_academy_lifecycle.next_page:0 "查看下一页"',
        ' zhx_academy_lifecycle.previous_page:0 "返回上一页"',
        ' zhx_academy_lifecycle.tolerate:0 "继续容忍讲学"',
        ' zhx_academy_expulsion_requirements_tt:0 "本国处于和平，稳定度至少为§Y1§!、行政点数至少为§Y30§!，当前没有逐学令或撤令余波，且该学宫仍是不受保护的异派学宫。"',
        ' zhx_academy_issue_expulsion_tt:0 "颁布三年逐学令：失去§R30§!行政点、§R1§!稳定度与§R5§!威望。奉行该学派的礼教国家将对我国产生§R-50§!意见并获得§R10§!侵略扩张。"',
        ' zhx_academy_lifecycle.200.t:0 "逐学令结算"',
        ' zhx_academy_lifecycle.200.d:0 "逐学令已经到期。"',
        ' zhx_academy_lifecycle.210.t:0 "流散学宫求庇"',
        ' zhx_academy_lifecycle.210.a:0 "接纳诸生，另辟讲席"',
        ' zhx_academy_lifecycle.210.b:0 "婉拒其请"',
        ' zhx_academy_refuge_host_requirements_tt:0 "国内至少有一座没有活跃学宫、学宫遗址或逐学压制的城市可供安置。"',
        ' zhx_academy_accept_refuge_tt:0 "学宫将优先迁入本国一座发展度至少20的空闲城市，其次选择发展度至少12的城市；若仍无，则选择任一没有活跃学宫、学宫遗址或逐学压制的城市。"',
        ' zhx_academy_refuse_refuge_tt:0 "婉拒后，学宫不会迁入我国，也不会被永久删除，而会保持流散。当前天子每年有§Y10%§!概率尝试为其另寻庇护；若没有合格礼教国家接纳，学宫将继续流散。"',
        ' zhx_academy_lifecycle.211.t:0 "学宫落脚"',
        ' zhx_academy_lifecycle.211.a:0 "安置诸生，重开讲席"',
        ' zhx_academy_lifecycle.220.t:0 "学宫离境"',
        ' zhx_academy_lifecycle.220.a:0 "旧址尚存，学统自有去处"',
        ' zhx_academy_lifecycle.221.t:0 "逐学令止息"',
        ' zhx_academy_lifecycle.221.a:0 "准其仍在原址讲学"',
        ' zhx_academy_lifecycle.230.t:0 "撤销逐学令"',
        ' zhx_academy_lifecycle.230.a:0 "准其安居原址"',
        ' zhx_academy_lifecycle.300.t:0 "学宫年度处置"',
        ' zhx_academy_lifecycle.300.d:0 "隐藏的学宫年度逻辑。"',
        ' zhx_academy_lifecycle.301.t:0 "流散学宫年度复兴"',
        ' zhx_academy_lifecycle.301.d:0 "隐藏的流散学宫年度复兴逻辑。"',
        ' zhx_academy_expulsion_campaign:0 "逐学令执行中"',
        ' zhx_academy_expulsion_campaign_desc:0 "官府正在压制一座异派学宫；同一时间只能执行一道逐学令。"',
        ' zhx_academy_under_expulsion:0 "逐学压制"',
        ' zhx_academy_under_expulsion_desc:0 "讲席遭到封禁，藏书与师生正在流散。若三年后仍不受本国主学派或第二学派保护，学宫将离开此地。"',
        ' zhx_academy_expulsion_cooldown:0 "撤令余波"',
        ' zhx_academy_expulsion_cooldown_desc:0 "朝廷刚刚撤销逐学令，十年内不得再次发动逐学。"',
        ' zhx_opinion_expelled_our_school:0 "驱逐我派学宫"',
    ]
    for entry in academies:
        name = entry["name"]
        school_name = SCHOOLS[str(entry["school"])]["name"]
        lines.extend(
            [
                f' zhx_academy_lifecycle.expel_{entry["key"]}:0 "逐学：{name}"',
                f' zhx_academy_lifecycle.210.d.{entry["key"]}:0 "{name}的诸生携藏书与礼器前来，请求我国庇护并准其重开讲席。接纳后，{school_name}学宫将在一座合格城市重新落脚。"',
                f' zhx_academy_lifecycle.211.d.{entry["key"]}:0 "§Y{name}§!的诸生已在§Y[zhx_academy_arrival_province.GetName]§!重开讲席。这里将继续传承{school_name}学统，并恢复具名学宫的全部地方收益。"',
                f' zhx_academy_lifecycle.220.d.{entry["key"]}:0 "三年逐学令已经执行完毕。{name}离开原址，故地留下学宫遗址；诸生将依次寻求同派、受邀同派或友好礼教国家庇护，无人接纳时则暂入流散。"',
                f' zhx_academy_lifecycle.221.d.{entry["key"]}:0 "逐学令到期时，{name}已得到本国主学派或受邀第二学派的正式保护。禁令就此撤销，学宫仍在原址讲学。"',
                f' zhx_academy_lifecycle.230.d.{entry["key"]}:0 "朝廷已经撤销针对§Y{name}§!的逐学令。学宫仍在§Y[zhx_academy_withdrawn_province.GetName]§!原址讲学，逐学压制已经解除；此后§Y10年§!内不得再次颁布逐学令。"',
                f' zhx_academy_ruins_{entry["key"]}:0 "{name}遗址"',
                f' zhx_academy_ruins_{entry["key"]}_desc:0 "这里曾是{name}的讲席。逐学令使诸生与藏书离散，但旧址仍保留少量学术遗产。"',
            ]
        )
    return "\n".join(lines) + "\n"


def balanced_braces(text: str, label: str) -> None:
    depth = 0
    in_string = False
    escaped = False
    in_comment = False
    for character in text:
        if in_comment:
            if character == "\n":
                in_comment = False
            continue
        if in_string:
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == '"':
                in_string = False
            continue
        if character == "#":
            in_comment = True
        elif character == '"':
            in_string = True
        elif character == "{":
            depth += 1
        elif character == "}":
            depth -= 1
            if depth < 0:
                raise ValueError(f"{label}: closing brace without opener")
    if in_string or depth:
        raise ValueError(f"{label}: unbalanced text (brace depth {depth})")


def render_all(academies: list[dict[str, object]]) -> dict[str, str]:
    rendered = {
        "triggers": render_triggers(academies),
        "effects": render_effects(academies),
        "modifiers": render_modifiers(academies),
        "opinions": render_opinions(),
        "decisions": render_decisions(),
        "events": render_events(academies),
        "localisation": render_localisation(academies),
    }
    for label, text in rendered.items():
        balanced_braces(text, label)
    return rendered


def run(check: bool) -> None:
    academies = load_academies()
    rendered = render_all(academies)
    for label, path in OUTPUTS.items():
        expected = rendered[label]
        if check:
            if not path.exists() or path.read_text(encoding="utf-8-sig") != expected:
                raise ValueError(f"stale generated academy lifecycle file: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    action = "checked" if check else "built"
    print(f"{action} academy lifecycle: academies={len(academies)}, outputs={len(OUTPUTS)}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    run(args.check)


if __name__ == "__main__":
    main()
