#!/usr/bin/env python3
"""Generate the province mod page from the authoritative academy manifest."""
from pathlib import Path
import argparse
import json
import re

ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / 'guangdong_independent_practice'
BEGIN = '\t\t\t# ZHX_PROVINCE_PANEL_BEGIN'
END = '\t\t\t# ZHX_PROVINCE_PANEL_END'
PAGE = 'FROM = { has_country_flag = zhx_province_mod_page }'
SCHOOLS = {'ru':'儒家','fa':'法家','mo':'墨家','dao':'道家','bing':'兵家','zongheng':'纵横家'}


def build():
    academies = json.loads((ROOT / 'planning/religion_academies/academy_manifest.json').read_text())['academies']
    loc = {}
    bindings = ['# Generated by tools/build_zhx_province_panel.py. No gameplay state is duplicated.']
    dynamic = ['# Generated from academy_manifest.json; all readers use province modifiers.']

    def bind(kind, name, potential='always = yes', trigger=None, effect=None, tooltip=None):
        lines = [f'custom_{kind} = {{', f'    name = {name}', f'    potential = {{ {potential} }}']
        if trigger is not None: lines.append(f'    trigger = {{ hidden_trigger = {{ {trigger} }} }}')
        if effect is not None: lines.append(f'    effect = {{ hidden_effect = {{ {effect} }} }}')
        if tooltip: lines.append(f'    tooltip = {tooltip}')
        bindings.append('\n'.join(lines + ['}']))

    def text(name, value, x, y, w=292, h=32, font='vic_18', potential='always = yes', tooltip=None):
        loc[name] = value
        bind('text_box', name, potential, tooltip=tooltip)
        return f'''instantTextBoxType = {{
    name = "{name}"
    position = {{ x = {x} y = {y} }}
    font = "{font}"
    borderSize = {{ x = 2 y = 2 }}
    maxWidth = {w}
    maxHeight = {h}
    format = left
    scripted = yes
}}'''

    def button(name, caption, x, y, potential='always = yes', trigger='always = yes', effect='', tooltip=None):
        loc[name] = caption
        bind('button',name,potential,trigger,effect,tooltip)
        return f'''guiButtonType = {{
    name = "{name}"
    position = {{ x = {x} y = {y} }}
    quadTextureSprite = "GFX_standard_button_71"
    buttonText = "{name}"
    buttonFont = "vic_18"
    clicksound = click
    scripted = yes
}}'''

    def defined(name, variants):
        lines = [f'defined_text = {{\n    name = {name}\n    random = no']
        for value,condition in variants:
            lines.append(f'    text = {{\n        localisation_key = {value}\n        trigger = {{ {condition} }}\n    }}')
        dynamic.append('\n'.join(lines+['}']))

    bind('window','zhx_province_mod_window',PAGE)
    bind('button','zhx_province_mod_background','always = yes','always = yes','')
    body = ['''guiButtonType = {
    name = "zhx_province_mod_background"
    position = { x = 0 y = 115 }
    quadTextureSprite = "GFX_zhx_province_mod_background"
    scripted = yes
}''']
    body += [text('zhx_province_panel_title','省务',24,137,110,32,'vic_22'),
             text('zhx_province_tianxia_heading','周天下省籍',24,184,290,32,'vic_22'),
             text('zhx_province_tianxia_status','[Root.GetZhxProvinceTianxiaStatus]',90,225,220,42),
             text('zhx_province_tianxia_help','[Root.GetZhxProvinceTianxiaHelp]',24,267,292,36)]
    for name,sprite in [('member_status','status'),('add','add'),('remove','remove')]:
        body.append(f'''guiButtonType = {{
    name = "gdd_tianxia_province_{name}_button"
    quadTextureSprite = "GFX_gdd_tianxia_province_{sprite}"
    position = {{ x = 24 y = 220 }}
    clicksound = click
    scripted = yes
}}''')
    body += [text('zhx_province_academy_heading','本省学宫',24,313,290,20,'vic_18'),
             text('zhx_province_academy_name','[Root.GetZhxProvinceAcademyName]',24,450,292,26,tooltip='zhx_province_academy_details'),
             text('zhx_province_academy_state','[Root.GetZhxProvinceAcademyState]',24,480,292,28),
             text('zhx_province_academy_ruins','学宫遗址：悬停查看记录',24,517,292,24,potential='zhx_academy_is_former_site = yes',tooltip='zhx_province_academy_ruins_tt'),
             button('zhx_province_academy_manage','处置学宫',24,552,
                    'owned_by = FROM zhx_academy_is_active_province = yes',
                    'FROM = { ai = no zhx_is_lijiao_country = yes zhx_has_doctrine = yes zhx_academy_has_any_unprotected = yes is_at_war = no stability = 1 adm_power = 30 NOT = { has_country_modifier = zhx_academy_expulsion_campaign } NOT = { has_country_modifier = zhx_academy_expulsion_cooldown } }',
                    'FROM = { country_event = { id = zhx_academy.100 } }','zhx_province_academy_manage_tt'),
             button('zhx_province_academy_withdraw','撤回驱逐',112,552,
                    'owned_by = FROM has_province_modifier = zhx_academy_under_expulsion',
                    'FROM = { ai = no has_country_modifier = zhx_academy_expulsion_campaign }',
                    'FROM = { zhx_academy_withdraw_current_expulsion = yes }','zhx_academy_withdraw_expulsion_tt')]
    tabs = [button('zhx_province_buildings_tab','建筑',146,137,
                   trigger=PAGE,effect='FROM = { clr_country_flag = zhx_province_mod_page }',tooltip='zhx_province_buildings_tab_tt'),
            button('zhx_province_mod_tab','诸夏省务',224,137,
                   trigger=f'NOT = {{ {PAGE} }}',effect='FROM = { set_country_flag = zhx_province_mod_page }',tooltip='zhx_province_mod_tab_tt')]
    panel = '''windowType = {
    name = "zhx_province_mod_window"
    position = { x = 0 y = 0 }
    size = { x = 348 y = 595 }
    moveable = 0
    fullScreen = no
    scripted = yes
'''+ '\n'.join('    '+line for item in body for line in item.splitlines())+'\n}'
    block = BEGIN+'\n'+'\n'.join('\t\t\t'+line for item in [panel]+tabs for line in item.splitlines())+'\n'+END
    gui = MOD / 'interface/provinceview.gui'
    content=gui.read_text()
    if BEGIN in content:
        content=re.sub(re.escape(BEGIN)+r'.*?'+re.escape(END),lambda m:block,content,flags=re.S)
    else:
        marker='\t\t\tguiButtonType = {\n\t\t\t\tname = "building_close_button"'
        assert content.count(marker)==1
        content=content.replace(marker,block+'\n\n'+marker)

    loc.update({
        'zhx_province_buildings_tab_tt':'查看本省建筑、省份价值与革命信息。',
        'zhx_province_mod_tab_tt':'查看本省周天下省籍、学宫与遗址；切换省份后继续显示此页。',
        'zhx_province_academy_manage_tt':'打开本国现有的学宫处置列表，选择学宫后再执行驱逐。',
        'zhx_province_academy_details':'[Root.GetZhxProvinceAcademyDetails]',
        'zhx_province_empty':'',
        'zhx_province_academy_none':'无在驻学宫',
        'zhx_province_academy_none_desc':'本省没有正在讲学的学宫。遗址不计作在驻学宫。',
        'zhx_province_academy_expelling':'§R正在驱逐§!：迁徙流程进行中',
        'zhx_province_academy_main_protected':'§G受主学派保护§!',
        'zhx_province_academy_invited_protected':'§G受礼聘学者保护§!',
        'zhx_province_academy_unprotected':'§Y未受学派保护§!',
        'zhx_province_tianxia_dismantled':'周天下已解散',
        'zhx_province_tianxia_uninitialised':'周天下尚未建立',
        'zhx_province_tianxia_hre':'神罗省份',
        'zhx_province_tianxia_tc':'贸易公司省份',
        'zhx_province_tianxia_member':'§G已入籍§! · 成员领土',
        'zhx_province_tianxia_foreign':'§Y已入籍§! · 域外持有',
        'zhx_province_tianxia_unregistered':'尚未登记周籍',
        'zhx_province_tianxia_outside':'非周天下成员领土',
        'zhx_province_tianxia_help_inactive':'当前没有可用的省籍操作。',
        'zhx_province_tianxia_help_exclusive':'神罗或贸易公司省份须先退出原制度，才能登记周籍。',
        'zhx_province_tianxia_help_member':'已登记为周土。悬停周字徽记可查看本省的省籍说明。',
        'zhx_province_tianxia_help_foreign':'本省仍保留周籍；符合条件的持有者可以申请移除。',
        'zhx_province_tianxia_help_add':'符合和平、自控与直属完整核心等条件后，可将本省登记为周土。',
    })
    states=[('dismantled','has_global_flag = zhx_tianxia_dismantled'),
            ('uninitialised','NOT = { has_global_flag = zhx_system_initialised_v13 }'),
            ('hre','is_part_of_hre = yes'),('tc','is_owned_by_trade_company = yes'),
            ('member','has_province_flag = zhx_tianxia_province owner = { zhx_is_tianxia_polity = yes }'),
            ('foreign','has_province_flag = zhx_tianxia_province'),
            ('unregistered','owner = { zhx_is_tianxia_polity = yes }'),('outside','always = yes')]
    defined('GetZhxProvinceTianxiaStatus',[(f'zhx_province_tianxia_{k}',v) for k,v in states])
    help_map={'dismantled':'inactive','uninitialised':'inactive','hre':'exclusive','tc':'exclusive','member':'member','foreign':'foreign','unregistered':'add','outside':'inactive'}
    defined('GetZhxProvinceTianxiaHelp',[(f'zhx_province_tianxia_help_{help_map[k]}',v) for k,v in states])
    names=[];details=[];academy_states=[('zhx_province_academy_expelling','has_province_modifier = zhx_academy_under_expulsion')]
    ruins=[]
    for a in academies:
        key=a['key'];school=a['school'];modifier=a['modifier']
        loc[f'zhx_province_academy_{key}_name']=f"{a['name']} · {SCHOOLS[school]}"
        names.append((f'zhx_province_academy_{key}_name',f'has_province_modifier = {modifier}'))
        details.append((modifier+'_desc',f'has_province_modifier = {modifier}'))
        academy_states.extend([
            ('zhx_province_academy_main_protected',f'has_province_modifier = {modifier} owner = {{ has_country_flag = zhx_doctrine_{school} }}'),
            ('zhx_province_academy_invited_protected',f'has_province_modifier = {modifier} owner = {{ has_country_modifier = zhx_{school}_invited_scholar_modifier }}')])
        loc[f'zhx_province_ruins_{key}']=f"\\n{a['name']}遗址"
        reader=f'GetZhxProvinceRuins{key.title()}'
        defined(reader,[(f'zhx_province_ruins_{key}',f'has_province_modifier = zhx_academy_ruins_{key}'),('zhx_province_empty','always = yes')])
        ruins.append(f'[Root.{reader}]')
    loc['zhx_province_academy_ruins_tt']='本省留存的学宫遗址：'+''.join(ruins)+'\\n遗址不计作在驻学宫，也不提供学宫协同。'
    defined('GetZhxProvinceAcademyName',names+[('zhx_province_academy_none','always = yes')])
    defined('GetZhxProvinceAcademyDetails',details+[('zhx_province_academy_none_desc','always = yes')])
    defined('GetZhxProvinceAcademyState',academy_states+[
        ('zhx_province_academy_unprotected','zhx_academy_is_active_province = yes'),('zhx_province_empty','always = yes')])
    gfx='''spriteTypes = {
    # Opaque native-sized artwork; runtime controls supply all labels and actions.
    spriteType = {
        name = "GFX_zhx_province_mod_background"
        texturefile = "gfx/interface/zhx_province_panel_v1.tga"
        noOfFrames = 1
    }
}
'''
    return {gui:content,
            MOD/'common/custom_gui/zhx_province_panel.txt':'\n\n'.join(bindings)+'\n',
            MOD/'customizable_localization/zhx_province_panel.txt':'\n\n'.join(dynamic)+'\n',
            MOD/'localisation_source/zhx_province_panel_readable_utf8.txt':'l_english:\n'+''.join(f' {k}:0 "{v}"\n' for k,v in loc.items()),
            MOD/'interface/zhx_province_panel.gfx':gfx}


def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for p,content in build().items():
        if args.check:
            assert p.exists() and p.read_text()==content,f'generated output stale: {p}'
        else: p.write_text(content)
        print(('checked ' if args.check else 'wrote ')+str(p.relative_to(ROOT)))


if __name__=='__main__':main()
