#!/usr/bin/env python3
"""Generate explainable AI reform-support tooltips for the EoC member grid."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "guangdong_independent_practice"
CUSTOMIZABLE = MOD / "customizable_localization/gdd_celestial_member_tooltips.txt"
LOCALISATION = MOD / "localisation_source/gdd_celestial_ui_readable_utf8.txt"
BEGIN = " # GDD_EOC_MEMBER_TOOLTIP_LOC_BEGIN"
END = " # GDD_EOC_MEMBER_TOOLTIP_LOC_END"

# IDs are the approved visible 8/6/6 button order and therefore the stable
# tiebreak used by gdd_consider_ai_reform_tooltip_rank_effect.
REFORMS = [
    (1, "keju", "改制科举"),
    (2, "civil_registration", "编户齐民"),
    (3, "silver_standard", "稳固银本"),
    (4, "kanhe", "勘合符契"),
    (5, "unified_market", "统一市法"),
    (6, "military_branch", "经武整军"),
    (7, "foreign_ship_designs", "研造夷船"),
    (8, "inclusive_monarchy", "仁德教化"),
    (9, "establish_gaituguiliu", "改土归流"),
    (10, "land_tax", "委任总督"),
    (11, "single_whip", "条鞭赋役"),
    (12, "centralizing_government", "重整官制"),
    (13, "reign_in_estates", "禁锢朋党"),
    (14, "vassalize_tributaries", "天下归一"),
    (15, "seaban", "晋封外藩"),
    (16, "military_governors", "联市通商"),
    (17, "tributary_embassies", "列国通聘"),
    (18, "modernize_banners", "分镇戍边"),
    (19, "bureaucratic_faction", "共议国是"),
    (20, "new_world", "会盟天下"),
]


def defined_text(name: str, entries: list[tuple[str, str]]) -> str:
    lines = ["defined_text = {", f"    name = {name}", "    random = no", ""]
    for key, trigger in entries:
        lines.extend(
            [
                "    text = {",
                f"        localisation_key = {key}",
                f"        trigger = {{ {trigger} }}",
                "    }",
            ]
        )
    lines.append("}")
    return "\n".join(lines)


def build_customizable() -> str:
    blocks = [
        "# Generated by tools/generate_gdd_celestial_member_tooltips.py.",
        "# ROOT is the hovered Zhou member; human members deliberately resolve",
        "# to an empty string, so only AI ballots expose an explanatory hover.",
        "",
        defined_text(
            "GetGddEocMemberShieldTooltip",
            [
                ("gdd_eoc_member_tooltip_blank", "ai = no"),
                (
                    "gdd_eoc_member_tooltip_ai_supported",
                    "check_variable = { which = gdd_reform_tooltip_supported_count value = 1 }",
                ),
                ("gdd_eoc_member_tooltip_ai_none", "always = yes"),
            ],
        ),
    ]

    for slot in (1, 2):
        blocks.append(
            defined_text(
                f"GetGddEocMemberTop{slot}Name",
                [
                    (
                        f"gdd_eoc_reform_name_{slug}",
                        f"is_variable_equal = {{ which = gdd_reform_tooltip_top_{slot}_id value = {reform_id} }}",
                    )
                    for reform_id, slug, _ in REFORMS
                ]
                + [("gdd_eoc_member_tooltip_blank", "always = yes")],
            )
        )
        threshold = slot
        blocks.append(
            defined_text(
                f"GetGddEocMemberTop{slot}Block",
                [
                    (
                        f"gdd_eoc_member_top_{slot}_block",
                        f"check_variable = {{ which = gdd_reform_tooltip_supported_count value = {threshold} }}",
                    ),
                    ("gdd_eoc_member_tooltip_blank", "always = yes"),
                ],
            )
        )

        for component in ("sponsor", "policy", "overlord", "mandate"):
            variable = f"gdd_reform_tooltip_top_{slot}_{component}"
            entries = [
                (
                    f"gdd_eoc_member_top_{slot}_{component}_positive",
                    f"check_variable = {{ which = {variable} value = 0.001 }}",
                )
            ]
            if component != "mandate":
                entries.append(
                    (
                        f"gdd_eoc_member_top_{slot}_{component}_negative",
                        f"NOT = {{ check_variable = {{ which = {variable} value = 0 }} }}",
                    )
                )
            entries.append(("gdd_eoc_member_tooltip_blank", "always = yes"))
            blocks.append(
                defined_text(
                    f"GetGddEocMemberTop{slot}{component.title()}Reason", entries
                )
            )

    blocks.append(
        defined_text(
            "GetGddEocMemberOtherSupportsBlock",
            [
                (
                    "gdd_eoc_member_other_supports_block",
                    "check_variable = { which = gdd_reform_tooltip_supported_count value = 3 }",
                ),
                ("gdd_eoc_member_tooltip_blank", "always = yes"),
            ],
        )
    )
    for reform_id, slug, _ in REFORMS:
        later_reforms = [
            (later_id, later_slug)
            for later_id, later_slug, _ in REFORMS
            if later_id > reform_id
        ]
        later_supported = " ".join(
            [
                "OR = {",
                *[
                    " ".join(
                        [
                            "AND = {",
                            f"has_country_flag = gdd_support_reform_{later_slug}",
                            f"NOT = {{ is_variable_equal = {{ which = gdd_reform_tooltip_top_1_id value = {later_id} }} }}",
                            f"NOT = {{ is_variable_equal = {{ which = gdd_reform_tooltip_top_2_id value = {later_id} }} }}",
                            "}",
                        ]
                    )
                    for later_id, later_slug in later_reforms
                ],
                "}",
            ]
        )
        current_supported = " ".join(
            [
                f"has_country_flag = gdd_support_reform_{slug}",
                f"NOT = {{ is_variable_equal = {{ which = gdd_reform_tooltip_top_1_id value = {reform_id} }} }}",
                f"NOT = {{ is_variable_equal = {{ which = gdd_reform_tooltip_top_2_id value = {reform_id} }} }}",
            ]
        )
        entries = []
        if later_reforms:
            entries.append(
                (
                    f"gdd_eoc_member_other_support_{slug}_continued",
                    f"{current_supported} {later_supported}",
                )
            )
        entries.extend(
            [
                (f"gdd_eoc_member_other_support_{slug}_final", current_supported),
                ("gdd_eoc_member_tooltip_blank", "always = yes"),
            ]
        )
        blocks.append(
            defined_text(
                f"GetGddEocMemberOtherSupport{reform_id:02d}",
                entries,
            )
        )
    return "\n\n".join(blocks) + "\n"


def build_localisation_block() -> str:
    lines = []
    for index in range(1, 66):
        lines.append(
            f' GDD_EOC_MEMBER_SHIELD_{index:02d}_TT:0 "[gdd_eoc_member_roster_{index:02d}.GetGddEocMemberShieldTooltip]"'
        )
    lines.extend(
        [
            ' gdd_eoc_member_tooltip_blank:0 ""',
            ' gdd_eoc_member_tooltip_ai_none:0 "§Y[Root.GetName]§!是周天下成员国。点击打开该国外交页面。\\n------------\\n他们目前不支持任何尚未通过的改革。"',
            ' gdd_eoc_member_tooltip_ai_supported:0 "§Y[Root.GetName]§!是周天下成员国。点击打开该国外交页面。\\n------------[Root.GetGddEocMemberTop1Block][Root.GetGddEocMemberTop2Block][Root.GetGddEocMemberOtherSupportsBlock]"',
        ]
    )
    for reform_id, slug, chinese_name in REFORMS:
        lines.append(f' gdd_eoc_reform_name_{slug}:0 "{chinese_name}"')
        lines.append(
            f' gdd_eoc_member_other_support_{slug}_continued:0 "§Y{chinese_name}§!、"'
        )
        lines.append(
            f' gdd_eoc_member_other_support_{slug}_final:0 "§Y{chinese_name}§!改革"'
        )

    reason_labels = {
        "sponsor": "对改革执行者的态度",
        "policy": "改革收益与本国国情",
        "overlord": "宗主国立场",
        "mandate": "王命高于改革门槛",
    }
    for slot in (1, 2):
        funcs = "".join(
            f"[Root.GetGddEocMemberTop{slot}{component.title()}Reason]"
            for component in ("sponsor", "policy", "overlord", "mandate")
        )
        prefix = "\\n他们还支持" if slot == 2 else "\\n他们支持"
        lines.append(
            f' gdd_eoc_member_top_{slot}_block:0 "{prefix}§Y[Root.GetGddEocMemberTop{slot}Name]§!改革（§G+[Root.gdd_reform_tooltip_top_{slot}_score.GetValue]§!），原因是：{funcs}"'
        )
        for component, label in reason_labels.items():
            variable = f"gdd_reform_tooltip_top_{slot}_{component}"
            lines.append(
                f' gdd_eoc_member_top_{slot}_{component}_positive:0 "\\n{label}：§G+[Root.{variable}.GetValue]§!"'
            )
            if component != "mandate":
                lines.append(
                    f' gdd_eoc_member_top_{slot}_{component}_negative:0 "\\n{label}：§R[Root.{variable}.GetValue]§!"'
                )

    others = "".join(
        f"[Root.GetGddEocMemberOtherSupport{reform_id:02d}]"
        for reform_id, _, _ in REFORMS
    )
    lines.append(
        f' gdd_eoc_member_other_supports_block:0 "\\n另支持{others}"'
    )
    return "\n".join(lines)


def replace_localisation_block(body: str) -> None:
    text = LOCALISATION.read_text(encoding="utf-8")
    before, remainder = text.split(BEGIN, maxsplit=1)
    _, after = remainder.split(END, maxsplit=1)
    LOCALISATION.write_text(
        f"{before}{BEGIN}\n{body}\n{END}{after}", encoding="utf-8"
    )


def main() -> None:
    CUSTOMIZABLE.write_text(build_customizable(), encoding="utf-8")
    replace_localisation_block(build_localisation_block())
    print("generated 65 EoC member tooltip bindings and 20 reform accessors")


if __name__ == "__main__":
    main()
