#!/usr/bin/env python3
"""Static contract checks for the six-school court guest-school lifecycle.

The native eastern-school selector is only a source picker.  The authoritative
state is the guarded scripted contract generated by build_zhx_guest_school.py.
This validator deliberately checks both the generated surface and its doctrine,
academy, reform, localisation, and encoding integration ports.
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from collections import OrderedDict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "guangdong_independent_practice"

SCHOOLS = OrderedDict(
    (
        ("ru", ("zhx_ru_school", "zhx_doctrine_ru", "zhx_ru_invited_scholar_modifier")),
        ("fa", ("zhx_fa_school", "zhx_doctrine_fa", "zhx_fa_invited_scholar_modifier")),
        ("mo", ("zhx_mo_school", "zhx_doctrine_mo", "zhx_mo_invited_scholar_modifier")),
        ("dao", ("zhx_dao_school", "zhx_doctrine_dao", "zhx_dao_invited_scholar_modifier")),
        ("bing", ("zhx_bing_school", "zhx_doctrine_bing", "zhx_bing_invited_scholar_modifier")),
        (
            "zongheng",
            (
                "zhx_zongheng_school",
                "zhx_doctrine_zongheng",
                "zhx_zongheng_invited_scholar_modifier",
            ),
        ),
    )
)

GUEST_PATHS = {
    "triggers": MOD / "common/scripted_triggers/zhx_guest_school_triggers.txt",
    "effects": MOD / "common/scripted_effects/zhx_guest_school_effects.txt",
    "modifiers": MOD / "common/event_modifiers/zhx_guest_school_modifiers.txt",
    "opinions": MOD / "common/opinion_modifiers/zhx_guest_school_opinions.txt",
    "decisions": MOD / "decisions/zhx_guest_school_decisions.txt",
    "events": MOD / "events/zhx_guest_school_events.txt",
}

INTEGRATION_PATHS = {
    "religion": MOD / "common/religions/00_religion.txt",
    "doctrine_effects": MOD / "common/scripted_effects/zhx_doctrine_effects.txt",
    "invited_modifiers": MOD / "common/static_modifiers/zhx_invited_school_modifiers.txt",
    "reform_triggers": MOD / "common/scripted_triggers/zhx_doctrine_reform_triggers.txt",
    "reform_effects": MOD / "common/scripted_effects/zhx_doctrine_reform_effects.txt",
    "academy_triggers": MOD / "common/scripted_triggers/zhx_academy_triggers.txt",
    "academy_effects": MOD / "common/scripted_effects/zhx_academy_effects.txt",
    "custom_text": MOD
    / "customizable_localization/zhx_guest_school_customizable_localization.txt",
    "guest_builder": ROOT / "tools/build_zhx_guest_school.py",
    "religion_builder": ROOT / "tools/build_zhx_religions.py",
    "encoder": ROOT / "tools/encode_eu4_chinese_localisation.py",
}

INVITED_VALUES = {
    "ru": {"advisor_cost": "-0.025", "stability_cost_modifier": "-0.025"},
    "fa": {"global_autonomy": "-0.025", "core_creation": "-0.025"},
    "mo": {"fort_maintenance_modifier": "-0.05", "defensiveness": "0.05"},
    "dao": {"global_unrest": "-0.5", "war_exhaustion": "-0.01"},
    "bing": {"manpower_recovery_speed": "0.05", "army_tradition_decay": "-0.005"},
    "zongheng": {"improve_relation_modifier": "0.10", "diplomatic_reputation": "0.25"},
}


class ContractError(ValueError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ContractError(message)


def read(path: Path) -> str:
    require(path.is_file(), f"missing required file: {path.relative_to(ROOT)}")
    return path.read_text(encoding="utf-8-sig")


def validate_braces(label: str, text: str) -> None:
    depth = 0
    in_string = False
    in_comment = False
    escaped = False
    for char in text:
        if in_comment:
            if char == "\n":
                in_comment = False
            continue
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            continue
        if char == "#":
            in_comment = True
        elif char == '"':
            in_string = True
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            require(depth >= 0, f"{label}: closing brace without opener")
    require(not in_string and depth == 0, f"{label}: unbalanced Clausewitz text")


def block(text: str, key: str) -> str:
    match = re.search(rf"(?m)^[ \t]*{re.escape(key)}\s*=\s*\{{", text)
    require(match is not None, f"missing block {key}")
    opening = text.find("{", match.start())
    depth = 0
    in_string = False
    in_comment = False
    escaped = False
    for index in range(opening, len(text)):
        char = text[index]
        if in_comment:
            if char == "\n":
                in_comment = False
            continue
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            continue
        if char == "#":
            in_comment = True
        elif char == '"':
            in_string = True
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[opening + 1 : index]
    raise ContractError(f"block {key} has no closing brace")


def country_event(text: str, event_id: str) -> str:
    matches: list[str] = []
    cursor = 0
    while True:
        match = re.search(r"(?m)^country_event\s*=\s*\{", text[cursor:])
        if match is None:
            break
        start = cursor + match.start()
        candidate = block(text[start:], "country_event")
        if re.search(rf"(?m)^\s*id\s*=\s*{re.escape(event_id)}\s*$", candidate):
            matches.append(candidate)
        cursor = start + len(candidate) + 2
    require(len(matches) == 1, f"expected exactly one country_event {event_id}")
    return matches[0]


def numeric_assignments(body: str) -> dict[str, str]:
    return dict(
        re.findall(
            r"(?m)^\s*([a-z_]+)\s*=\s*(-?\d+(?:\.\d+)?)\s*$",
            body,
        )
    )


def definitions(text: str, prefix: str) -> set[str]:
    return set(
        re.findall(
            rf"(?m)^({re.escape(prefix)}[a-z0-9_]*)\s*=\s*\{{",
            text,
        )
    )


def load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    require(spec is not None and spec.loader is not None, f"cannot import {path.name}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def load_texts() -> dict[str, str]:
    paths = GUEST_PATHS | INTEGRATION_PATHS
    texts = {name: read(path) for name, path in paths.items()}
    for name, text in texts.items():
        if name not in {"guest_builder", "religion_builder", "encoder"}:
            validate_braces(name, text)
    return texts


def check_generated_outputs(texts: dict[str, str]) -> None:
    guest_builder = load_module(INTEGRATION_PATHS["guest_builder"], "zhx_guest_builder_validation")
    rendered = guest_builder.render_all()
    require(set(rendered) == set(GUEST_PATHS.values()), "guest builder target set changed")
    for path, expected in rendered.items():
        label = next(name for name, target in GUEST_PATHS.items() if target == path)
        require(
            texts[label] == expected.rstrip() + "\n",
            f"stale generated guest-school output: {path.relative_to(ROOT)}",
        )

    religion_builder = load_module(
        INTEGRATION_PATHS["religion_builder"], "zhx_religion_builder_validation"
    )
    expected_schools = block(religion_builder.build_school_block(), "religious_schools")
    eastern = block(texts["religion"], "eastern")
    actual_schools = block(eastern, "religious_schools")
    require(
        actual_schools.strip() == expected_schools.strip(),
        "generated 00_religion native guest-school dispatch is stale",
    )


def validate_semantics(texts: dict[str, str]) -> None:
    triggers = texts["triggers"]
    effects = texts["effects"]
    event_modifiers = texts["modifiers"]
    opinions = texts["opinions"]
    decisions = texts["decisions"]
    events = texts["events"]
    religion = texts["religion"]
    doctrine_effects = texts["doctrine_effects"]
    invited_modifiers = texts["invited_modifiers"]
    reform_triggers = texts["reform_triggers"]
    reform_effects = texts["reform_effects"]
    academy_triggers = texts["academy_triggers"]
    academy_effects = texts["academy_effects"]

    # Six-way symmetry is a hard maintenance contract.
    expected_codes = set(SCHOOLS)
    for prefix, text in (
        ("zhx_guest_school_source_is_eligible_", triggers),
        ("zhx_guest_school_pending_", triggers),
        ("zhx_guest_school_has_valid_", triggers),
        ("zhx_guest_school_ai_wants_", triggers),
        ("zhx_guest_school_begin_", effects),
        ("zhx_guest_school_pick_", effects),
        ("zhx_guest_school_renew_", effects),
        ("zhx_guest_school_expel_reaction_", effects),
    ):
        found = definitions(text, prefix)
        if prefix == "zhx_guest_school_ai_wants_":
            found = {
                name
                for name in found
                if not name.startswith("zhx_guest_school_ai_wants_renew_")
            }
        codes = {
            name.removeprefix(prefix)
            .removesuffix("_is_valid")
            .removesuffix("_renewal_source")
            .removesuffix("_renewal_source")
            for name in found
        }
        if prefix == "zhx_guest_school_has_valid_":
            codes.discard("renewal_source")
        if prefix == "zhx_guest_school_renew_":
            codes.discard("current")
        require(codes == expected_codes, f"six-school symmetry broken for {prefix}: {codes}")

    may_invite = block(triggers, "zhx_guest_school_may_invite")
    for token in (
        "zhx_is_lijiao_country = yes",
        "zhx_has_doctrine = yes",
        "has_religious_school = yes",
        "NOT = { zhx_doctrine_reform_invitation_locked = yes }",
        "NOT = { zhx_guest_school_has_active_contract = yes }",
        "NOT = { has_country_modifier = zhx_guest_school_dishonour }",
        "NOT = { zhx_guest_school_has_any_invited_benefit = yes }",
        "dip_power = 75",
        "years_of_income = 0.5",
    ):
        require(may_invite.count(token) == 1, f"invitation gate missing {token}")
    require(
        all(token not in may_invite for token in ("is_at_war", "stability =", "num_of_loans")),
        "player invitations must remain possible during war, negative stability, or loans",
    )

    active_contract = block(triggers, "zhx_guest_school_has_active_contract")
    require(active_contract.count("zhx_guest_school_contract_active") == 1, "active contract flag missing")
    require(
        all(active_contract.count(f"zhx_guest_school_contract_{code}") == 1 for code in SCHOOLS),
        "active contract must recognize all six school flags",
    )

    for code, (native, doctrine, modifier) in SCHOOLS.items():
        source = block(triggers, f"zhx_guest_school_source_is_eligible_{code}")
        for token in (
            "exists = yes",
            "NOT = { tag = ROOT }",
            "zhx_is_lijiao_country = yes",
            f"has_country_flag = {doctrine}",
            "group = eastern",
            f"school = {native}",
            "has_opinion = { who = ROOT value = 150 }",
            "capital_scope = { ROOT = { has_discovered = PREV } }",
            "NOT = { is_subject_of = ROOT }",
            "NOT = { liberty_desire = 50 }",
        ):
            require(source.count(token) == 1, f"{code} source contract missing {token}")
        require(
            "has_country_modifier" not in source,
            f"{code} guest/old-momentum mirror must not become a third-country source",
        )

        pending = block(triggers, f"zhx_guest_school_pending_{code}_is_valid")
        for token in (
            "zhx_guest_school_may_invite = yes",
            f"NOT = {{ has_country_flag = {doctrine} }}",
            f"has_country_flag = zhx_guest_school_pending_{code}",
            "has_saved_event_target = zhx_guest_school_pending_source",
            f"zhx_guest_school_source_is_eligible_{code} = yes",
        ):
            require(pending.count(token) == 1, f"{code} confirmation revalidation missing {token}")

        wants = block(triggers, f"zhx_guest_school_ai_wants_{code}")
        require(
            wants.count(f"zhx_has_unprotected_{code}_academy = yes") == 1
            and wants.count(f"has_country_flag = zhx_guest_school_ai_plan_{code}") == 1,
            f"AI may invite {code} only for academy protection or an explicit reform plan",
        )
        renewal_wants = block(triggers, f"zhx_guest_school_ai_wants_renew_{code}")
        require(
            renewal_wants.count(f"zhx_has_{code}_academy = yes") == 1
            and f"zhx_has_unprotected_{code}_academy" not in renewal_wants
            and renewal_wants.count(f"has_country_flag = zhx_guest_school_ai_plan_{code}")
            == 1,
            f"AI {code} renewal must not depend on same-day expiry of its own protection",
        )

        begin = block(effects, f"zhx_guest_school_begin_{code}")
        for token in (
            f"zhx_guest_school_pending_{code}_is_valid = yes",
            "zhx_guest_school_pay_contract_cost = yes",
            "zhx_guest_school_mark_pending_source = yes",
            "set_country_flag = zhx_guest_school_contract_active",
            f"set_country_flag = zhx_guest_school_contract_{code}",
            f"add_country_modifier = {{ name = {modifier} duration = 7300 }}",
            "name = zhx_guest_school_adjustment",
            "duration = 1825",
            "zhx_guest_school_toggle_generation_and_schedule = yes",
            "zhx_guest_school_clear_pending = yes",
            "zhx_refresh_academy_country_effects = yes",
        ):
            require(begin.count(token) == 1, f"{code} contract start missing {token}")

        renew = block(effects, f"zhx_guest_school_renew_{code}")
        for token in (
            f"zhx_guest_school_has_valid_{code}_renewal_source = yes",
            f"zhx_guest_school_pick_{code}_renewal_source = yes",
            "zhx_guest_school_pay_contract_cost = yes",
            f"remove_country_modifier = {modifier}",
            f"add_country_modifier = {{ name = {modifier} duration = 7300 }}",
            "remove_country_modifier = zhx_guest_school_adjustment",
            "zhx_guest_school_toggle_generation_and_schedule = yes",
            "zhx_refresh_academy_country_effects = yes",
        ):
            require(renew.count(token) == 1, f"{code} renewal missing {token}")
        require(
            "name = zhx_guest_school_adjustment" not in renew,
            f"{code} same-school renewal must not repeat the five-year adjustment",
        )

        academy_gate = block(academy_triggers, f"zhx_has_unprotected_{code}_academy")
        require(
            academy_gate.count(f"NOT = {{ has_country_modifier = {modifier} }}") == 1,
            f"{code} invited school must protect its named academies",
        )

        live_root = block(reform_triggers, f"zhx_doctrine_reform_has_{code}_invited_root_now")
        require(
            live_root.count(f"has_country_modifier = {modifier}") == 1
            and live_root.count("has_country_flag = zhx_guest_school_contract_active") == 1
            and live_root.count(f"has_country_flag = zhx_guest_school_contract_{code}") == 1,
            f"{code} reform root must read the live contract, school flag, and benefit",
        )
        five_years = block(
            reform_triggers, f"zhx_doctrine_reform_has_{code}_invited_root_with_five_years"
        )
        require(
            five_years.count(f"zhx_doctrine_reform_has_{code}_invited_root_now = yes") == 1
            and five_years.count("flag = zhx_guest_school_contract_active") == 1
            and five_years.count("days = 5475") == 1,
            f"{code} guest-only reform root must retain a five-year-plus-one-day window",
        )
        can_target = block(reform_triggers, f"zhx_doctrine_reform_can_target_{code}")
        require(
            can_target.count("NOT = { zhx_guest_school_has_active_contract = yes }")
            == 1
            and can_target.count(f"has_country_flag = zhx_guest_school_contract_{code}")
            == 1,
            f"{code} reform must reject a different active guest contract",
        )
        retains = block(reform_triggers, f"zhx_doctrine_reform_target_{code}_retains_root")
        require(
            retains.count(f"zhx_doctrine_reform_has_{code}_invited_root_now = yes") == 1
            and retains.count(f"zhx_doctrine_reform_has_active_{code}_academy_root = yes") == 1
            and f"zhx_doctrine_reform_root_invited_{code}" not in retains,
            f"{code} cultivation root must reconcile against live guest/academy state",
        )

    pay = block(effects, "zhx_guest_school_pay_contract_cost")
    require(
        numeric_assignments(pay) == {"add_dip_power": "-75", "add_years_of_income": "-0.5"},
        "each initial contract and renewal must cost exactly 75 DIP plus half-year income",
    )
    require(
        effects.count("zhx_guest_school_pay_contract_cost = yes") == 12,
        "cost effect must be called exactly once by six starts and six renewals",
    )

    adjustment = block(event_modifiers, "zhx_guest_school_adjustment")
    require(
        numeric_assignments(adjustment)
        == {"global_unrest": "1", "stability_cost_modifier": "0.15", "advisor_cost": "0.10"},
        "five-year guest-school adjustment values changed",
    )
    dishonour = block(event_modifiers, "zhx_guest_school_dishonour")
    require(
        numeric_assignments(dishonour)
        == {"diplomatic_reputation": "-1", "stability_cost_modifier": "0.10"},
        "ten-year dishonour values changed",
    )

    for code, (_, _, modifier) in SCHOOLS.items():
        body = block(invited_modifiers, modifier)
        numeric = numeric_assignments(body)
        require(numeric == INVITED_VALUES[code], f"{code} weak invited benefit changed: {numeric}")
        require(
            body.count("religion_sub_modifier = yes") == 1
            and body.count("religion = yes") == 1
            and body.count("is_scholar_modifier = yes") == 1
            and "expire_message_type" not in body,
            f"{code} benefit must remain a lifecycle-owned native sub-modifier",
        )

    schedule = block(effects, "zhx_guest_school_toggle_generation_and_schedule")
    for token in (
        "has_country_flag = zhx_guest_school_generation_a",
        "clr_country_flag = zhx_guest_school_generation_a",
        "set_country_flag = zhx_guest_school_generation_b",
        "id = zhx_guest_school.21 days = 6935",
        "id = zhx_guest_school.31 days = 7300",
        "clr_country_flag = zhx_guest_school_generation_b",
        "set_country_flag = zhx_guest_school_generation_a",
        "id = zhx_guest_school.20 days = 6935",
        "id = zhx_guest_school.30 days = 7300",
    ):
        require(schedule.count(token) == 1, f"A/B stale-callback guard missing {token}")
    clear_state = block(effects, "zhx_guest_school_clear_contract_state")
    require(
        "zhx_guest_school_generation_a" not in clear_state
        and "zhx_guest_school_generation_b" not in clear_state,
        "generation token must survive cleanup so the next contract toggles away from stale callbacks",
    )
    for code, (_, _, modifier) in SCHOOLS.items():
        require(clear_state.count(f"remove_country_modifier = {modifier}") == 1, f"cleanup misses {modifier}")
        require(clear_state.count(f"clr_country_flag = zhx_guest_school_contract_{code}") == 1, f"cleanup misses {code} contract flag")

    for event_id, generation in ((20, "a"), (21, "b"), (30, "a"), (31, "b")):
        body = country_event(events, f"zhx_guest_school.{event_id}")
        require(
            body.count("zhx_guest_school_has_active_contract = yes") == 1
            and body.count(f"has_country_flag = zhx_guest_school_generation_{generation}") == 1,
            f"callback {event_id} must reject inactive or stale-generation contracts",
        )
        for token in (
            "title = OK",
            "desc = OK",
            "picture = DIPLOMACY_eventPicture",
            "hidden = yes",
            "is_triggered_only = yes",
            "option = { name = OK }",
        ):
            require(
                body.count(token) == 1,
                f"callback {event_id} lacks log-complete hidden-event field: {token}",
            )
    require(
        set(re.findall(r"(?m)^\s*id\s*=\s*zhx_guest_school\.(\d+)\s*$", events))
        == {"10", "11", "12", "13", "14", "15", "20", "21", "22", "30", "31", "40", "50"},
        "guest-school event ID contract changed",
    )
    require(
        events.count("tooltip = zhx_guest_school_confirmation_requirements_tt") == 6
        and events.count("custom_trigger_tooltip = {") == 7,
        "all six confirmation options and the renewal option must hide internal eligibility trees",
    )
    require(
        events.count("tooltip = zhx_guest_school_renew_requirements_tt") == 1,
        "renewal option must expose one readable eligibility line",
    )

    ai_renew = block(triggers, "zhx_guest_school_ai_may_renew")
    for token in (
        "ai = yes",
        "is_at_war = no",
        "stability = 0",
        "NOT = { num_of_loans = 1 }",
        "dip_power = 125",
        "years_of_income = 0.5",
        "zhx_guest_school_has_valid_renewal_source = yes",
    ):
        require(ai_renew.count(token) == 1, f"AI renewal gate missing {token}")
    for code in SCHOOLS:
        require(
            ai_renew.count(
                f"AND = {{ has_country_flag = zhx_guest_school_contract_{code} zhx_guest_school_ai_wants_renew_{code} = yes }}"
            )
            == 1,
            f"AI renewal for {code} lacks academy/plan intent",
        )

    normal = block(effects, "zhx_guest_school_close_normally")
    require(
        normal.count("zhx_guest_school_honour_source = yes") == 1
        and normal.count("zhx_guest_school_clear_contract_state = yes") == 1
        and normal.count("zhx_refresh_academy_country_effects = yes") == 1
        and normal.count("zhx_doctrine_reform_reconcile = yes") == 1,
        "normal expiry must honour the source, clear state, refresh academies, and reconcile reform",
    )
    opinion_values = {
        "zhx_opinion_guest_school_source_link": {"opinion": "1", "yearly_decay": "0"},
        "zhx_opinion_guest_school_honoured": {"opinion": "25", "yearly_decay": "2.5"},
        "zhx_opinion_guest_school_expelled_source": {"opinion": "-100", "yearly_decay": "10"},
        "zhx_opinion_guest_school_expelled_school": {"opinion": "-25", "yearly_decay": "2.5"},
    }
    for name, expected in opinion_values.items():
        require(numeric_assignments(block(opinions, name)) == expected, f"opinion contract changed: {name}")

    expel = block(effects, "zhx_guest_school_expel_current")
    require(
        expel.count("add_stability = -1") == 1
        and expel.count("name = zhx_guest_school_dishonour") == 1
        and expel.count("duration = 3650") == 1
        and expel.count("zhx_guest_school_clear_contract_state = yes") == 1
        and expel.count("zhx_refresh_academy_country_effects = yes") == 1
        and expel.count("zhx_doctrine_reform_reconcile = yes") == 1
        and "add_aggressive_expansion" not in expel,
        "early expulsion must apply the complete ten-year domestic cost and reconciliation",
    )
    for code, (_, doctrine, _) in SCHOOLS.items():
        reaction = block(effects, f"zhx_guest_school_expel_reaction_{code}")
        require(
            reaction.count(f"has_country_flag = {doctrine}") == 1
            and reaction.count("modifier = zhx_opinion_guest_school_expelled_school") == 1
            and reaction.count("modifier = zhx_opinion_guest_school_source_link") == 1
            and reaction.count("NOT = {") >= 1,
            f"{code} expulsion reaction must target formal same-school countries and exclude the source",
        )
    require(
        expel.count("modifier = zhx_opinion_guest_school_expelled_source") == 1,
        "early expulsion must give the surviving source -100 separately",
    )

    clear_wrapper = block(doctrine_effects, "zhx_clear_invited_school_modifiers")
    require(
        clear_wrapper.strip() == "zhx_guest_school_clear_silently = yes",
        "all doctrine/religion cleanup must delegate to the idempotent contract cleanup",
    )
    require(
        "zhx_refresh_academy_country_effects = {" in academy_effects,
        "named-academy refresh integration port is missing",
    )
    require(
        "zhx_doctrine_reform_reconcile = {" in reform_effects,
        "main-school reform reconciliation port is missing",
    )

    decision_body = block(block(decisions, "country_decisions"), "zhx_expel_guest_school")
    require(
        decision_body.count("ai = no") == 1
        and decision_body.count("zhx_guest_school_has_active_contract = yes") == 1
        and decision_body.count("allow = { always = yes }") == 1
        and decision_body.count("country_event = { id = zhx_guest_school.50 }") == 1
        and decision_body.count("factor = 0") == 1,
        "early expulsion must remain a player-only separately confirmed decision",
    )

    # Native eastern cards stage one confirmation each; no free direct grant remains.
    schools_block = block(block(religion, "eastern"), "religious_schools")
    for event_index, (code, (native, doctrine, modifier)) in enumerate(SCHOOLS.items(), start=10):
        school = block(schools_block, native)
        for phase in ("potential_invite_scholar", "can_invite_scholar"):
            phase_body = block(school, phase)
            require(phase_body.count("zhx_guest_school_may_invite = yes") == 1, f"{native} {phase} lacks shared gate")
            require(phase_body.count(f"zhx_guest_school_source_is_eligible_{code} = yes") == 1, f"{native} {phase} lacks formal source gate")
            require(
                phase_body.count("custom_trigger_tooltip = {") == 3
                and phase_body.count("hidden_trigger = {") == 1
                and "tooltip = zhx_guest_school_inviter_requirements_tt" in phase_body
                and f"tooltip = zhx_guest_school_not_current_{code}_tt" in phase_body
                and f"tooltip = zhx_guest_school_source_{code}_requirements_tt" in phase_body,
                f"{native} {phase} must collapse its player conditions and hide the AI gate",
            )
            for token in ("limit = { ai = yes }", "is_at_war = no", "stability = 0", "NOT = { num_of_loans = 1 }", "dip_power = 125", f"zhx_guest_school_ai_wants_{code} = yes"):
                require(phase_body.count(token) == 1, f"{native} {phase} AI-only gate missing {token}")
        on_body = block(school, "on_invite_scholar")
        for token in (
            "zhx_guest_school_may_invite = yes",
            f"zhx_guest_school_source_is_eligible_{code} = yes",
            "zhx_guest_school_clear_pending = yes",
            f"set_country_flag = zhx_guest_school_pending_{code}",
            "FROM = { save_event_target_as = zhx_guest_school_pending_source }",
            "custom_tooltip = zhx_guest_school_native_confirmation_tt",
            f"country_event = {{ id = zhx_guest_school.{event_index} }}",
        ):
            require(on_body.count(token) == 1, f"{native} native dispatch missing {token}")
        require(
            all(token not in on_body for token in ("add_dip_power", "add_years_of_income", "add_country_modifier")),
            f"{native} must not grant or charge before confirmation",
        )
        require(school.count(f"invite_scholar_modifier_display = {modifier}") == 1, f"{native} display modifier mismatch")

    # No startup/on-action fixture is required: all lifecycle callbacks are scheduled at acceptance.
    fixture_name = re.compile(r"(?:zhxtest|fatest|motest|guest[_-]?school.*test|runtime[_-]?test|fixture)", re.I)
    leaked_files = sorted(
        path.relative_to(ROOT).as_posix()
        for path in MOD.rglob("*")
        if path.is_file() and fixture_name.search(path.name)
    )
    require(not leaked_files, f"temporary guest-school fixture files remain: {leaked_files}")
    production_guest = "\n".join(texts[name] for name in (*GUEST_PATHS, "religion", "doctrine_effects", "reform_triggers", "reform_effects"))
    require(
        not re.search(r"(?:zhxtest|fatest|motest|ZHX_DIRECT_|TEMP(?:ORARY)?[_ ](?:FIXTURE|HARNESS))", production_guest, re.I),
        "temporary guest-school fixture token remains in production scripts",
    )


def validate_localisation(texts: dict[str, str]) -> None:
    sys.path.insert(0, str(ROOT / "tools"))
    try:
        encoder = load_module(INTEGRATION_PATHS["encoder"], "zhx_guest_encoder_validation")
    finally:
        sys.path.pop(0)
    source_name = "zhx_guest_school_readable_utf8.txt"
    require(source_name in encoder.FILES, "guest-school localisation source is not registered in encoder FILES")
    source = MOD / "localisation_source" / source_name
    target = MOD / "localisation" / encoder.FILES[source_name]
    readable = read(source)
    require(target.is_file(), f"missing encoded guest-school localisation: {target.name}")
    encoder.verify_file(source, target)

    keys = re.findall(r'(?m)^\s*([^\s:#]+):\d+\s+"', readable)
    require(len(keys) == len(set(keys)), "duplicate guest-school localisation keys")
    required = {
        "zhx_guest_school_native_confirmation_tt",
        "zhx_expel_guest_school_title",
        "zhx_expel_guest_school_desc",
        "zhx_guest_school_adjustment",
        "zhx_guest_school_adjustment_desc",
        "zhx_guest_school_dishonour",
        "zhx_guest_school_dishonour_desc",
        "zhx_guest_school_contract_cost_tt",
        "zhx_guest_school_confirmation_requirements_tt",
        "zhx_guest_school_renew_requirements_tt",
        "zhx_guest_school_renew_cost_tt",
        "zhx_guest_school_send_home_tt",
        "zhx_guest_school_expel_cost_tt",
        "zhx_guest_school.reminder.t",
        "zhx_guest_school.reminder.d",
        "zhx_guest_school.reminder.no_source.d",
        "zhx_guest_school.expiry.t",
        "zhx_guest_school.expiry.d",
        "zhx_guest_school.expiry.no_source.d",
        "zhx_guest_school.expel.t",
        "zhx_guest_school.expel.d",
        "zhx_guest_school.expel.no_source.d",
        "zhx_opinion_guest_school_source_link",
        "zhx_opinion_guest_school_honoured",
        "zhx_opinion_guest_school_expelled_source",
        "zhx_opinion_guest_school_expelled_school",
    }
    for code in SCHOOLS:
        required |= {
            f"zhx_guest_school_name_{code}",
            f"zhx_guest_school.confirm_{code}.t",
            f"zhx_guest_school.confirm_{code}.d",
            f"zhx_guest_school.confirm_{code}.a",
        }
    require(required <= set(keys), f"missing guest-school localisation keys: {sorted(required - set(keys))}")
    for token in ("75", "半年", "五年", "二十年", "+25", "-100", "-25"):
        require(token in readable, f"guest-school localisation omits approved term/cost token: {token}")

    custom = texts["custom_text"]
    name_body = block(custom, "defined_text")
    require(name_body.count("name = GetZhxGuestSchoolName") == 1, "guest-school identity text missing")
    for code in SCHOOLS:
        require(
            name_body.count(f"localisation_key = zhx_guest_school_name_{code}") == 1
            and name_body.count(f"has_country_flag = zhx_guest_school_contract_{code}") == 1,
            f"custom guest-school identity lacks {code}",
        )


def run_mutation_tests(texts: dict[str, str]) -> None:
    mutations = (
        ("cost", "effects", "add_dip_power = -75", "add_dip_power = -74"),
        ("source opinion", "triggers", "value = 150", "value = 149"),
        ("five-year adjustment", "effects", "duration = 1825", "duration = 1824"),
        ("twenty-year callback", "effects", "id = zhx_guest_school.30 days = 7300", "id = zhx_guest_school.30 days = 7299"),
        ("hidden callback event completeness", "events", "title = OK", "title = ZHX_MISSING_TEST_TITLE"),
        ("AI reserve", "triggers", "dip_power = 125", "dip_power = 124"),
        ("normal honour", "effects", "zhx_guest_school_honour_source = yes", "zhx_guest_school_honour_source = no"),
        ("reform window", "reform_triggers", "days = 5475", "days = 5474"),
        ("native dispatch", "religion", "id = zhx_guest_school.10", "id = zhx_guest_school.99"),
        ("weak benefit", "invited_modifiers", "advisor_cost = -0.025", "advisor_cost = -0.024"),
    )
    passed = 0
    for label, file_key, old, new in mutations:
        mutated = dict(texts)
        require(old in mutated[file_key], f"mutation fixture no longer matches: {label}")
        mutated[file_key] = mutated[file_key].replace(old, new, 1)
        try:
            validate_semantics(mutated)
        except ContractError:
            passed += 1
        else:
            raise ContractError(f"validator failed to detect in-memory mutation: {label}")
    print(f"  Mutation checks: {passed}/{len(mutations)} rejected")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--self-test-mutations",
        action="store_true",
        help="also prove critical contracts reject in-memory mutations",
    )
    args = parser.parse_args()
    try:
        texts = load_texts()
        check_generated_outputs(texts)
        validate_semantics(texts)
        validate_localisation(texts)
        if args.self_test_mutations:
            run_mutation_tests(texts)
    except (ContractError, ValueError) as exc:
        raise SystemExit(f"guest-school validation failed: {exc}") from None
    print("Guest-school contract validation passed.")
    print(f"  Schools: {len(SCHOOLS)}")
    print("  Costs/terms: 75 DIP + half-year income; 5-year adjustment; 20-year term")
    print("  Lifecycle: native confirmation, A/B callbacks, renewal, honour, expulsion")


if __name__ == "__main__":
    main()
